### ISSUE TITLE
[Video] Exclude already colorized Images from the process in video

### ISSUE THREAD

**Issue by jqueguiner** [jantic/DeOldify#110]
Exclude already colorized Images from the process in mixt B&W + Color videos

**Comment by jantic** [comment]
That does seem to be a common use case from what I've come across.  I'll keep this open for now as it seems like a legit good feature.

**Comment by jqueguiner** [comment]
In fact I took and documentary from WWII and half of the images were colorized. A good use case is history documentaries when you have archive videos mixed with historian interviews ! It’s just crazy every day I think deoldify is changing the way we consume media

**Comment by jantic** [comment]
Upon further consideration- this is adding a bit too much complication and potential unreliability for something that won't be used by the vast majority of users. Detecting reliably whether or not something is already colorized isn't entirely trivial. This is one of those things that I think is better left up to manual intervention.,
