### ISSUE TITLE
Frames Per Second (FPS) calculation for video is slightly inaccurate

### ISSUE THREAD

**Issue by jantic** [jantic/DeOldify#113]
Title says it all.  This is leading to the audio synchronization issues that are being reported. @jqueguiner fyi

**Comment by mgrankin** [comment]
There is no need to calculate the frame rate. The way to go is just copy it from the source video. For instance, my video the frame rate is '30000/1001', but if you divide and round it will be 30 and this will slightly desynchronise video with the audio.

**Comment by jantic** [comment]
Fixed. Dood- thank you
