### ISSUE TITLE
'colorizer' is not defined in Colab

### ISSUE THREAD

**Issue by arjunpar** [jantic/DeOldify#115]
I tried to DeOldify on th Colab but I am getting the following error
NameError                                 Traceback (most recent call last)
<ipython-input-2-f71b8c4f866c> in <module>()
      3 
      4 if source_url is not None and source_url !='':
----> 5     image_path = colorizer.plot_transformed_image_from_url(url=source_url, render_factor=render_factor, compare=True)
      6     show_image_in_notebook(image_path)
      7 else:

NameError: name 'colorizer' is not defined

**Comment by jqueguiner** [comment]
Try to rerun from scratch the notebook starting from line 1 :

https://colab.research.google.com/github/jantic/DeOldify/blob/master/ImageColorizerColab.ipynb#scrollTo=00_GcC_trpdE&line=2&uniqifier=1

**Comment by arjunpar** [comment]
Thanks a lot @jqueguiner it worked. New to Colab...

**Comment by guillefunes** [comment]
Hello I am also trying to use DeOldify but for a video, and I am getting the same error:
5 if source_url is not None and source_url !='':
----> 6     video_path = colorizer.colorize_from_url(source_url, 'video.mp4', render_factor, watermarked=watermarked)
      7     show_video_in_notebook(video_path)
      8 else:

NameError: name 'colorizer' is not defined

**Comment by jantic** [comment]
@guillefunes - using Colab or Notebook?  Then jqueguiner 's instructions above apply just the same either way.

Otherwise, please clarify your situation- what you're trying to run and how.

**Comment by guillefunes** [comment]
> @guillefunes - using Colab or Notebook? Then jqueguiner 's instructions above apply just the same either way.
> 
> Otherwise, please clarify your situation- what you're trying to run and how.

Sorry, my bad. Already worked. Thanks

**Comment by Archviz360** [comment]
im stuck on this error 

ameError                                 Traceback (most recent call last)
<ipython-input-15-d41e8163fe4e> in <module>
----> 1 colorizer = get_image_colorizer(artistic=True)

NameError: name 'get_image_colorizer' is not defined

**Comment by jantic** [comment]
@Archviz360 Did you make sure to run each cell in order as discussed above? The specific cell that needs to run successfully to avoid the error you're seeing is this one (but make sure to run all of them in order of course!)

![image](https://user-images.githubusercontent.com/179759/127714169-fd8490cd-f938-4b5e-b45b-30ab6a172d6e.png)

**Comment by lashavsdz** [comment]
hello, I have an issue. when i run: **colorizer = get_image_colorizer(artistic=True)**
I get error like this:

EOFError                                  Traceback (most recent call last)
[<ipython-input-7-d41e8163fe4e>](https://localhost:8080/#) in <module>
----> 1 colorizer = get_image_colorizer(artistic=True)

5 frames
[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    918             "functionality.")
    919 
--> 920     magic_number = pickle_module.load(f, **pickle_load_args)
    921     if magic_number != MAGIC_NUMBER:
    922         raise RuntimeError("Invalid magic number; corrupt file?")

EOFError: Ran out of input

![image](https://user-images.githubusercontent.com/103876658/197165632-c86829ae-6276-4bc0-9204-9f4f267e7ee7.png)

**Comment by rajmonpraveen** [comment]
getting the same error as lashavsdz. Ran all in the order and getting the same error.

**Comment by gulyaslevente** [comment]
I'm also getting the same error, ran everything in order and tried from different accounts and different computers, nothing worked.

**Comment by rajmonpraveen** [comment]
Working for me now.

In cell 6 add "--no-check-certificate" to !wget
!wget --no-check-certificate url

**Comment by jantic** [comment]
Since it's a certificate issue on DeepAI's end, I'm going to wait this out for them to resolve it. It'll probably be a relatively short term issue.

**Comment by cc1311** [comment]
Hello, I have an issue when I run cell2 in local, there are Errors: Permission Error:13
`PermissionError                           Traceback (most recent call last)
Cell In[2], line 1
----> 1 from deoldify.visualize import *
      2 plt.style.use('dark_background')
      3 import warnings

File D:\Deoldify\DeOldify-master\deoldify\visualize.py:8
      6 from PIL import Image
      7 import ffmpeg
----> 8 import yt_dlp as youtube_dl
      9 import gc
     10 import requests

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\__init__.py:19
     17 from .compat import compat_shlex_quote
     18 from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
---> 19 from .downloader.external import get_external_downloader
     20 from .extractor import list_extractor_classes
     21 from .extractor.adobepass import MSO_INFO

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\downloader\__init__.py:26
     24 from .common import FileDownloader
     25 from .dash import DashSegmentsFD
---> 26 from .external import FFmpegFD, get_external_downloader
     27 from .f4m import F4mFD
     28 from .fc2 import FC2LiveFD

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\downloader\external.py:12
     10 from .fragment import FragmentFD
     11 from ..compat import functools
---> 12 from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
     13 from ..utils import (
     14     Popen,
     15     RetryManager,
   (...)
     29     traverse_obj,
     30 )
     33 class Features(enum.Enum):

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\postprocessor\__init__.py:38
     35 from .xattrpp import XAttrMetadataPP
     36 from ..plugins import load_plugins
---> 38 _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
     41 def get_postprocessor(key):
     42     return globals()[key + 'PP']

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:135, in load_plugins(name, suffix)
    132 def load_plugins(name, suffix):
    133     classes = {}
--> 135     for finder, module_name, _ in iter_modules(name):
    136         if any(x.startswith('_') for x in module_name.split('.')):
    137             continue

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:119, in iter_modules(subpackage)
    117 fullname = f'{PACKAGE_NAME}.{subpackage}'
    118 with contextlib.suppress(ModuleNotFoundError):
--> 119     pkg = importlib.import_module(fullname)
    120     yield from pkgutil.iter_modules(path=pkg.__path__, prefix=f'{fullname}.')

File C:\ProgramData\Anaconda3\envs\deoldify\lib\importlib\__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1014, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:991, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:971, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:914, in _find_spec(name, path, target)

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:96, in PluginFinder.find_spec(self, fullname, path, target)
     93 if fullname not in self.packages:
     94     return None
---> 96 search_locations = self.search_locations(fullname)
     97 if not search_locations:
     98     return None

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:88, in PluginFinder.search_locations(self, fullname)
     86     elif path.name and any(path.with_suffix(suffix).is_file() for suffix in {'.zip', '.egg', '.whl'}):
     87         with contextlib.suppress(FileNotFoundError):
---> 88             if parts in dirs_in_zip(path):
     89                 locations.add(str(candidate))
     90 return locations

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:37, in dirs_in_zip(archive)
     35 @functools.cache
     36 def dirs_in_zip(archive):
---> 37     with ZipFile(archive) as zip:
     38         return set(itertools.chain.from_iterable(
     39             Path(file).parents for file in zip.namelist()))

File C:\ProgramData\Anaconda3\envs\deoldify\lib\zipfile.py:1251, in ZipFile.__init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1249 while True:
   1250     try:
-> 1251         self.fp = io.open(file, filemode)
   1252     except OSError:
   1253         if filemode in modeDict:

PermissionError: [Errno 13] Permission denied: 'D:\\Deoldify\\DeOldify-master'`
