### ISSUE TITLE
how to fine-tune my dataset?

### ISSUE THREAD

**Issue by osakaka** [jantic/DeOldify#117]
Thank to share this wonderful project! I want to know how to fine-tune my dataset, because i dont really familiar with pytorch or fastai, so i dont how to do this. I also try to implement other methods which not include GAN method, but i dont get satisfied picture.  Please help me, thanks!

**Comment by jantic** [comment]
I think you'll need to be familiar with Pytorch and FastAI first.  Start there!  There's no shortcuts in this case.
