### ISSUE TITLE
Deep Learning-Based Frame Interpolation

### ISSUE THREAD

**Issue by jantic** [jantic/DeOldify#119]
Feature request: frame interpolation via last week's Google paper https://arxiv.org/abs/1905.10240

**Comment by chakri-muthyala** [comment]
So you're thinking about frame interpolation for colorization, like colorizing a perfect frames and interpolating colorization in between?

**Comment by jantic** [comment]
Interpolation in general.  In fact I think it may be more effective to do it pre-colorization.

**Comment by jantic** [comment]
Upon further consideration, I think this is beyond the scope of what we want to do for DeOldify.  There are other offerings out there that already do this quite well.
