### ISSUE TITLE
pretrained resnet 

### ISSUE THREAD

**Issue by omniasaleh** [jantic/DeOldify#128]
in training are you freeze layers from resnet ?!

**Comment by jantic** [comment]
Yes- both freezing initially and then unfreezing later.  This follows practice advocated by fast.ai.  Freezing of the resnet portion is implicit in the creation of the DynamicUnet, so I don't have the code explicitly freezing it currently.  This would probably make the code clearer though.

**Comment by omniasaleh** [comment]
gen_freeze_tos=[-1]
that means you only train the  last layer in all layers in genrator 
 gen_freeze_tos=[0]
that means you train all layers in genrator 
that is right or not?
thanks

**Comment by jantic** [comment]
Oh man you're looking at old code (archived elsewhere- see https://github.com/dana-kelley/DeOldify).  That's not even done anymore in the current code.  

That being said, gen_freeze_tos[-1] actually means freezing just the encoder in this case (the resnet backbone).  Then yes, gen_freeze_to[0] is unfreezing everything.  Confusing I know.  It's an old fastai convention.
