### ISSUE TITLE
Multiple Learning rates

### ISSUE THREAD

**Issue by RihamHazem** [jantic/DeOldify#129]
Hello,
I've noticed in your old project that you're using for the discriminator and generator three learning rate. So how does this work?

![image](https://user-images.githubusercontent.com/15961470/60350637-431b1980-99c4-11e9-8771-e2277b75fcbf.png)

**Comment by jantic** [comment]
This is a fastai thing.  Going to close this and refer you to that.  https://docs.fast.ai/basic_train.html#Discriminative-layer-training
