### ISSUE TITLE
Exeption:[Errno 2] No such file or directory: 'models\\tmp4586lc_d'

### ISSUE THREAD

**Issue by flowerpotmf** [jantic/DeOldify#132]
I get this when I try to run colorizer = get_video_colorizer()

Exception: [Errno 2] No such file or directory: 'models\\tmp4586lc_d'
Can't write to 'models', set `learn.model_dir` attribute in Learner to a full libpath path that is writable

I have put the ColorizeVideo_crit and gen .pths in the 'models' folder in DeOldify. 

I'm unsure of what to do next and stuck. Help Please. :) 

FULL THING IS DOWN BELOW:

Exception                                 Traceback (most recent call last)
<ipython-input-4-81c07a854ecc> in <module>
----> 1 colorizer = get_video_colorizer()

~\DeOldify\fasterai\visualize.py in get_video_colorizer(render_factor)
    188 
    189 def get_video_colorizer(render_factor:int=21)->VideoColorizer:
--> 190     return get_stable_video_colorizer(render_factor=render_factor)
    191 
    192 def get_stable_video_colorizer(root_folder:Path=Path('./'), weights_name:str='ColorizeVideo_gen', 

~\DeOldify\fasterai\visualize.py in get_stable_video_colorizer(root_folder, weights_name, results_dir, render_factor)
    192 def get_stable_video_colorizer(root_folder:Path=Path('./'), weights_name:str='ColorizeVideo_gen', 
    193         results_dir='result_images', render_factor:int=21)->VideoColorizer:
--> 194     learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
    195     filtr = MasterFilter([ColorizerFilter(learn=learn)], render_factor=render_factor)
    196     vis = ModelImageVisualizer(filtr, results_dir=results_dir)

~\DeOldify\fasterai\generators.py in gen_inference_wide(root_folder, weights_name, nf_factor, arch)
     10       learn = gen_learner_wide(data=data, gen_loss=F.l1_loss, nf_factor=nf_factor, arch=arch)
     11       learn.path = root_folder
---> 12       learn.load(weights_name)
     13       learn.model.eval()
     14       return learn

B:\ProjectColour\anacondapy3\lib\site-packages\fastai\basic_train.py in load(self, file, device, strict, with_opt, purge, remove_module)
    259              with_opt:bool=None, purge:bool=True, remove_module:bool=False):
    260         "Load model and optimizer state (if `with_opt`) `file` from `self.model_dir` using `device`. `file` can be file-like (file or buffer)"
--> 261         if purge: self.purge(clear_opt=ifnone(with_opt, False))
    262         if device is None: device = self.data.device
    263         elif isinstance(device, int): device = torch.device('cuda', device)

B:\ProjectColour\anacondapy3\lib\site-packages\fastai\basic_train.py in purge(self, clear_opt)
    299     def purge(self, clear_opt:bool=True):
    300         "Purge the `Learner` of all cached attributes to release some GPU memory."
--> 301         self._test_writeable_path()
    302         attrs_all = [k for k in self.__dict__.keys() if not k.startswith("__")]
    303         attrs_pkl = ['bn_wd', 'callback_fns', 'layer_groups', 'loss_func', 'metrics', 'model',

B:\ProjectColour\anacondapy3\lib\site-packages\fastai\basic_train.py in _test_writeable_path(self)
    175         try: tmp_file = get_tmp_file(path)
    176         except OSError as e:
--> 177             raise Exception(f"{e}\nCan't write to '{path}', set `learn.model_dir` attribute in Learner to a full libpath path that is writable") from None
    178         os.remove(tmp_file)
    179 

Exception: [Errno 2] No such file or directory: 'models\\tmp4586lc_d'
Can't write to 'models', set `learn.model_dir` attribute in Learner to a full libpath path that is writable

**Comment by flowerpotmf** [comment]
I unticked read only on the 'models' folder. Seems to have fixed it. Now I get 

RuntimeError: CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 6.00 GiB total capacity; 1.09 GiB already allocated; 196.68 MiB free; 27.63 MiB cached)

Using windows 10 and I think I saw another thread for this so will look up now.

**Comment by jantic** [comment]
Ok since we have a thread for that memory issue I'm going to close this.

**Comment by jon0x0** [comment]
So this 'can't write to models' issue is a problem, trying to set up DeOldify on a new Linux installation and is what I am getting also. It's not clear to me which 'models' dir this refers to, and I have tried making them all writable to no avail.  Can you please help with a more indepth example. Thank you

**Comment by jantic** [comment]
@jon0x0  So the models directory behavior is a fastai thing, and what they do is default to the base directory being wherever the training/val images folder is.  By default that's defined in the notebooks like this:

path = Path('data/imagenet/ILSVRC/Data/CLS-LOC')

So in there (that's relative to where you're running the notebook). That is to say, it's going to try to read/write to a models folder here:

**Comment by Enom2** [comment]
Hello! There are none of the paths you indicated:

./data/imagenet/ILSVRC/Data/CLS-LOC/models
path = Path ('data / imagenet / ILSVRC / Data / CLS-LOC')

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-6-81c07a854ecc> in <module>
----> 1 colorizer = get_video_colorizer()

~/DeOldify/deoldify/visualize.py in get_video_colorizer(render_factor)
    357 
    358 def get_video_colorizer(render_factor: int = 21) -> VideoColorizer:
--> 359     return get_stable_video_colorizer(render_factor=render_factor)
    360 
    361 

~/DeOldify/deoldify/visualize.py in get_stable_video_colorizer(root_folder, weights_name, results_dir, render_factor)
    378     render_factor: int = 21
    379 ) -> VideoColorizer:
--> 380     learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
    381     filtr = MasterFilter([ColorizerFilter(learn=learn)], render_factor=render_factor)
    382     vis = ModelImageVisualizer(filtr, results_dir=results_dir)

~/DeOldify/deoldify/generators.py in gen_inference_wide(root_folder, weights_name, nf_factor, arch)
     13     )
     14     learn.path = root_folder
---> 15     learn.load(weights_name)
     16     learn.model.eval()
     17     return learn

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/fastai/basic_train.py in load(self, file, device, strict, with_opt, purge, remove_module)
    259              with_opt:bool=None, purge:bool=True, remove_module:bool=False):
    260         "Load model and optimizer state (if `with_opt`) `file` from `self.model_dir` using `device`. `file` can be file-like (file or buffer)"
--> 261         if purge: self.purge(clear_opt=ifnone(with_opt, False))
    262         if device is None: device = self.data.device
    263         elif isinstance(device, int): device = torch.device('cuda', device)

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/fastai/basic_train.py in purge(self, clear_opt)
    299     def purge(self, clear_opt:bool=True):
    300         "Purge the `Learner` of all cached attributes to release some GPU memory."
--> 301         self._test_writeable_path()
    302         attrs_all = [k for k in self.__dict__.keys() if not k.startswith("__")]
    303         attrs_pkl = ['bn_wd', 'callback_fns', 'layer_groups', 'loss_func', 'metrics', 'model',

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/fastai/basic_train.py in _test_writeable_path(self)
    175         try: tmp_file = get_tmp_file(path)
    176         except OSError as e:
--> 177             raise Exception(f"{e}\nCan't write to '{path}', set `learn.model_dir` attribute in Learner to a full libpath path that is writable") from None
    178         os.remove(tmp_file)
    179 

Exception: [Errno 2] No such file or directory: 'models/tmpsm5w3cv9'
Can't write to 'models', set `learn.model_dir` attribute in Learner to a full libpath path that is writable

**Comment by abuzahid** [comment]
1. Create a folder named "models" inside "DeOldify" folder.
2. Download these [three](https://github.com/jantic/DeOldify#completed-generator-weights) weights and paste inside "models" folder.
It solved my issue.

**Comment by royal-ai** [comment]
1，set the learn.model_dir in the generators.py
The source code is showed below:
def gen_inference_wide(
    root_folder: Path, weights_name: str, nf_factor: int = 2, arch=models.resnet101) -> Learner:
    data = get_dummy_databunch()
    learn = gen_learner_wide(
        data=data, gen_loss=F.l1_loss, nf_factor=nf_factor, arch=arch
    )
    learn.path = root_folder
    print(weights_name)
    learn.model_dir="/home/xc/AIModel/DeOldify/models"
    learn.load(weights_name)
    learn.model.eval()
    return learn

It works for me

**Comment by prabathbr** [comment]
> 
> 
>     1. Create a folder named "models" inside "DeOldify" folder.
> 
>     2. Download these [three](https://github.com/jantic/DeOldify#completed-generator-weights) weights from  **Completed Generator Weights** and paste inside "models" folder.
>        It solved my issue.

Thanks a lot, this is the only solution worked for me on Windows 10. Downloading only "ColorizeArtistic_gen.pth" was enough for image colorizing with artistic model [ colorizer = get_image_colorizer(artistic=True) ].
