### ISSUE TITLE
OSError: cannot identify image file <_io.BytesIO object at 0x7fea708661a8>

### ISSUE THREAD

**Issue by flowerpotmf** [jantic/DeOldify#133]
I have the videocolorizercolab working fine. 

When it comes to the imagecolorizercolab i'm not having any luck. 

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-ab9bcac82075> in <module>()
      3 
      4 if source_url is not None and source_url !='':
----> 5     image_path = colorizer.plot_transformed_image_from_url(url=source_url, render_factor=render_factor, compare=True)
      6     show_image_in_notebook(image_path)
      7 else:

2 frames
/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)
   2570         fp.close()
   2571     raise IOError("cannot identify image file %r"
-> 2572                   % (filename if filename else fp))
   2573 
   2574 #

OSError: cannot identify image file <_io.BytesIO object at 0x7fea708661a8>

any idea?

**Comment by jantic** [comment]
Yes, this would happen if you used a link that's not actually directly linking to an image.  For example, if you use an imgur link, you have to be careful.  

This won't work:  https://imgur.com/WOiOMCD

This will:  https://i.imgur.com/WOiOMCD.png

That might seem strange but the former is the link to the page as a whole, and the latter is the actual direct link to the image.  When you go to that link in the first url, you can get the actual image link (second url) by right clicking on the image itself and selecting "Copy Image Address" or whatever the equivalent option is that you have.
