### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by alexandrevicenzi** [jantic/DeOldify#150]
If you set the render_factor too high you will end up with "CUDA out of memory", nothing abnormal here.

The problem starts when you lower the render_factor, you still get "CUDA out of memory" because what was allocated with that factor is not completely freed, calling `torch.cuda.empty_cache()` does not seems to help, I had to delete the colorizer (`del colorizer`) to free up memory.

`colorizer.plot_transformed_image_from_url` should probably free resources after it finishes the colorization.

I got this on Colab. My Colab has both models (Stable and Artistic) loaded, render_factor 45 works, no problem there, can run multiple times, even switching models, but if I crank up to 60 there's no way back, can set to 10 and still will have no memory.

**Comment by kirkgutierrdd** [comment]
Same here seems to be a memory leak

**Comment by alexandrevicenzi** [comment]
@kirkgutierrdd If running locally give it a try to [nvidia-smi](https://manpages.ubuntu.com/manpages/precise/en/man1/alt-nvidia-current-smi.1.html) cmd line to free up memory.

Otherwise, there's a need to look at what is leaking memory in DeOldify or maybe even underling libs.
