### ISSUE TITLE
Dehazing

### ISSUE THREAD

**Issue by gguynn** [jantic/DeOldify#158]
This seems very promising.  Could this be incorporated into your project for better results?

http://www.wisdom.weizmann.ac.il/~vision/DoubleDIP/
https://github.com/yossigandelsman/DoubleDIP

**Comment by jantic** [comment]
It's an interesting paper and results but it's not really in the spirit of what this project is trying to achieve.  DeOldify is strictly attempting to restore/enhance photographs to make them look like they were taken more recently.  This dehazing paper is actually modifying the appearance of the subject matter itself (altering reality).

**Comment by gguynn** [comment]
Very good.  Thanks for clearing that up.
