### ISSUE TITLE
ONNX export failed on ATen operator dot because torch.onnx.symbolic.dot does not exist

### ISSUE THREAD

**Issue by shahidul56** [jantic/DeOldify#159]
/root/miniconda3/envs/deoldify/lib/python3.7/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator dot because torch.onnx.symbolic.dot does not exist
  .format(op_name, op_name))

Environment:
os: ubuntu 18
name: deoldify
channels:
- fastai
- conda-forge
- defaults
dependencies:
- python>=3.7.3
- fastai=1.0.51
- pytorch=1.0.1
- ffmpeg=4.1.1
- tensorboardX=1.6
- youtube-dl>=2019.4.17
- jupyterlab
- pip:
  - ffmpeg-python==0.1.17
  - opencv-python>=3.3.0.10

![ferfe](https://user-images.githubusercontent.com/11449967/65688452-fa3f3380-e08c-11e9-9594-4635bae262c8.PNG)

**Comment by jantic** [comment]
This was touched on in this issue here:  https://github.com/jantic/DeOldify/issues/121 .  The short of it is:  It's a fastai bug.   From the issue there's this comment (Onnx is spelled incorrectly...doh!)

> The Onyx error you're getting there is because of a change in fastai's Tensorboard callback plugin that was added to generate a of the model. It's annoying but not going to cause actual breaking issues. I just commented out that stuff myself in the fastai core code.
