### ISSUE TITLE
Allow more video formats for local files

### ISSUE THREAD

**Issue by Ichaelus** [jantic/DeOldify#162]
Thanks for keeping this project up, I'll discontinue https://github.com/Ichaelus/video-colorization since you including a video colorization mode that basically does the same as I did.

As I'm trying out the new mode, I'll open a few issues to improve its usability. 

In [the video colorizer notebook](https://github.com/jantic/DeOldify/blob/master/VideoColorizer.ipynb), you describe `file_name_ext` as _There's no reason to changes this._ - but indeed there is! I think it would be quite easy to allow any video format accepted by ffmpeg. Right now, this is not possible since "mp4" is hardcoded on quite a few locations.

Thank you for looking into this.

**Comment by jantic** [comment]
This wasn't just a lazy decision actually.  It was quite deliberate. First, the notebooks are meant to be used for videos that have urls (convenient and the most common use case so far). So the video generation just picks .mp4 to keep things simple.  The ingested videos are thus 100% consistent in terms of how they're encoded, etc.  This is actually really important in minimizing maintenance and keeping things working 100%. And that's basically the big thing I'm aiming for- low maintenance, low bugs, low fuss.  

So I'd say any effort to work on local files more robustly will want to keep this in mind.  The dual edge sword aspect of adding more features to anything is that you also add more bugs (that's inevitable, I'd argue).

**Comment by alexandrevicenzi** [comment]
On a side note, MP4 is a standard pretty much everywhere, and MP4 is just a container, you can change change a video from MKV to MP4 without re-encoding as long they use the same coded.

H264 and H265, or any other coded is something completely different and should not be misunderstood.

For local files I would suggest to just run ffmpeg by yourself before inputting into the notebook.

We could definitely have these ffmpeg commands in a Wiki.

**Comment by Ichaelus** [comment]
I think this is a reasonable argument against my proposal. It should be made clear though for users of the exposed API (like [VideoColorizer#colorize_from_file_name](https://github.com/jantic/DeOldify/blob/e01dd6b4cdc11f512e319e090604b81d4860a948/deoldify/visualize.py#L176)), e.g. by including the term "mp4" in the method name and/or adding instructions to the wiki.

**Comment by alexandrevicenzi** [comment]
@Ichaelus we will do that, we're working on better docs.
