### ISSUE TITLE
Temporal consistency loss

### ISSUE THREAD

**Issue by hfarazi** [jantic/DeOldify#163]
I want to add temporal consistency loss to the model. Any idea would be appreciated. 
Another question is how can I retain it from scratch?

**Comment by jantic** [comment]
I do have an idea but i can't give it away yet.  It's a trade secret for now.  Sorry!

**Comment by jantic** [comment]
Oh an you can retrain from scratch by using the training notebooks (ColorizeTrainingArtistic.ipynb, for example). You'd need to download whatever datasets you want to use (I'd recommend big like imagenet) and extracting it to the directory the notebook is looking at. The path in the notebook by default is data/imagenet/ILSVRC/Data/CLS-LOC (relative to where you're running the jupyter instance from which is assumed to be the same folder as your notebook).  That folder should contain a train and val folder, and inside those contains a folder for each class of objects, and inside each of those are the original color photos themselves.  Once you have those, then just run the notebook and follow the instructions.

**Comment by alexandrevicenzi** [comment]
@hfarazi , @jantic  I created a [wiki page](https://github.com/jantic/DeOldify/wiki/Retrain-from-scratch) with this information for future reference.

Anyone can add more details there if needed.

**Comment by jantic** [comment]
@alexandrevicenzi  Fantastic!
