### ISSUE TITLE
Enchased colorization

### ISSUE THREAD

**Issue by shadowzoom** [jantic/DeOldify#164]
If this possible to rewrite script to just good autocolor image? Like i want to automate colors on this image https://i.imgur.com/PXnJjFc.jpg but my colorization knowledgence is poor

**Comment by alexandrevicenzi** [comment]
@shadowzoom improving the quality of images is not what this project aims for, this project is to colorize old images, AKA as black and white images.

Perhaps what you look for is something like [https://letsenhance.io/](https://letsenhance.io/).

**Comment by jantic** [comment]
Agreed 100% with @alexandrevicenzi .  Thanks!
