### ISSUE TITLE
When new version will be released?

### ISSUE THREAD

**Issue by shadowzoom** [jantic/DeOldify#165]
And if new version will be avialable in google colab?

**Comment by alexandrevicenzi** [comment]
@shadowzoom what you mean by a new version?

You can find the latest version on Colab and GitHub itself.

**Comment by shadowzoom** [comment]
@alexandrevicenzi  I mean this version https://www.youtube.com/watch?v=u9Z3lCmIOlg author sayed that this version still not released yet

**Comment by jantic** [comment]
@shadowzoom New version will release when it's complete :) Commercial first before open source. It'll probably be Google Colab again, yes.
