### ISSUE TITLE
No such file or directory in ColorizeTrainingStable.py

### ISSUE THREAD

**Issue by cyrilzakka** [jantic/DeOldify#169]
I'm trying to train my own colorizing model on Colab but I can't seem to get the example project up and running for some reason. When trying to run the following line: 
`learn_gen.fit_one_cycle(1, pct_start=0.8, max_lr=slice(1e-3))`

I get the following error:` No such file or directory: '/content/data/images_dir/00951.png`.

I thought this might be a problem with files stored in Drive, so I moved everything to the runtime environment but I still run into the same issue. 

Runtime/Drive are both structured as so:

```
data 
│
└───images_dir
│   │  000958.png
│   │   ...
│   │
│   └───bnw
│       │   000958.png
│       │   ...
│   
└───dummy
    │   000958.png
```
I've changed the relevant paths but to no avail. I've also noticed that the image mentioned in the error message randomly goes missing from the folder when running the cell, but all other images remain. It's a different image that goes missing every time. Any thoughts?

**Comment by alexandrevicenzi** [comment]
Training notebooks are not built for Colab, but for your local computer.

Perhaps you need to do some tinkering with paths to get it working.

**Comment by jantic** [comment]
Yeah I'm going to sound a bit mean here. But I'm  just going to lay down the law here and say we're not here to debug your own projects where you're doing something that we didn't code for. This is going to be a pretty simple issue to address if you just take the time to look at what the code's doing.  Not our job.
