### ISSUE TITLE
Greatly increase max resolution output by taking advantage of this chrominance optimization

### ISSUE THREAD

**Issue by jantic** [jantic/DeOldify#17]
Source: MayeulC on HackerNews, thread:

https://news.ycombinator.com/item?id=18363870#18369410

"Now, there seems to be a distinct loss of details in the restored images. The network being resolution-limited, is the black-and-white image displayed at full resolution besides the restored one?

What I would like to see is the output of the network to be treated as chrominance only.

Take the YUV transform of both the input and output images, scale back the UV matrix of the restored one to match the input, and replace the original channels. I'd be really curious to look at the output (and would do it myself if I was not on a smartphone)!"

**Comment by jantic** [comment]
And....This is done!  So happy about this one.

**Comment by MayeulC** [comment]
All right, your explanation makes sense. I was expecting the dimensionality gains to propagate down the layers, but it is true that it might only provide tangible gains in the first (and last) channels. And the fact that you are using a pre-trained network also makes sense!

I am afraid I can't really provide much more interesting input for your project, I wish you the best of luck with it, and I look forward to its next iterations!

**Comment by jantic** [comment]
@MayeulC Dude, you made such a huge impact on this project already!  That was the single most impactful improvement I've been able to make on the rendering.  So thank you thank you thank you.
