### ISSUE TITLE
Here is a StopIteration

### ISSUE THREAD

**Issue by UserJTZhang** [jantic/DeOldify#175]
Sorry, I know you have written the code as well as possible, but it may be my personal ability. When I run to ‘ `learn_gen.fit_one_cycle(1, pct_start=0.8, max_lr=slice(1e-3))` ’, there is an ‘StopIteration’ report. I don't know how to solve it. Maybe it's because of the data folder structure？

**Comment by UserJTZhang** [comment]
I try to run "ColorizeTrainingStable.ipython", but when I run to `data_gen = get_data(bs=bs, sz=sz, keep_pct=keep_pct)`, I was told "IndexError: index 0 is out of bounds for axis 0 with size 0", so I change keep_pct=0.9, is it ok?

**Comment by jantic** [comment]
Yeah that'd be an issue you'd run into if the data loader fails to find the expected training data in the format expected.  Here's what that should look like:

There should be a data folder in the root DeOldify folder (where the notebooks are).  Inside that would be the imagenet data.  I used exactly what I got from downloading imagenet so the training/validation sets are in here:  data/imagenet/ILSVRC/Data/CLS-LOC

In that folder you'd have these two folders:

![image](https://user-images.githubusercontent.com/179759/69890177-74688000-12a9-11ea-8c7f-f6684992dd79.png)

train folder looks like this- each of the folders contains images belonging to the folder's class:

![image](https://user-images.githubusercontent.com/179759/69890255-af6ab380-12a9-11ea-87d0-2f3337003091.png)

val folder looks the same(except not nearly as much data of course).

Finally make sure that this runs in that ColorizeTrainingStable.ipython notebook:

![image](https://user-images.githubusercontent.com/179759/69890334-f0fb5e80-12a9-11ea-939f-2efd800f9d45.png)

It'll make the corresponding black and white images from those folders I just described and drop them in a newly created data/imagenet/ILSVRC/Data/CLS-LOC/bandw folder.   If you don't do that you'll see the error you're describing in this issue.

**Comment by jantic** [comment]
Also I wouldn't change the keep_pct value.  That just determines what percentage of the data is pulled from the folders to train with that I just described.  1.0 would mean all the data (100%).  0.5 would mean 50%.

**Comment by UserJTZhang** [comment]
Now I know why I was get this error, but when I run this line

![](https://user-images.githubusercontent.com/179759/69890334-f0fb5e80-12a9-11ea-939f-2efd800f9d45.png)

I get nothing, my floder not create the "data/imagenet/ILSVRC/Data/CLS-LOC/bandw", I just get the photo number 

![image](https://user-images.githubusercontent.com/45026028/70196596-36091000-1744-11ea-80cb-0609a1c6af7b.png)

This means that the image was read but not converted to black and white, I can't get black and white, so what should I do. I really don't know where have problem.

**Comment by UserJTZhang** [comment]
The `il.items` have been read

![image](https://user-images.githubusercontent.com/45026028/70197493-03ace200-1747-11ea-94b8-4c9375ed8eb0.png)

**Comment by kroslaniec** [comment]
@jantic 

This step was not explained in notebooks or Readme, I hope that you could help me with it. I downloaded some data from Imagenet, but it has a different structure than yours. I modified it, created train and val folders, but I am not sure where to place files.
Also, this step: parallel(create_training_images, il.items) does not work. I can also print il.items, but the bandw is not created, and next step throws error IndexError: index 0 is out of bounds for axis 0 with size 0 because of this

**Comment by jantic** [comment]
@kroslaniec just do what it takes to match the folder structure I described above, link here:  https://github.com/jantic/DeOldify/issues/175#issuecomment-559881554

As to what should go in train/val - if you're really needing to make that manually then just pull a small percentage of random images from train and put them in val. 1% perhaps?

I won't be able to go beyond this though and start helping to debug here though- that will take too much time and I'm a bit busy.
