### ISSUE TITLE
Can't create “bandw” floder 

### ISSUE THREAD

**Issue by UserJTZhang** [jantic/DeOldify#177]
Now I know why I was get this error, but when I run this line：
![image](https://user-images.githubusercontent.com/179759/69890334-f0fb5e80-12a9-11ea-939f-2efd800f9d45.png)
I get nothing, my floder not create the "data/imagenet/ILSVRC/Data/CLS-LOC/bandw", I just get the photo number and seconds in the jupyter notebook
![image](https://user-images.githubusercontent.com/45026028/70196786-c8a9af00-1744-11ea-85ba-26f3756b36f5.png)
This means that the image was read but not converted to black and white, I can't get black and white, so what should I do. I really don't know where have problem.

The il.items have been read
![image](https://user-images.githubusercontent.com/45026028/70197493-03ace200-1747-11ea-94b8-4c9375ed8eb0.png)

**Comment by UserJTZhang** [comment]
Maybe I've solved the problem, I used other methods, I don't know if it's right.

![image](https://user-images.githubusercontent.com/45026028/70328023-0f95c280-1873-11ea-9b6a-daee0537959a.png)

But I have a new problem.My computer is windows10 and GPU is 2080ti(11G), have 16G RAM. I put train data 200 and val data 50.

 When I run to the `learn_gen.fit_one_cycle`, it told me ` CUDA out of memory`.

![image](https://user-images.githubusercontent.com/45026028/70328580-5a640a00-1874-11ea-8a6f-68dbb07a0638.png)

Can I solve this problem by adjusting the parameters.

And I don't know the meaning of `bs=88` `sz=64`, can I adjust them?

**Comment by alexandrevicenzi** [comment]
DeOldify is only tested, developed and supported on Linux. On Windows, you may see weird errors and we can't help getting it up on Windows.

**Comment by UserJTZhang** [comment]
But in theory, it may not be a system problem. I want to ask which parameters involve memory usage, so that I can adjust myself until I can run successfully

**Comment by jantic** [comment]
If you have 16GB GPU ram the existing settings should be fine.  This was all designed around 11GB.  bs is batch size (lowering it will lower your memory requirements).  sz is image size in pixels (they're squared).

But otherwise I think you're on your own on this one.  @alexandrevicenzi is right.
