### ISSUE TITLE
Amazing! But one of my photos is getting always green. 

### ISSUE THREAD

**Issue by WittmannF** [jantic/DeOldify#179]
First of all, congratulations! This is one of my favorite applications of deep learning. I was wondering if you could give me some insight of a particular case. I am trying to colorize the following picture of my grandfather:

![Miguel_1](https://user-images.githubusercontent.com/5733246/71427033-0a69ad80-2692-11ea-8a7a-60c78a4e04d4.jpg)

However, for all rendering values, the output is coming green:

![Screen Shot 2019-12-24 at 22 13 01](https://user-images.githubusercontent.com/5733246/71427038-32591100-2692-11ea-9c67-6737530055b9.png)
![Screen Shot 2019-12-24 at 22 12 44](https://user-images.githubusercontent.com/5733246/71427039-32f1a780-2692-11ea-86ce-99f01a878cc8.png)
![Screen Shot 2019-12-24 at 22 12 36](https://user-images.githubusercontent.com/5733246/71427040-32f1a780-2692-11ea-9292-f4347b70ae49.png)

Is there any other parameter that I could try besides `render_factor`? I captured the photo using Camscanner. Maybe I should use a better scanner?

Thanks in advance!

**Comment by jantic** [comment]
So what you have here is a pretty exceptional aspect ratio, where the photo is much taller than it is wide. This is actually contributing most to what you're seeing- the model simply wasn't trained to deal with images that have these sorts of dimensions.  In fact all images are reduced to a smaller square before they're fed through the model.  So what happens in this case is that this image gets super distorted in that process.  My guess is that the one thing it still recognizes in the image is the plants and so it just decides to make everything green.

SO the answer here to get a decent result is to crop the image. If you do that you get a much better result:

Current open source model, using render_factor at 22:  
![cropped2](https://user-images.githubusercontent.com/179759/71652985-c8b6b380-2cde-11ea-89a1-0b74e8f7b77f.png)

Bonus:  New model I'm working on (unreleased)
![cropped3](https://user-images.githubusercontent.com/179759/71652998-dec47400-2cde-11ea-8680-5de37df73e1f.png)

You'd get an even better result if the image wasn't so grainy- not sure if you can do anything about that.

**Comment by WittmannF** [comment]
Thank you @jantic! That totally makes sense!

**Comment by WittmannF** [comment]
@jantic , I don't want to disturb you so much, but any other hint beside the aspect ratio?

I squared the following picture:
![vo](https://user-images.githubusercontent.com/5733246/71786091-8ba43700-2fe6-11ea-9e84-929ca14aefc2.png)


But still, the pictures are not being correctly colored. I think it is due to its low quality. Here's what I get:

![Screen Shot 2020-01-05 at 19 11 15](https://user-images.githubusercontent.com/5733246/71786109-cc9c4b80-2fe6-11ea-8d42-67b6227dd7b7.png)


![Screen Shot 2020-01-05 at 19 11 22](https://user-images.githubusercontent.com/5733246/71786112-d160ff80-2fe6-11ea-97e4-52c7c238c8a8.png)

Overall, I am getting very good results! Here are some pictures that it colored quite well:

![Screen Shot 2020-01-05 at 19 12 47](https://user-images.githubusercontent.com/5733246/71786131-1be27c00-2fe7-11ea-8947-0fc037c88612.png)


Thank you again!

**Comment by jantic** [comment]
Yeah there's a pretty easy answer to this one- The lower quality the photo is, the harder time you're going to have getting a decent result. Makes sense, right?  The main things to be done is to reduce noise, sharpen the image, and improve the contrast.  Easier said than done and unfortunately not all situations can be rectified like this.
