### ISSUE TITLE
Video Implementation

### ISSUE THREAD

**Issue by jantic** [jantic/DeOldify#18]
This will only be tackled once image generation is significantly improved.

**Comment by jantic** [comment]
So first- that's awesome! Surprisingly good quality in certain spots.   Somebody else is actually doing great video stuff as well and I'll be posting his Colab notebook for it in about two-three weeks.  After I get a new model up which should largely address rendering inconsistency issues that happen to be magnified by video (the flashing colors, for example).

As far as the memory issue is concerned:  Try using this method instead:

vis.get_transformed_image_as_pil('./income/black_images/output_' + name + '.png', render_factor=42)

You'll have to save the pil image returned yourself but it won't be producing a pyplot image which is what is causing your problem here apparently.

**Comment by django554** [comment]
Hey @jantic - are you able to post the 'great video stuff' you have mentioned? Thanks!

**Comment by jantic** [comment]
@django554  Oops...Yeah so time frames changed a bit.  Sorry about that.  There's actually a set date that we're working with (and we definitely can't kick the can on) to release this stuff once and for all.  That'll be end of April.  Since the Jan 20 comment of mine, things have improved rather drastically.

**Comment by django554** [comment]
Now you are making me very curious :-) I will be following your project.

**Comment by jantic** [comment]
Video implementation is now up.  Enjoy!  Closifying.
