### ISSUE TITLE
Do we have anyone that has a colab notebook that can run any ColorizeTraining file?

### ISSUE THREAD

**Issue by JonathanSum** [jantic/DeOldify#190]
I tried to run the ColorizeTrainingArtistic.ipynb on colab, but it fails. I 
Failed attemp: https://colab.research.google.com/drive/1JS3zoP_TCl3kmogQWYwM0tO2vBIrMaR9
Dataset: https://drive.google.com/file/d/1dgS6dgsbNrFWT3gBtxO9RLd05sfkfVlP/view

**Comment by jantic** [comment]
Unfortunately this isn't something that we'll support here, for a number of reasons.  Big one is that basically Google won't let you run it long enough to train (it takes a few days- it times out at 12 hours). So it's basically just not doable.

**Comment by JonathanSum** [comment]
Hi, Jason Antic. I am sorry for bothering you. 
There are some tricks that we can run the colab more than 12 hours, and I have been training the lesson7 notebook for almost 18 hours or 20 hours every day.  In addition, you can upgrade to Colab pro is just 9.99 dollars can have 30 more GB ram and 24 hours run times. 

I have had running hours issues, but I can solve it by export the model and trained weight to the google drive once the training part1 is down, and I can train it in part2.
If you can, could you tell me what tech did you use in your deoldify project and the paper I have to read that I can learn by myself and build another deoldify?

**Comment by jantic** [comment]
Your best bet is going to be the [readme](https://github.com/jantic/DeOldify/blob/master/README.md), and then just following along with the [ColorizeTrainingArtistic](https://github.com/jantic/DeOldify/blob/master/ColorizeTrainingArtistic.ipynb) notebook (there's some documentation in there). I'm not sure what your background is but you should have a pretty solid background in deep learning already (FastAI courses, for example). The training of this particular stuff isn't easy unfortunately, even for people with the background.

To be clear on why we're not supporting a ColorizeTrainingArtistic Colab version:  
1. Indeed, you have to employ clever workarounds and/or buy Colab pro.  Very few people are going to want to do this.
2. More importantly, we can't be everything for everyone here.  We're making deliberate choices about how to spend our time and what we'll support (hence not supporting Windows). It's about sane time and resource management.
