### ISSUE TITLE
Colab ImageColorizer is not working properly

### ISSUE THREAD

**Issue by n10ty** [jantic/DeOldify#194]
Have next issue with ImageColorizerColab.ipynb
This happen after yesterday changes related to watermark (which, by the way, is not working, as I can see)
![Screen Shot 2020-02-20 at 15 46 33](https://user-images.githubusercontent.com/2970001/74939496-a563d700-53f8-11ea-9f16-3cd8dfe06e21.png)

**Comment by alexandrevicenzi** [comment]
Could you be a little more descriptive? Just saying that it does not work is not that helpful.

**Comment by jantic** [comment]
@n10ty  I've fixed the issues.  Basically I made a series of bad decisions yesterday.  Sorry about that!

**Comment by n10ty** [comment]
@alexandrevicenzi  sorry, I thought it's enough to attach screenshot
@jantic thanks!
