### ISSUE TITLE
Can't create environment.yml (Windows 10 - Anaconda)

### ISSUE THREAD

**Issue by petem266** [jantic/DeOldify#195]
Tried running DeOldify on the latest Winx64 version of Anaconda. 
However, the environment.yml creation always fails with numerous conflicts concerning incompatible packages. I tried downgrading conda and various other workarounds I found via google. Any ideas as to what might be causing the issue? 

************************************************************
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for fastai jupyterlab:  80%|████████████████████████████████▊        | 8/10 [00:05<00:01,  1.38it/s]|failed                                                                                                        |      -

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 111, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda_env\installers\conda.py", line 32, in install
        prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "C:\Users\petem\Anaconda3\lib\site-packages\conda\models\match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ C:\Users\petem\Anaconda3\Scripts\conda-env-script.py create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\petem\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\petem\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\petem\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\petem\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\petem\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\petem
                     PATH=C:\Users\petem\Anaconda3;C:\Users\petem\Anaconda3\Library\mingw-w64\bi
                          n;C:\Users\petem\Anaconda3\Library\usr\bin;C:\Users\petem\Anaconda3\Li
                          brary\bin;C:\Users\petem\Anaconda3\Scripts;C:\Users\petem\Anaconda3\bi
                          n;C:\Users\petem\Anaconda3;C:\Users\petem\Anaconda3\Library\mingw-w64\
                          bin;C:\Users\petem\Anaconda3\Library\usr\bin;C:\Users\petem\Anaconda3\
                          Library\bin;C:\Users\petem\Anaconda3\Scripts;C:\Users\petem\Anaconda3\
                          bin;C:\Users\petem\Anaconda3\condabin;C:\Windows\system32;C:\Windows;C
                          :\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\
                          Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program
                          Files\Git\cmd;C:\Users\petem\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\petem\Anaconda3
            shell level : 1
       user config file : C:\Users\petem\.condarc
 populated config files : C:\Users\petem\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\petem\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\petem\Anaconda3\pkgs
                          C:\Users\petem\.conda\pkgs
                          C:\Users\petem\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\petem\Anaconda3\envs
                          C:\Users\petem\.conda\envs
                          C:\Users\petem\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

(base) C:\Users\petem\pythonstuff\DeOldify>

**Comment by jantic** [comment]
Hi @petem266 ! So unfortunately Windows support is one of those things we've drawn a line on and have the stance that it's beyond the scope of what we're willing to support for this project.  There's many reasons for that, but one big one is that generally the deep learning ecosystem simply isn't tailored around Windows.  Windows is basically neglected. So for us to chase issues stemming from that fact just seems to be not worth it.  Granted, this alienates a lot of users and that's unfortunate, but it boils down to a simple question of time management for us.  And sanity.

That all being said, I did make an honest effort to look at the error text you posted there.  It's certainly not obvious what Anaconda is complaining about there, I can tell you that much. 

If you can do this, your best bet by far would be to install a dual boot of Ubuntu 18.04 on your machine and run DeOldify from that.  If I remember correctly, when you install Ubuntu it'll give you the option to make it a dual boot with Windows if you already have Windows on the machine.  But I'd double check on that before proceeding.

**Comment by alexandrevicenzi** [comment]
Based on the traceback it seems to me that the bug is in Anaconda itself, maybe you can try to use another Anaconda version or file an issue in their project.

**Comment by alexandrevicenzi** [comment]
@petem266 take the [official example](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually) from Anaconda docs and try to reproduce the bug.

**Comment by petem266** [comment]
Having tested things on an Ubuntu, I am starting to believe that Conda seems to be the issue.

I went back to Windows, downgraded my conda (to 4.6.14). This caused the environment creation to crash at FASTAI / PYTORCH. I edited the environment.yml and moved FASTAI under PIP just to see what happens. Well, this caused the environment to be created without a single error message.  The environment was also activated by conda without any issues. 
However, FASTAI was not installed as it was "missing" when running the jupyter notebook. 

Trying to install Fastai 1.0.51 into the environment however produced a "failed to build bottleneck" error and an error about Microsoft Visual C++ 14 missing. So, some progress was made, but new errors have occurred.

**Comment by jantic** [comment]
Thanks @petem266 ! This is good to know.

**Comment by oyvigri** [comment]
My god Im glad I stumbled upon this issue. Note to self: Check the "Issues" tab ALOT sooner.
Thank you for creating this issue and for continous feedback @petem266.

Im currently trying to setup this on my Windows 10 machine but have come across some of your mentioned errors. You have currently helped me to get past my previous errors atleast.

Could you take me through the process step by step in order to make this work ? (I understand if its a hassle, so no worries if you dont) 

Ive tried so much now and Im just completelly lost. Think I have 5 different python versions installed and anaconda aswell as miniconda installed.

Uninstalled Everything and started from scratch...
-----------------------------------------------------

Where Im currently at:

installed Anaconda3-2019.10-Windows-x86_64
setup the following ENV variables

C:\\users\xxx\Anaconda3
C:\\users\xxx\Anaconda3\Scripts
C:\\users\xxx\Anaconda3\Library\bin

Copied
libcrypto-1_1-x64.*
libssl-1_1-x64.*
from C:\\users\xxx\Anaconda3\Library\bin to C:\\users\xxx\Anaconda3\DLLs

(in order to get rid of the following error
`Error Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available.` )

changed the environment.yml to the following, atleast thats what I figured from your previous comment.
```
name: deoldify
channels:
- fastai
- conda-forge
- defaults
- pytorch
dependencies:
- python>=3.7.3
- pytorch=1.0.1
- ffmpeg=4.1.1
- tensorboardX=1.6
- youtube-dl>=2019.4.17
- jupyterlab
- pillow=6.2.1
- pip:
  - ffmpeg-python==0.1.17
  - opencv-python>=3.3.0.10
  - wandb
  - fastai=1.0.51
```

After runing `conda env create -f environment.yml` Im now stuck with "endless" `InvalidArchiveError`
Example: 
```
InvalidArchiveError("Error with archive C:\\Users\\XXX\\Anaconda3\\pkgs\\prometheus_client-0.7.1-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to open 'C:\\Users\\XXX\\Anaconda3\\pkgs\\prometheus_client-0.7.1-py_0.tar.bz2'")
```

Any help would be GREATLY appreciated.

**Comment by oyvigri** [comment]
seeing this post is marked as "closed", of which I assume noone in this thread will recieve any further notifications, Im trying this -> @ping @petem266

**Comment by oyvigri** [comment]
OK so I got a step closer.
Reinstalled everything again (python, anaconda etc.)

Downloaded same anaconda version as mentioned above (4.7.12) with python version 3.7 installer.

cloned repo, edited the environment.yml file to the following:
```
name: deoldify
channels:
- fastai
- conda-forge
- defaults
- pytorch
dependencies:
- python>=3.7.3
- fastai=1.0.51
- pytorch=1.0.1
- ffmpeg=4.1.1
- tensorboardX=1.6
- youtube-dl>=2019.4.17
- jupyterlab
- pillow=6.2.1
- pip:
  - ffmpeg-python==0.1.17
  - opencv-python>=3.3.0.10
  - wandb
```
and FINALLY could run `conda env create -f environment.yml` succesfully
Since Im on Windows `source conda activate deoldify` doesnt work, but `conda activate deoldify` does.
Got the error `CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.` when trying conda activate, so opened Git bash in the Deoldify folder and ran `conda init bash`. Reopened git bash and then ran `jupyter lab`.

This created a localhost on port 8888 and opened a sort of webapp.

**Comment by jantic** [comment]
@oyvigri  Thanks for this very detailed writeup and research.  I've been on vacation so I just got around to looking at this now.  

This will be a great resource for those power users who really really want to run DeOldify on Windows.  That being said, I don't plan on adding changes to support Windows, because that means we'll be promising support on that platform and opening a can of worms with maintenance on a platform that is generally just not well supported in the deep learning community.  It's a practical decision more than anything.  

Honestly, I secretly prefer Windows myself (heresy!). But not enough to open the flood gates on additional issues and corner cases to hunt down.

**Comment by oyvigri** [comment]
Hi again Jantic and thank you for your response.
I was just wondering about where I can download the imagenet dataset file.
I did download it a while ago but have been having some issues which resulted me in starting over, and forgot where I downloaded it.

**Comment by jantic** [comment]
@oyvigri  Join the competition (no obligations in doing so), then you can download, [here](https://www.kaggle.com/c/imagenet-object-localization-challenge/data)

**Comment by oyvigri** [comment]
Yes that was the link. Thank you very much. Greatly appreciated.
Have a nice day.
