### ISSUE TITLE
undefined symbol: nvrtcGetProgramLogSize(Ubuntu18.04.3, Anaconda)

### ISSUE THREAD

**Issue by yusenfei** [jantic/DeOldify#196]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c38fbfd2d71d> in <module>
----> 1 from deoldify.visualize import *
      2 plt.style.use('dark_background')
      3 torch.backends.cudnn.benchmark=True

~/DeOldify/deoldify/visualize.py in <module>
----> 1 from fastai.core import *
      2 from fastai.vision import *
      3 from matplotlib.axes import Axes
      4 from matplotlib.figure import Figure
      5 from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/fastai/core.py in <module>
      1 "`fastai.core` contains essential util functions to format and split data"
----> 2 from .imports.core import *
      3 
      4 warnings.filterwarnings("ignore", message="numpy.dtype size changed")
      5 warnings.filterwarnings("ignore", message="numpy.ufunc size changed")

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/fastai/imports/__init__.py in <module>
      1 from .core import *
----> 2 from .torch import *

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/fastai/imports/torch.py in <module>
----> 1 import torch, torch.nn.functional as F
      2 from torch import ByteTensor, DoubleTensor, FloatTensor, HalfTensor, LongTensor, ShortTensor, Tensor
      3 from torch import nn, optim, as_tensor
      4 from torch.utils.data import BatchSampler, DataLoader, Dataset, Sampler, TensorDataset
      5 from torch.nn.utils import weight_norm, spectral_norm

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/torch/__init__.py in <module>
    100     pass
    101 
--> 102 from torch._C import *
    103 
    104 __all__ += [name for name in dir(_C)

ImportError: /home/yusenfei/anaconda3/envs/deoldify/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: nvrtcGetProgramLogSize
---------------------------------------------------------------------------------------------------------
my packages
---------------------------------------------------------------------------------------------------------
# packages in environment at /home/yusenfei/anaconda3/envs/deoldify:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.8.2                    py37_0    conda-forge
blas                      1.0                         mkl    defaults
bleach                    3.1.1                      py_0    conda-forge
bottleneck                1.3.2            py37hc1659b7_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                      pypi_0    pypi
configparser              4.0.2                    pypi_0    pypi
cryptography              2.8              py37h72c5cf5_1    conda-forge
cudatoolkit               10.0.130                      0    defaults
cudnn                     7.6.5                cuda10.0_0    defaults
cycler                    0.10.0                     py_2    conda-forge
cymem                     2.0.2            py37he1b5a44_0    fastai
cython-blis               0.2.4            py37h516909a_1    fastai
dataclasses               0.6                        py_0    fastai
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docker-pycreds            0.4.0                    pypi_0    pypi
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastai                    1.0.51                        1    fastai
fastprogress              0.2.2                      py_0    fastai
ffmpeg                    4.1.1                h167e202_0    conda-forge
ffmpeg-python             0.1.17                   pypi_0    pypi
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
future                    0.18.2                   pypi_0    pypi
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gitdb2                    3.0.2                    pypi_0    pypi
gitpython                 3.0.8                    pypi_0    pypi
glib                      2.58.3          py37h6f030ca_1002    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
gql                       0.2.0                    pypi_0    pypi
graphql-core              1.1                      pypi_0    pypi
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
importlib_metadata        1.5.0                    py37_0    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.16.0                   py37_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_core              4.6.3                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.11.4               h8b12597_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.3                    py37_0    conda-forge
matplotlib-base           3.1.3            py37h250f245_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py37h516909a_0    conda-forge
mkl_fft                   1.1.0            py37hc1659b7_1    conda-forge
mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
murmurhash                1.0.0            py37he1b5a44_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
ninja                     1.10.0               hc9558a2_0    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numexpr                   2.7.1            py37hb3f55d8_0    conda-forge
numpy                     1.18.1           py37h4f9e942_0    defaults
numpy-base                1.18.1           py37hde5b4d6_1    defaults
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
opencv-python             4.2.0.32                 pypi_0    pypi
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.1            py37hb3f55d8_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.1                      py_0    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.1            py37hd70f55b_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
plac                      0.9.6                      py_1    conda-forge
preshed                   2.0.1            py37he1b5a44_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
promise                   2.3                      pypi_0    pypi
prompt_toolkit            3.0.3                      py_0    conda-forge
protobuf                  3.11.4           py37he1b5a44_0    conda-forge
psutil                    5.7.0                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.19                       py_2    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.6                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytorch                   1.0.1           cuda100py37he554f03_0    defaults
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0                   py37_0    conda-forge
scipy                     1.4.1            py37h0b6359f_0    defaults
send2trash                1.5.0                      py_0    conda-forge
sentry-sdk                0.14.1                   pypi_0    pypi
setuptools                45.2.0                   py37_0    conda-forge
shortuuid                 0.5.0                    pypi_0    pypi
six                       1.14.0                   py37_0    conda-forge
smmap2                    2.0.5                    pypi_0    pypi
soupsieve                 1.9.4                    py37_0    conda-forge
spacy                     2.1.8            py37hc9558a2_0    fastai
sqlite                    3.30.1               hcee41ef_0    conda-forge
srsly                     0.1.0            py37he1b5a44_0    fastai
subprocess32              3.5.4                    pypi_0    pypi
tensorboardx              1.6                        py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thinc                     7.0.8            py37hc9558a2_0    fastai
tk                        8.6.10               hed695b0_0    conda-forge
torchvision               0.2.1                    py37_0    defaults
tornado                   6.0.3            py37h516909a_4    conda-forge
tqdm                      4.43.0                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
typing                    3.6.4                    py37_0    defaults
urllib3                   1.25.7                   py37_0    conda-forge
wandb                     0.8.28                   pypi_0    pypi
wasabi                    0.2.2                      py_0    fastai
watchdog                  0.10.2                   pypi_0    pypi
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
youtube-dl                2020.2.16                py37_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
---------------------------------------------------------------------------------------------------------------
Ubuntu 18.04.3 and Anaconda.
Just "conda env create -f environment.yml" and tried "ImageColorizer.ipynb" in Jupyter Lab.
It is said "undefined symbol: nvrtcGetProgramLogSize"
I checked the version of pytorch 1.0.1.
Could you please help me with it? 
Thanks and greetings.

**Comment by jantic** [comment]
@yusenfei  This was closed- did you find a resolution...?

**Comment by yusenfei** [comment]
@jantic Yes! I updated the version of Nvidia driver. The model is fantastic! Cheers!
