### ISSUE TITLE
I try to run command conda env create -f environment.yml but it encounters several conflicts in the packages

### ISSUE THREAD

**Issue by quockerwodger** [jantic/DeOldify#199]
[Conflict reports deoldify.txt](https://github.com/jantic/DeOldify/files/4309958/Conflict.reports.deoldify.txt)
I have attached the conflicts it come up with, it seems I am not the only one with this problem. It could be that I have the wrong versions of programs installed (I couldn't find how to install FastAI 1.0.51, only the most recent version). Any help would be greatly appreciated

**Comment by jantic** [comment]
It looks like you're trying to install on Windows.  Windows is not supported for a number of reasons so I'll be closing this issue and directing you to go with a Linux install.
 
Reason- it's impractical for us to chase down all the issues that are associated with the lack of support in the key libraries themselves. Ubuntu 18.04 is the way to go- makes life way simpler.
