### ISSUE TITLE
COLAB result video not showing up

### ISSUE THREAD

**Issue by zabique** [jantic/DeOldify#200]
After successful colourization Video created here: video/result/video.mp4 not showing up most of the time. is it possible to add Google drive import/export like in DFL notebook?

**Comment by jantic** [comment]
It might be possible but we're not going to add anything in addition to what's already there.  If all else fails it should be in that path you mentioned there (video/result/video.mp4 ).  The Troubleshooting section details how to navigate to this folder if you don't see the video show up on the UI with a media player.
