### ISSUE TITLE
Training a custom model

### ISSUE THREAD

**Issue by ByronTsang** [jantic/DeOldify#203]
I am able to reproduce very nice result by following to the descriptions of README on my own machine. Is it possible to get the result based on localised data on the color of bus, taxi, ferry etc.
I attempted to start a training on imagenet dataset using the notebook template 'ColorizeTrainingArtistic.ipynb'. Placing some training images to default path. But I got "AttributeError: Can't get attribute 'create_training_images' on <module '__main__' (built-in)>". So, would you provide more hints on how to train custom data.

**Comment by jantic** [comment]
It sounds like you're not running the Jupyter notebook itself and are trying to do this in a custom way.... Is that accurate?  I would recommend sticking with the notebooks. I won't be supporting anything that diverges from what's in the GitHub repo.

**Comment by ByronTsang** [comment]
I ran the notebook to try training the model with imagenet images. Put 20k images under the path. The images were found after this `il = ImageList.from_folder(path_hr)`. But when I ran `data_gen = get_data(bs=bs, sz=sz, keep_pct=keep_pct)`, I got the exact same error as [#35](https://github.com/jantic/DeOldify/issues/35). I tried to create the folders manually with no luck.

**Comment by jantic** [comment]
I'm going to have to decline hunting this down.  I don't want to be mean, but you're doing custom work then asking me to debug it. That's not what I'm here for.

**Comment by Tom797** [comment]
> I ran the notebook to try training the model with imagenet images. Put 20k images under the path. The images were found after this `il = ImageList.from_folder(path_hr)`. But when I ran `data_gen = get_data(bs=bs, sz=sz, keep_pct=keep_pct)`, I got the exact same error as [#35](https://github.com/jantic/DeOldify/issues/35). I tried to create the folders manually with no luck.
I have same error right now. Have you figured out how to solve it?

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
