### ISSUE TITLE
Windows CUDA memory error fix

### ISSUE THREAD

**Issue by zwarmapapa** [jantic/DeOldify#206]
I ran into a CUDA memory error, and I was messing around with it for a while, and finally was able to fix it. 

`torch.cuda.empty_cache()` throws an error, which caused it to not work. I looked it up, and apparently it's not even needed, so I disabled that line and now it works well on windows (7). I thought maybe GPU memory would now keep increasing, but that's not the case, it stays at the same amount. 

To be clear, I now have:

```
    def _clean_mem(self):
        # torch.cuda.empty_cache()
        # gc.collect()
        return 1;
```

I hope that's helpful to anyone bumping into the same error/problem.

**Comment by jantic** [comment]
Thanks for posting this.  I'll close this issue and am not going to take further action on it- Windows is not supported and won't be in the foreseable future.  But those who want to try getting it to work on Windows anyway may certainly find this useful.
