### ISSUE TITLE
help me now!

### ISSUE THREAD

**Issue by daciansolgen** [jantic/DeOldify#209]
after I rebooted my pc i got this error when i tried to proced to next step in instalation

conda env create -f environment.yml
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ conda env create -f environment.yml
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jantic** [comment]
First question is- is this Linux?  If not- only Linux is supported.

If it is Linux, then it appears what you need to do is install Anaconda.  Instructions [here](https://docs.anaconda.com/anaconda/install/linux/)

**Comment by daciansolgen** [comment]
ok. i try to install linux on my system next week when i come home.
