### ISSUE TITLE
Rando spam, a result I am very proud of

### ISSUE THREAD

**Issue by kirkgutierrdd** [jantic/DeOldify#211]
![image](https://user-images.githubusercontent.com/61682281/79363797-0cad8b80-7f51-11ea-8355-073b37fa109f.png)
Sorry for the spam but here is a result I am proud of !
![image](https://user-images.githubusercontent.com/61682281/79363863-24850f80-7f51-11ea-9e3f-edf6e0a054e2.png)

**Comment by jantic** [comment]
Looks great!  Thanks for sharing.
