### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by scienceapps** [jantic/DeOldify#215]
Hello, 

I'm using the VideoColorizer.ipynb and I get this error : 

AttributeError: module 'ffmpeg' has no attribute 'input'

ffmpeg-python is installed. Win10 64 bits

Can you help me ?

**Comment by jantic** [comment]
Unfortunately Windows is not supported.  Only Linux. But luckily you can simply use the Colab here and not install anything locally:

https://colab.research.google.com/github/jantic/DeOldify/blob/master/VideoColorizerColab.ipynb
