### ISSUE TITLE
trap invalid opcode error

### ISSUE THREAD

**Issue by miltosc** [jantic/DeOldify#216]
Hello!

when i run "nvidia-docker run --ipc=host -p 5000:5000 -d deoldify_api" after building it i get in my logs the following error and it does not start. Using docker ps i get empty results.

"kernel: [ 2676.041889] traps: python3[12171] trap invalid opcode ip:7f26ae925400 sp:7fff95696a28 error:0 in libcaffe2.so[7f26ac877000+3155000]"

Thanks in advance for your help.

**Comment by jantic** [comment]
I haven't been able to reproduce this issue, and the error codes aren't helping to narrow down the issue unfortunately. Are there any more logs to share, for example?  And this is Linux?

**Comment by miltosc** [comment]
It was Linux. I managed to run it natively without docker. As long as I know probably caffe2 is not compiled for my CPU in docker

On April 25, 2020 6:16:40 AM GMT+03:00, Jason Antic <notifications@github.com> wrote:
>I haven't been able to reproduce this issue, and the error codes aren't
>helping to narrow down the issue unfortunately. Are there any more logs
>to share, for example?  And this is Linux?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jantic/DeOldify/issues/216#issuecomment-619311442

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
