### ISSUE TITLE
Working good

### ISSUE THREAD

**Issue by srinivasbheesetty** [jantic/DeOldify#220]
Hai I am Srinivas Hobbyist in old film colorization. Recently I  used your software in Google colab. Wonderful I like this. Please visit my youtube channel. All videos single frame work. Days, weeks, months done. I am not software person just passion this work. Recently one old video used deoldify. I request you give me one help . Mission learning my own colouring images to old film ( Just like " ebsynth ") . Total film to frames, some frames to own colour,  choose to target..... ( Sorry my bad English). ....my youtube channel colorization.... Please check this link or my     
Thank you 🙏

[https://youtube.com/user/technicalmindsrinu]

https://youtu.be/6y8zwCMzWCQ

**Comment by kirkgutierrdd** [comment]
We will never get to get to use the myheritage DeOldify...
The owner wanna sell the newer the works so much better...

**Comment by jantic** [comment]
Hi @srinivasbheesetty !  Great work on that channel.

So what you describe there is probably the direction we're going with video if we tackle video again (a big question currently). But that won't be for a while and it would be a paid product for sure (will require lots of work).  

The next best thing in the meantime is to basically achieve the same thing with some existing tools.  Garrett Gilchrist has a great workflow that he describes it in [this YouTube series.](https://www.youtube.com/playlist?list=PLj35L0AEP6qk467T8YDDiewGTcmsMg4vc).

**Comment by srinivasbheesetty** [comment]
![Thanks](https://user-images.githubusercontent.com/62322116/81954599-a9ce1380-9626-11ea-9388-50e3015a743e.PNG)
