### ISSUE TITLE
Unable to use other three pre-trained models

### ISSUE THREAD

**Issue by madhavasai** [jantic/DeOldify#222]
At present we are using the ColorizeVideo_gen.pth model. But after transferring all other models  into model directory.(ColorizeVideo_PretrainOnly_gen.pth, ColorizeVideo_PretrainOnly_crit.pth, ColorizeVideo_crit.pth) its using by default only  ColorizeVideo_gen.pth. I tried with only  ColorizeVideo_crit.pth in model directory. But its checking for ColorizeVideo_gen.pth model and its not allowing to use other models other than this (ColorizeVideo_gen.pth).

So my kind request is could you please help me to provide the process for configuration of other model for this provided coding.

I am facing one more issue is I observed after converting to colourization videos black/blue shades are there on the body parts (faces, legs, hands). Please could you provide any solution for this issue.

Thanks & Regards,
Sai

**Comment by 453trfge543** [comment]
Interested of knowing it too

**Comment by jantic** [comment]
@madhavasai  I'm unclear on what you're trying to accomplish here.  The models with the suffix "_crit" are strictly pretrained "critic" models used in training and they do not produce video output. Rather, they're used in training to "criticize" the images generated by the "generator" in training and improve it.  So you can't use them to generate video. 

ColorizeVideo_gen.pth is the only practically usable set of model weights for video.  ColorizeVideo_PretrainOnly_gen.pth are just the model weights snapshot just before GAN training was initiated.  Video can technically be produced by it but it'll look awful (very dull).

If you really want to use those weights, just search and replace the code "ColorizeVideo_gen" with "ColorizeVideo_PretrainOnly_gen", provided you have the source code running on a Linux box. If you're running on a Colab only you can simply swap out the Dropbox link download for the one provided in the readme for the PretrainOnly one.

But again, I don't recommend it. The results will simply be more disappointing.

> I am facing one more issue is I observed after converting to colourization videos black/blue shades are there on the body parts (faces, legs, hands). Please could you provide any solution for this issue.

As far as the issue you site there- the only potential solution available to you is to play around with the render_factor value and see what renders best.  There's functionality in the notebook and Colab to preview a specific frame that you specify for a range of render_factors- generally a single image is a good indicator of overall video performance.  

Failing that, basically you're at the mercy of the fact that this is an older model with limitations!
