### ISSUE TITLE
If only Myheritage-DeOldify aka the real DeOldify would have been released

### ISSUE THREAD

**Issue by 453trfge543** [jantic/DeOldify#223]
https://www.youtube.com/watch?v=SR-ES6zbSTY
Here is a video I enhanced via the 'real', 'true' DeOldify. 
if only you released InColor-DeOldify it would be amazing to the remastering community.

I took few keyframes put'd it into myheritage and I put'd it into DeepRemaster
which let you put few frames in it and like a chad it colorize the video by the keyframes in my case it was KeyFrames by 
the real DeOldify provided by myheritage

you dont have rights to the software ? I dont see the point of releasing the software as 'free' and 'open sourced'
while trying to make money of it which you probably not making any of it

If only it would be released

**Comment by jantic** [comment]
Hello kirkgutierrdd, 

We've been through this.

Thanks
Jason
