### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data\\bandw\\models\\VideoModel_gen_0.pth'

### ISSUE THREAD

**Issue by miltosc** [jantic/DeOldify#225]
Hello!

when running ColorizeTrainingVideo.ipynb i get the error FileNotFoundError: [Errno 2] No such file or directory: 'data/bandw/models/VideoModel_gen_0.pth'
it creates a temp file there but finally it deletes it and throws that error.
Same error in windows and in linux.
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-35-ae36aee0c2ad> in <module>
      1 #learn_gen = learn_gen.load(pre_gen_name, with_opt=False)
----> 2 learn_gen = learn_gen.load('VideoModel_gen_0','VideoModel_gen_0', with_opt=False)

site-packages\fastai\basic_train.py in load(self, file, device, strict, with_opt, purge, remove_module)
    263         elif isinstance(device, int): device = torch.device('cuda', device)
    264         source = self.path/self./f'{file}.pth' if is_pathlike(file) else file
--> 265         state = torch.load(source, map_location=device)
    266         if set(state.keys()) == {'model', 'opt'}:
    267             model_state = state['model']

site-packages\torch\serialization.py in load(f, map_location, pickle_module)
    364             (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)):
    365         new_fd = True
--> 366         f = open(f, 'rb')
    367     try:
    368         return _load(f, map_location, pickle_module)
	
FileNotFoundError: [Errno 2] No such file or directory: 'data\\bandw\\models\\VideoModel_gen_0.pth'

```

Trying to train using ILSVRC2017_CLS-LOC.tar.gz

Is that correct ?

Please help.
Thanks in advance

**Comment by jantic** [comment]
This notebook by default assumes that you had done training using ColorizeTrainingStable, and then renamed the resuling model to VideoModel_gen_0.pth.  If you're going directly to video training, you'll need to download the [pretrained stable model](https://www.dropbox.com/s/mdnuo1563bb8nh4/ColorizeStable_PretrainOnly_gen.pth?dl=0) and rename it and put it in the specified path.  That path, 'data\bandw\models\VideoModel_gen_0.pth,  is relative to the root DeOldify folder that contains the notebooks. And yes you'll want to extract  ILSVRC2017_CLS-LOC.tar.gz and use that to train (which I further elaborate on [here](https://github.com/jantic/DeOldify/issues/228)).  

Let me save you time- training simply won't work on Windows. I mean...it'll run, but super super slowly.  Windows is not supported.

**Comment by miltosc** [comment]
Honestly i did your first recommendation (download and rename) but i got error "StopIteration" at the next step. After i run the command you added (also re-downloading and renaming the file) it created bandw folder and all its contents, everything goes fine.

Thank you very much for your precious help!
