### ISSUE TITLE
Stripe artifacts

### ISSUE THREAD

**Issue by 972461099** [jantic/DeOldify#226]
thanks you wonderful work!
but when I test on my picture,the result has serious stripe， How can I deal with it? 
thank you
![Uploading i
![IMG20200511143517](https://user-images.githubusercontent.com/23586956/81531637-a4a66580-9395-11ea-97b3-7fa68227ac66.jpg)
mage.png…]()

**Comment by jantic** [comment]
Can you try uploading your image there again?  It's not showing up correctly.

**Comment by 972461099** [comment]
![捕获](https://user-images.githubusercontent.com/23586956/81544158-b3971300-93a9-11ea-8dec-17cd5632c04f.JPG)
![捕获2](https://user-images.githubusercontent.com/23586956/81544286-e8a36580-93a9-11ea-8d4c-01899c40bde8.JPG)

**Comment by jantic** [comment]
Thanks.  Yeah unfortunately for now I don't have a solution for you.  Even in my latest models I still run into this.  I'll keep this issue open to document it for now (will rename it to be more specific).  

The best workaround I can give you (and it's not much of one) is to render with higher render_factors.

**Comment by 972461099** [comment]
Thank you very much, looking forward to your latest results

**Comment by jantic** [comment]
We have a solution for this in our commercial models but it's not going to be released anytime soon in open source for a number of reasons. Competitive advantage being just one of them.
