### ISSUE TITLE
Windows GUI for Deoldify Video

### ISSUE THREAD

**Issue by thingol8768** [jantic/DeOldify#231]
A couple of months ago someone mentioned it....and a reply was made that it could be done for a donation.

**So what kind of donation would it take** to make Deoldify an app for use in Windows with a GUI that would handle both the video and still pictures, complete with Render Factor selection and MP4 render quality selection at output? 

Assuming you need a beefy computer with an NVIDIA card (cuda cores), it would be so much easier to work with this in Windows. Thanks!

**Comment by jantic** [comment]
So basically this is possibly in the cards, but it'd be a paid product and it'll take quite a while to get there at this point.  There's still a lot of research to be done. That is to say- when the time comes the "donation" will be simply to pay for the app!

I'm a big believer in taking time to do things right and seeing things through, but unfortunately for everybody else involved that means things go slooooow and seem to take forever. So hopefully you guys don't lose interest before then :P
