### ISSUE TITLE
How to download dataset (or part of it) for running Training workbooks

### ISSUE THREAD

**Issue by AshleyRudland** [jantic/DeOldify#232]
Hi @jantic! Probably a really dumb question, but I'm completely lost and hope you can help.

Trying to run the Stable training workbook in Colab. My main issue is I simply cannot a clear way to download the imagenet dataset.

In the workbook it expects the following:

```python
path = Path('data/imagenet/ILSVRC/Data/CLS-LOC')
```

Hope you can point me in the right direction. I just want to download the above.

Thanks in advance!
Ash.

**Comment by jantic** [comment]
The one I got was from [here at Kaggle](https://www.kaggle.com/c/imagenet-object-localization-challenge)

You have to "join" the competition but it doesn't obligate you do anything.

**Comment by cduguet** [comment]
It is not available in Kaggle anymore. Some people suggested the [original imagenet download site](http://image-net.org/download) but I'm trying it it works out with [imagenette](https://github.com/fastai/imagenette) first.

**Comment by jantic** [comment]
If hunting down Imagenet proves to be impossible you should be able to get excellent results using a few million images using [Open Images](https://storage.googleapis.com/openimages/web/index.html). It's one of the main datasets we use now for our closed source version. In fact I suspect if you use it in isolation to replace Imagenet in this case you may in fact get better results.

**Comment by cduguet** [comment]
Thank you!  Will try out.
