### ISSUE TITLE
creation of ColorizeVideo_gen.pth

### ISSUE THREAD

**Issue by miltosc** [jantic/DeOldify#234]
Hello,

i downloaded the https://www.dropbox.com/s/b3wka56iyv1fvdc/ColorizeStable_PretrainOnly_crit.pth?dl=0 renamed it to VideoModel_crit_0.pth at the right path and after finishing execution of ColorizeTrainingVideo.ipynb i got an extra file VideoModel_crit_1.pth. I renamed it to ColorizeVideo_gen.pth but cannot colorize video it throws runtime error, So how i produce a ColorizeVideo_gen.pth file Generator  weights? I get only Critic weights.

Thank you in advance for your help

**Comment by miltosc** [comment]
It seems like the final videomodel_gen_0.pth is the final ColorizeVideo_gen.pth . Am i right?

**Comment by jantic** [comment]
Final video generator model is [here](https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0)

The weights for the video generator model just as it was finished pretraining and just before doing the GAN training phase are[here](https://www.dropbox.com/s/avzixh1ujf86e8x/ColorizeVideo_PretrainOnly_gen.pth?dl=0)

You can't use the critic or crit models for video generation.  That model just "criticizes" the video generator during training.
