### ISSUE TITLE
How to use gpu 

### ISSUE THREAD

**Issue by yunnian** [jantic/DeOldify#237]
I didn't use docker to start the API,  I start api use ' python3 app.py ' directly on the machine,  but I found that I only used CPU ,the GPU not work 。 

How to use gpu when run  the ' python3 app.py'   on the machine not docker

**Comment by jantic** [comment]
Did you do the conda install and run app.py on that conda environment? And do you have a fairly recent NVidia GPU? The code will automatically revert to using the CPU if the prerequisites (like CUDA) aren't detected.

Also note that only Linux is supported.

**Comment by yunnian** [comment]
![image](https://user-images.githubusercontent.com/5779513/82753239-c3c1e000-9df6-11ea-9fed-c984e90874bd.png)
Yes, I don't understand why I didn't use GPU. Please help me

**Comment by yunnian** [comment]
but in  jupyter lab  GPU is work

![image](https://user-images.githubusercontent.com/5779513/82757459-32ad3200-9e13-11ea-87b8-4213737bfe7a.png)
![image](https://user-images.githubusercontent.com/5779513/82757482-4d7fa680-9e13-11ea-987f-3d6cc2beac3d.png)

why  python3 app.py service cannot use GPU?

**Comment by yunnian** [comment]
I I added the code to solve the problem  in app.py
![image](https://user-images.githubusercontent.com/5779513/82758031-a6047300-9e16-11ea-800e-6a96c0e8add3.png)

**Comment by mahaveergautamji** [comment]
http://localhost:8888/lab
ImportError                               Traceback (most recent call last)
Cell In[1], line 5
      3 from deoldify.device_id import DeviceId
      4 #choices:  CPU, GPU0...GPU7
----> 5 device.set(device=DeviceId.GPU0)

File [~/AutoDeOldifyLocal/DeOldify/deoldify/_device.py:26](http://127.0.0.1:8888/lab/tree/AutoDeOldifyLocal/DeOldify/AutoDeOldifyLocal/DeOldify/deoldify/_device.py#line=25), in _Device.set(self, device)
     24 else:
     25     os.environ['CUDA_VISIBLE_DEVICES']=str(device.value)
---> 26     import torch
     27     torch.backends.cudnn.benchmark=False
     29 self._current_device = device    

File [~/miniconda3/envs/deoldify/lib/python3.10/site-packages/torch/__init__.py:199](http://127.0.0.1:8888/lab/tree/AutoDeOldifyLocal/DeOldify/miniconda3/envs/deoldify/lib/python3.10/site-packages/torch/__init__.py#line=198)
    197     if USE_GLOBAL_DEPS:
    198         _load_global_deps()
--> 199     from torch._C import *  # noqa: F403
    201 # Appease the type checker; ordinarily this binding is inserted by the
    202 # torch._C module initialization code in C
    203 if TYPE_CHECKING:

ImportError: /home/veeru/miniconda3/envs/deoldify/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
