### ISSUE TITLE
Pic tool

### ISSUE THREAD

**Issue by nijinjose** [jantic/DeOldify#241]

**Comment by jantic** [comment]
@nijinjose Can you add a description? I really don't know what you mean here....

**Comment by lnmjy** [comment]
I'm sorry, I'm just in the learning stage, for my very interesting things, I have some uncertain operation, to bring you trouble please forgive me! ! !&nbsp;




------------------ 原始邮件 ------------------
发件人: &nbsp;"Jason Antic"<notifications@github.com&gt;;
发送时间: &nbsp;2020年5月27日(星期三)中午1:50
收件人: &nbsp;"jantic/DeOldify"<DeOldify@noreply.github.com&gt;;
抄送: &nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题: &nbsp;Re: [jantic/DeOldify] Pic tool (#241)





 
@nijinjose Can you add a description? I really don't know what you mean here....
