### ISSUE TITLE
How to train a model?

### ISSUE THREAD

**Issue by keto33** [jantic/DeOldify#242]
How can I train a model or continue training the available model?

**Comment by jantic** [comment]
If you have the prerequisite background in deep learning (fastai would be ideal), then what's in the [readme](https://github.com/jantic/DeOldify/blob/master/README.md) along with the Jupyter notebooks should suffice.  That being said, training NoGAN is particularly challenging even with a solid background (it's tricky to know when to stop, namely).

If you don't have that background I can't really help you and you won't get too far until something goes wrong. It's not so much of a "follow this recipe" sort of thing unfortunately.
