### ISSUE TITLE
make a windows version with graphical ui

### ISSUE THREAD

**Issue by daciansolgen3** [jantic/DeOldify#244]
please make a windows version with graphical ui so we that arent nasa rocket scientist or ritch like billgates or elon musk can enjoy too.

**Comment by jantic** [comment]
Yeah...no... That's not how to persuade me to do things.  

Here, read a book instead:  [How to Win Friends and Influence People](https://www.amazon.com/How-Win-Friends-Influence-People/dp/0671027034)

**Comment by daciansolgen3** [comment]
Sorry for my angry comment
