### ISSUE TITLE
22s to process 1 photo. Is this hitting GPU or CPU? 

### ISSUE THREAD

**Issue by andycloke** [jantic/DeOldify#246]
Firstly, this repo is awesome!

When I run the docker API and color 1 photo, it's taking 22s. I'm guessing that means it's hitting the CPU not the GPU (based on this answer: https://github.com/jantic/DeOldify/issues/76#issuecomment-471803927). 

Does this `nvidia-smi` output confirm that that is the case?
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:00:05.0 Off |                  N/A |
|  0%   16C    P8     7W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:00:06.0 Off |                  N/A |
|  0%   20C    P8     8W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

And do you have any suggestions for what might be wrong? I've Googled a fair bit around docker/ Nvidia and tried quite a few things but can't figure it out.

System:Ubuntu 18.04
GPU : 2 x 1080ti
CPU: 8GB
GPU Driver Version:396.54
NVIDIA-SMI: 430.50       
Driver Version: 430.50       
CUDA Version: 10.1

Thanks

**Comment by Tortoise17** [comment]
could be wrong tensorflow version. !! see your TF version?

**Comment by Tortoise17** [comment]
First see TF gpu is available if YES, which version

**Comment by andycloke** [comment]
Thanks for the quick response! 

I didn't install TF as I assume docker handled it but guessing that's wrong. Will install it now.

**Comment by Tortoise17** [comment]
python3 -c 'import tensorflow as tf; print(tf.__version__)'

this commands shows your version. Because above 1.15 TF is not compatible with cuda 10.1

**Comment by Tortoise17** [comment]
Could be either you raise your cuda version to 10.2 could help.

**Comment by andycloke** [comment]
Thanks, installing TF now. I'll try cuda too if this does not fix it.

Is this correct? `pip3 install tensorflow-gpu==1.14`  ?

**Comment by Tortoise17** [comment]
1.15 should work
pip3 install tensorflow-gpu==1.14
pip3 install tensorflow-gpu==1.15

Try 1.15 first. 
yes, if the versions or any other thing which is mismatching, than, maybe cuda 10.2 or 10.0 is the solution for definitely. Because this is the cuda mismatch.

**Comment by Tortoise17** [comment]
But, here could be that pytorch is mismatching. sorry. I am jumping back and forth in different tools. 

see which pytorch version you have. // and which cuda is compatible with?? or if you tell me torch version, I can tell you. 

You can check this with 
pip list 
or 
pip3 list

**Comment by andycloke** [comment]
I got `No matching distribution found for tensorflow-gpu==1.15`, so tried doing 1.14 instead.

Do I actually need to install `pytorch` myself, won't docker handle that? https://github.com/jantic/DeOldify/blob/master/Dockerfile-api#L17

**Comment by Tortoise17** [comment]
I think it assumes you already have pytorch and updates it only. But see 
https://pytorch.org/

maybe it is already expecting your cuda 10.2?

update cuda and run. It should work.

**Comment by andycloke** [comment]
Updated to cuda 10.2 and still no luck. Will try pytorch now. Thanks

**Comment by andycloke** [comment]
Still not working with pytorch 1.0.1 and condo 10.2. Must be missing something else.

**Comment by Tortoise17** [comment]
nvcc --version

can you confirm cuda version? 10.2 ? if not. than mismatch. 
mismatch and dropdown to 9.2 and see if that is really picking your environments.

**Comment by andycloke** [comment]
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**Comment by Tortoise17** [comment]
https://discuss.pytorch.org/t/pytorch-for-cuda-10-2/65524

**Comment by jantic** [comment]
Thanks @Tortoise17 for all the help.

@andycloke did you install nvidia-docke per the readmer?  https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)#installing-version-20

**Comment by andycloke** [comment]
@jantic yes I did. I'm using the colab now, and @kirushyk is helping me set up a remote server. We can close this ticket, thanks
