### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by HpZhao607** [jantic/DeOldify#250]
Hello, I'm sorry to bother you, I want to ask about when run "ImageColorizerStableTests. Ipynb" file there will always be such errors occur, and each time the error message "No to the file or directory:" the inside of the content is different, because I lack what document or other reasons? I hope you can reply me. Thank you.
![2020-06-29 16-28-07屏幕截图](https://user-images.githubusercontent.com/63080810/85991404-f4b0b880-ba25-11ea-8b5f-b376385474a9.png)

**Comment by HpZhao607** [comment]
Such as:
![2020-06-29 16-33-19屏幕截图](https://user-images.githubusercontent.com/63080810/85991788-828ca380-ba26-11ea-941f-a6c9a8872414.png)

**Comment by jantic** [comment]
@HpZhao607  That's looking like a file permissions issue.  Easiest thing to do would be to do this:

Open a terminal in PycharmProjects and add read/write permissions.

chmod -R 666 DeOldify

This will recursively add read/write permissions and you should be good to go. I'm a bit lazy so I'll just give you something pretty permissive here but if that worries you can adjust the "666" part accordingly.

**Comment by jantic** [comment]
@HpZhao607 Sorry my first response was incomplete.  

You need to add the models directory per the readme.  There's instructions there to download the models from dropbox and add to this folder.

THEN if you're still running into issues do this:

Open a terminal in PycharmProjects and add read/write permissions.

chmod -R 666 DeOldify

This will recursively add read/write permissions and you should be good to go. I'm a bit lazy so I'll just give you something pretty permissive here but if that worries you can adjust the "666" part accordingly.
