### ISSUE TITLE
How model handles different rendering factors. 

### ISSUE THREAD

**Issue by AlbertOh90** [jantic/DeOldify#251]
Thanks for sharing the source codes of this wonderful application. 

I am not sure this is the right place to ask. But I am curious about how the model handling different rendering factors. In the Colab demo, I can choose different rendering factors for processing an original image.
 I can see from the source code that the input _rendering factor_ is multiplied with the _render_base_ (default 16). The resulting number is used to resize the input image to a square image. The resized image is then passed to the function _pred_patch_ of a trained model, which I believe is an object of _DynamicUnetDeep_ class. However, when I look at the code of _DynamicUnetDeep_, I cannot find any snippets of handling different input image size. The input image size is set to (224, 224) by default. 

So I am just wondering which part of the model handles different input image sizes due to different rendering factors. Is the model trained by different rendering factors?

Any hints would be appreciated. Thanks. 

Best regards,
Hanwei

**Comment by hiterjoshua** [comment]
In my opinion, the image was downsampled 16x during the encoder part, and then upsampled to the input size, so the render_base was set to 16. and any resized image which is a multiple of 16 would be OK for this network.

**Comment by AlbertOh90** [comment]
Thank you for your reply! I believe you're correct. The input image is indeed first downsampled by a factor of 16 using resnet34 . Then it seems that the activations of the modules responsible for the downsampling are stored a hook. Then the code use F.interpolates to upsample the activations according to the shapes of the stored activations reversely.
