### ISSUE TITLE
How to colorize personal videos

### ISSUE THREAD

**Issue by srinivas68** [jantic/DeOldify#252]
Hi. How to colorize personal videos from my PC . I used Ubuntu  . Working great from youtube videos. But I need personal old videos not identified my Ubuntu or Google colab.

**Comment by anh-nn01** [comment]
One simple solution is to upload your video on Youtube and then take the url. It should be quick if your video is not several hours long.

**Comment by srinivas68** [comment]
After editing Favourite movie bits not accepted youtube . So my favourite movie bits colorize my own Ubuntu system. Without youtube or any other.

**Comment by jantic** [comment]
Yeah our stance is: Quick and easy:  Do Colab (urls only).  More involved but industrial strength:  Use Ubuntu install, where you can do longer videos and local videos, and not run into trouble with YouTube not accepting something, etc.
