### ISSUE TITLE
Unable to run "predict" method from Learner to log prediction samples

### ISSUE THREAD

**Issue by leeqiaogithub** [jantic/DeOldify#256]
when training GAN, there is a warning:Unable to run "predict" method from Learner to log prediction samples.therefore I can not check the samples every epoch by browsing W&B web. 
How can I correct this?

**Comment by leeqiaogithub** [comment]
It is not bound to arise

**Comment by jantic** [comment]
@leeqiaogithub I'll just be brutally honest- I've had a lot of issues with W&B myself with reliability so I've avoided it personally.  It doesn't actually give me anything that Tensorboard does already other than cloud storage and a somewhat nice web interface.

So I'll keep this open but it'll be pretty low priority.

**Comment by leeqiaogithub** [comment]
> @leeqiaogithub I'll just be brutally honest- I've had a lot of issues with W&B myself with reliability so I've avoided it personally. It doesn't actually give me anything that Tensorboard does already other than cloud storage and a somewhat nice web interface.
> 
> So I'll keep this open but it'll be pretty low priority.

ok，thank you very much.
