### ISSUE TITLE
dummy is not a valid directory.

### ISSUE THREAD

**Issue by kaoruse** [jantic/DeOldify#258]
Hi everyone. I've been trying to execute DeOldify using Jupyter Notebook and I'm getting this error.
Hence name 'colorizer' is not defined and I cannot proceed with the process.
Can someone provide the solution?

Thanks,

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-81c07a854ecc> in <module>
----> 1 colorizer = get_video_colorizer()

C:\DeOldify\deoldify\visualize.py in get_video_colorizer(render_factor)
    355 
    356 def get_video_colorizer(render_factor: int = 21) -> VideoColorizer:
--> 357     return get_stable_video_colorizer(render_factor=render_factor)
    358 
    359 

C:\DeOldify\deoldify\visualize.py in get_stable_video_colorizer(root_folder, weights_name, results_dir, render_factor)
    376     render_factor: int = 21
    377 ) -> VideoColorizer:
--> 378     learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
    379     filtr = MasterFilter([ColorizerFilter(learn=learn)], render_factor=render_factor)
    380     vis = ModelImageVisualizer(filtr, results_dir=results_dir)

C:\DeOldify\deoldify\generators.py in gen_inference_wide(root_folder, weights_name, nf_factor, arch)
      8 def gen_inference_wide(
      9     root_folder: Path, weights_name: str, nf_factor: int = 2, arch=models.resnet101) -> Learner:
---> 10     data = get_dummy_databunch()
     11     learn = gen_learner_wide(
     12         data=data, gen_loss=F.l1_loss, nf_factor=nf_factor, arch=arch

C:\DeOldify\deoldify\dataset.py in get_dummy_databunch()
     45     path = Path('./dummy/')
     46     return get_colorize_data(
---> 47         sz=1, bs=1, crappy_path=path, good_path=path, keep_pct=0.001
     48     )

C:\DeOldify\deoldify\dataset.py in get_colorize_data(sz, bs, crappy_path, good_path, random_seed, keep_pct, num_workers, stats, xtra_tfms)
     20 
     21     src = (
---> 22         ImageImageList.from_folder(crappy_path, convert_mode='RGB')
     23         .use_partial_data(sample_pct=keep_pct, seed=random_seed)
     24         .split_by_rand_pct(0.1, seed=random_seed)

~\AppData\Roaming\Python\Python37\site-packages\fastai\vision\data.py in from_folder(cls, path, extensions, **kwargs)
    277         "Get the list of files in `path` that have an image suffix. `recurse` determines if we search subfolders."
    278         extensions = ifnone(extensions, image_extensions)
--> 279         return super().from_folder(path=path, extensions=extensions, **kwargs)
    280 
    281     @classmethod

~\AppData\Roaming\Python\Python37\site-packages\fastai\data_block.py in from_folder(cls, path, extensions, recurse, exclude, include, processor, presort, **kwargs)
    127         `recurse` determines if we search subfolders."""
    128         path = Path(path)
--> 129         assert path.is_dir() and path.exists(), f"{path} is not a valid directory."
    130         return cls(get_files(path, extensions, recurse=recurse, exclude=exclude, include=include, presort=presort), 
    131                    path=path, processor=processor, **kwargs)

AssertionError: dummy is not a valid directory.

**Comment by jantic** [comment]
@kaoruse Yep...the answer is that this works fine on Linux and Windows isn't supported. You may be able to add a folder called "dummy" to the main folder and get it to work but you're bound to run into other issues.
