### ISSUE TITLE
Conda environment setup not recognising or downloading Python

### ISSUE THREAD

**Issue by gitLRD** [jantic/DeOldify#261]
Hey,

I tried to do a first time setup today and it looks like Python isn't being picked up by Conda; 

```
failed
An error occurred while installing package 'conda-forge::attrs-19.3.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/home/lewisdesforges/.conda/envs/deoldify/bin/python3.7'")
Attempting to roll back.
```
I can see the following Python related packages in my .conda directory (this is a blank box so anything in there will be related to De Oldify):

```
python-3.7.8-h6f2ec95_1_cpython.tar.bz2
python_abi-3.7-1_cp37m.tar.bz2
python-dateutil-2.8.1-py_0.tar.bz2
```
But when I see it go through and link packages I can't see Python being linked.

I'm running this on a fresh Fedora 29 install (need to update my ISO).

**Comment by jantic** [comment]
That's a bit strange.  I'm not reproducing it myself.  Based on what I'm seeing elsewhere researching this issue, my best guess as to now is that you may just need to update conda itself and retry. Update conda by running this command: 

`conda update conda`

If that works, great- please let me know. If not, please provide complete conda environment install output for this.  Thanks!

**Comment by gitLRD** [comment]
Thanks Jason. Conda was a brand new install so I would have thought it was the most up to date, but this box was running Fedora 29 when I tried it which is pretty old by now, so I just upgraded it to 32 so let me have another go and see what happens when everything is a bit newer. 

Will get back to you in a bit.

**Comment by gitLRD** [comment]
Hey Jason,

Looks like a newer version of Fedora has solved this for me; I deleted all the existing DeOldify environments, recreated them and it worked flawlessly. Thanks for the help 👍

**Comment by jantic** [comment]
@gitLRD That's great to hear, and really helpful to get this sort of feedback documented in the issues log.  Thank you!
