### ISSUE TITLE
Is it possible to colorize raw rgb data/image

### ISSUE THREAD

**Issue by devalexqt** [jantic/DeOldify#269]
Any one know how to read raw rgb24 data from post request and then colorize it? In other words colorize image not from disk but from memory buffer that have rgb  data?

**Comment by jantic** [comment]
There's sample code in visualize.py that shows converting raw bytes into PIL, similar to what you're describing:

```
def _get_image_from_url(self, url: str) -> Image:
        response = requests.get(url, timeout=30)
        img = PIL.Image.open(BytesIO(response.content)).convert('RGB')
        return img
```
From there you colorize it.  Granted, the code that people keep trying to use is the visualize.py stuff that is oriented around testing and jupyter notebooks, so they read and write to file paths which is not what you want here.  But within there you'll see this:

   ```
 def get_transformed_image(
        self, path: Path, render_factor: int = None, post_process: bool = True,
        watermarked: bool = True,
    ) -> Image:
        self._clean_mem()
        orig_image = self._open_pil_image(path)
        filtered_image = self.filter.filter(
            orig_image, orig_image, render_factor=render_factor,post_process=post_process
        )

        if watermarked:
            return get_watermarked(filtered_image)

        return filtered_image
```

The relevant call for you is just the self.filter.filter part:

`        filtered_image = self.filter.filter(
            orig_image, orig_image, render_factor=render_factor,post_process=post_process
        )`

That way you can directly pass an image in and get an image out.

Hope that helps.
