### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by Enom2** [jantic/DeOldify#270]
Hello!

Ubuntu 18, VideoColorizerColab.ipynb
At the 10th stage, it gives an error: "AttributeError: module 'ffmpeg' has no attribute 'input'"

Tried reinstalling ffmpeg-python, it didn't help.

pip uninstall ffmpeg
pip uninstall ffmpeg-python
pip install ffmpeg-python

Full text:

source_url = 'https://www.youtube.com/watch?v=0taZYgPKalk' #@param {type:"string"}
render_factor = 21  #@param {type: "slider", min: 5, max: 40}
watermarked = True #@param {type:"boolean"}

if source_url is not None and source_url !='':
    video_path = colorizer.colorize_from_url(source_url, 'video.mp4', render_factor, watermarked=watermarked)
    show_video_in_notebook(video_path)
else:
    print('Provide a video url and try again.')

[youtube] 0taZYgPKalk: Downloading webpage
[youtube] 0taZYgPKalk: Downloading MPD manifest
[dashsegments] Total fragments: 2
[download] Destination: video/source/video.f135.mp4
[download] 100% of 125.77KiB in 00:00.13MiB/s ETA 00:005
[dashsegments] Total fragments: 2
[download] Destination: video/source/video.mp4.f140
[download] 100% of 85.80KiB in 00:00.07MiB/s ETA 00:0030
[ffmpeg] Merging formats into "video/source/video.mp4"
Deleting original file video/source/video.f135.mp4 (pass -k to keep)
Deleting original file video/source/video.mp4.f140 (pass -k to keep)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-9b51d5715abe> in <module>
      4 
      5 if source_url is not None and source_url !='':
----> 6     video_path = colorizer.colorize_from_url(source_url, 'video.mp4', render_factor, watermarked=watermarked)
      7     show_video_in_notebook(video_path)
      8 else:

~/Документы/AnyDesk/DeOldify/deoldify/visualize.py in colorize_from_url(self, source_url, file_name, render_factor, post_process, watermarked)
    331         self._download_video_from_url(source_url, source_path)
    332         return self._colorize_from_path(
--> 333             source_path, render_factor=render_factor, post_process=post_process,watermarked=watermarked
    334         )
    335 

~/Документы/AnyDesk/DeOldify/deoldify/visualize.py in _colorize_from_path(self, source_path, render_factor, watermarked, post_process)
    349                 'Video at path specfied, ' + str(source_path) + ' could not be found.'
    350             )
--> 351         self._extract_raw_frames(source_path)
    352         self._colorize_raw_frames(
    353             source_path, render_factor=render_factor,post_process=post_process,watermarked=watermarked

~/Документы/AnyDesk/DeOldify/deoldify/visualize.py in _extract_raw_frames(self, source_path)
    247         bwframes_folder.mkdir(parents=True, exist_ok=True)
    248         self._purge_images(bwframes_folder)
--> 249         ffmpeg.input(str(source_path)).output(
    250             str(bwframe_path_template), format='image2', vcodec='mjpeg', qscale=0
    251         ).run(capture_stdout=True)

AttributeError: module 'ffmpeg' has no attribute 'input'

**Comment by jantic** [comment]
Seems like there's a fairly easy answer here:  If you're running DeOldify locally use VideoColorizer.ipynb instead.  This Colab notebook you're using is strictly meant to be ran [here](https://colab.research.google.com/github/jantic/DeOldify/blob/master/VideoColorizerColab.ipynb):
