### ISSUE TITLE
Cant the model directory be created and models downloaded in dockerfile-api instead of app.py ?

### ISSUE THREAD

**Issue by mewbot97** [jantic/DeOldify#271]

**Comment by jantic** [comment]
That makes sense but this would be something for @jqueguiner to weigh in on (original author and primary user). Thoughts @jqueguiner ?

**Comment by jqueguiner** [comment]
can you check if https://github.com/jantic/DeOldify/pull/288 is the expected behavior ?

**Comment by jqueguiner** [comment]
@mewbot97 did you had time to check of behaviour presented fits your need ?

**Comment by mewbot97** [comment]
Yes it did run.

**Comment by jqueguiner** [comment]
Awesome ! Thanks for helping us improving the experience with your feedback !

**Comment by jqueguiner** [comment]
I’ll add related doc today in readme

**Comment by jqueguiner** [comment]
can we close this issue ?

**Comment by jantic** [comment]
@jqueguiner - Yes, closing now.  Thanks!
