### ISSUE TITLE
Training to improve certain object coloring

### ISSUE THREAD

**Issue by jbreu** [jantic/DeOldify#273]
Hi,

first, thank you so much for this incredible project! I colorized my first two historic pictures and am stunned by the results.

However, I want to go one step further. My challenge is that I want to colorize historic student photographs in which people wear red caps. However, the current network makes them blue. So I wonder what it would take to get to decent red-ish results.

- Would you estimate that if I add a few hundred, up to 1000 pictures, showing guys with red cap (and their grayscale versions) to the imaginet training set this would make a difference?
- Assuming I would borrow a decent graphics card with > 11 GB memory, how long does one training run actually take? I tried to look everywhere in ReadMe and relevant issues but couldn’t find that information (or missed it).

And expert guesstimate would be sufficient.

Thanks in advance!

**Comment by jantic** [comment]
Training from beginning to end will take 3-5 days. 

Your best bet in getting generally better results is to train on a bunch of images from a more diverse training set such as open images.  BUT the gains from this will be marginal relative to what you're trying to achieve here, and ultimately you're just not going to get the level of control you're hoping for here, even if you were to add very specific training examples. I call it a very long tail problem: The reality is that it's quite literally an impossible task to get perfection in this sort of task, especially when it comes to things like clothing.

Really for people who want this level of control the path I foresee that I want to explore is blending manual interventions with automatic colorization.  Say for example, you'd have a user place a dot of color on the hat to indicate that it should be red, and the model runs with that hint accordingly.  That's what I think should be done but I just haven't made it yet.

**Comment by jbreu** [comment]
Thank you very much for the feedback! So it sounds like I have to wait then and hope 😉
