### ISSUE TITLE
jupyter-client>=6.1.5

### ISSUE THREAD

**Issue by smidgett** [jantic/DeOldify#274]
When running ImageColorizerColab.ipynb I get the following issue:

ERROR: nbclient 0.5.0 has requirement jupyter-client>=6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.

I'm just a user and am trying to troubleshoot the error.

Thanks

**Comment by jantic** [comment]
So I'll try to figure out what could have gone wrong here.  The most likely scenario seems to be that you're trying to run it on your own computer. The Colab is strictly meant to be ran online, here: 
 [link](https://colab.research.google.com/github/jantic/DeOldify/blob/master/ImageColorizerColab.ipynb)

And make sure to run each cell in order.

Does that help?

**Comment by smidgett** [comment]
Yes, Jason. Thanks for your help. I reloaded the page and started
from scratch and now it is working fine.

**Comment by jantic** [comment]
Ok great!
