### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input' 

### ISSUE THREAD

**Issue by steve12345585** [jantic/DeOldify#275]
I'm using the VideoColorizer.ipynb and I get this error :

AttributeError: module 'ffmpeg' has no attribute 'input'

ffmpeg-python is installed. UBUNTU 20 64 Bit.

`Colorize!!

#NOTE:  Max is 44 with 11GB video cards.  21 is a good default

render_factor=21

#NOTE:  Make source_url None to just read from file at ./video/source/[file_name] directly without modification

source_url='Private FTP LOCATION/Mars.mp4'

file_name = 'Mars.mp4'

file_name_ext = file_name + '.mp4'

result_path = None

​

if source_url is not None:

    result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)

else:

    result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)

​

show_video_in_notebook(result_path)

[generic] Mars: Requesting header
[download] Destination: video/source/Mars.mp4.mp4
[download] 100% of 4.93MiB in 00:0305MiB/s ETA 00:005

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-ddef8f118dec> in <module>
      8 
      9 if source_url is not None:
---> 10     result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)
     11 else:
     12     result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)

~/Downloads/DeOldify-master/deoldify/visualize.py in colorize_from_url(self, source_url, file_name, render_factor, post_process, watermarked)
    331         self._download_video_from_url(source_url, source_path)
    332         return self._colorize_from_path(
--> 333             source_path, render_factor=render_factor, post_process=post_process,watermarked=watermarked
    334         )
    335 

~/Downloads/DeOldify-master/deoldify/visualize.py in _colorize_from_path(self, source_path, render_factor, watermarked, post_process)
    349                 'Video at path specfied, ' + str(source_path) + ' could not be found.'
    350             )
--> 351         self._extract_raw_frames(source_path)
    352         self._colorize_raw_frames(
    353             source_path, render_factor=render_factor,post_process=post_process,watermarked=watermarked

~/Downloads/DeOldify-master/deoldify/visualize.py in _extract_raw_frames(self, source_path)
    247         bwframes_folder.mkdir(parents=True, exist_ok=True)
    248         self._purge_images(bwframes_folder)
--> 249         ffmpeg.input(str(source_path)).output(
    250             str(bwframe_path_template), format='image2', vcodec='mjpeg', qscale=0
    251         ).run(capture_stdout=True)

AttributeError: module 'ffmpeg' has no attribute 'input'

'

**Comment by jantic** [comment]
Most likely cells weren't run in order or were skipped- that's how this issue normally happens.  I just tried the Colab and it worked fine for me on this video:  http://i.imgur.com/zaYFEwq.mp4

Try that yourself and see if you can get that to work.
