### ISSUE TITLE
ERROR 404: Not Found. Aka "I'm a computer. Stop All the Downloadin!"

### ISSUE THREAD

**Issue by kugyo5** [jantic/DeOldify#277]
When runningVideoColorizerColab.ipynb I get the following issue:

!mkdir 'models'
!wget https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0 -O ./models/ColorizeVideo_gen.pth
--2020-10-31 21:55:00--  https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.6.1, 2620:1 00:601c:1::a27d:601
Connecting to www.dropbox.com (www.dropbox.com)|162.125.6.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/336vn9y4qwyg9yz/ColorizeVideo_gen.pth [following]
--2020-10-31 21:55:00--  https://www.dropbox.com/s/raw/336vn9y4qwyg9yz/ColorizeVideo_gen.pth
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-10-31 21:55:00 ERROR 404: Not Found.

I'm just a user and am trying to troubleshoot the error.
However, I cannot find what I should do.

Thanks

**Comment by jantic** [comment]
@kugyo5  Yeah I got a notification from Dropbox that they've shutdown the links temporarily because of high traffic. I'm waiting to hear back from their customer service on this.

**Comment by kugyo5** [comment]
@jantic Hi, thank you for your reply. I see. I'll wait for a while.

**Comment by CaiqueCoelho** [comment]
Hi @jantic I had a similar problem with the dropbox these times and the only solution I found was to move to the google drive on a public link using the gdown library to download the files. I hope you can find a solution, I look forward to trying your project, anything I can help just let me know

**Comment by kugyo5** [comment]
@CaiqueCoelho, @jantic Thank you! I'll keep waiting.

**Comment by kugyo5** [comment]
I'd like to download ColorizeVideo_gen.pth. However, I cannot find it anywhere. 
Where can I download it?

**Comment by jantic** [comment]
@kugyo5  DeepAI kindly provided these links (you can run these ca

[Image (artistic)](https://deepai-opensource-codebases-models.s3-us-west-2.amazonaws.com/deoldify/ColorizeArtistic_gen.pth)

[Video](https://deepai-opensource-codebases-models.s3-us-west-2.amazonaws.com/deoldify/ColorizeVideo_gen.pth)

**Comment by kugyo5** [comment]
@jantic Oh! Thank you very much!

**Comment by kugyo5** [comment]
@CaiqueCoelho, @jantic Everything works without any problems now. Thank you for your kindness!

**Comment by jantic** [comment]
This is working now, because Dropbox's 24 hour time limit on the suspension has lapsed.  I haven't heard from them so who knows if they'll just do it again.  But in the meantime, party on.

**Comment by jantic** [comment]
This just happened again.  I'm using the aws links in the Colabs now (already committed) and I'll address the readme links soon.

**Comment by jantic** [comment]
Readme links are now fixed.

**Comment by mdtanrikulu** [comment]
Hello there, I have this issue again.

```
--2020-11-30 19:20:40--  https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.66.1, 2620:100:6022:1::a27d:4201
Connecting to www.dropbox.com (www.dropbox.com)|162.125.66.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth [following]
--2020-11-30 19:20:40--  https://www.dropbox.com/s/raw/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2020-11-30 19:20:41 ERROR 404: Not Found.
```

**Comment by jantic** [comment]
@mdtanrikulu  Look above in the comment thread.  Replace the links in the code with those (comment starts with" DeepAI kindly provided these links").

I'm assuming you're having this trouble with the docker image.  I'm about to merge a pull request that resolves these issues.
