### ISSUE TITLE
is it possible to create a gui and pack everything in a program?

### ISSUE THREAD

**Issue by starinspace** [jantic/DeOldify#278]
Is it possible to pack all files and necessary things needed to get it to work and create a gui (a program, .exe) for Windows do make it work offline and easy install?

**Comment by jantic** [comment]
This would be way beyond the scope of what we're willing to do for this project.  You're basically talking about creating a product! 

Your best bet for images is to go here if you want to use a good free version:  https://deepai.org/machine-learning-model/colorizer

Or the best and latest version:  https://www.myheritage.com/incolor
