### ISSUE TITLE
ColorizeVideo_gen.pth This item was deleted. 404

### ISSUE THREAD

**Issue by isty1974** [jantic/DeOldify#280]
https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0

**Comment by jantic** [comment]
Yes, this was intentional. With the current repo you shouldn't need that anyway.  Can you let me know what your use case is here?

**Comment by jantic** [comment]
No response...gonna close.

**Comment by NathanRichHGDW** [comment]
You may want to update this then:
https://colab.research.google.com/github/ojjsaw/video-processing/blob/master/Custom_DeOldify_VideoColorizer_Colab.ipynb
It's still trying to use this URL.

**Comment by jantic** [comment]
@NathanRichHGDW I'm not sure how you got a hold of that specific url but that's not the official Colab that we provide.  That one is at [this link](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)

What you have there is some else's fork of older code, coming from [here](https://github.com/ojjsaw/video-processing) .
