### ISSUE TITLE
Artistic colorizer error

### ISSUE THREAD

**Issue by gionniak** [jantic/DeOldify#285]
Hello, I am trying to run the commands as always and today it seems impossible.
In the stage of PIP install:
**ERROR: nbclient 0.5.1 has requirement jupyter-client>=6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.**
and at the end:
**WARNING: The following packages were previously imported in this runtime:
  [typing]
You must restart the runtime in order to use newly installed versions.**
Which I do restart but it stays the same.
and then at the stage of colorizer = get_image_colorizer(artistic=True):
Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /root/.cache/torch/hub/checkpoints/resnet34-333f7ec4.pth
100%
83.3M/83.3M [00:14<00:00, 5.89MB/s]

---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-8-d41e8163fe4e> in <module>()
----> 1 colorizer = get_image_colorizer(artistic=True)

5 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    762             "functionality.")
    763 
--> 764     magic_number = pickle_module.load(f, **pickle_load_args)
    765     if magic_number != MAGIC_NUMBER:
    766         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, 'm'.

**Comment by jantic** [comment]
This should be good to go now.  The model links were moved to a new location and I just now merged the code for that to work again.  Shout out to DeepAI for hosting them!

**Comment by gionniak** [comment]
Thank you very very much!

Στις Παρ, 13 Νοε 2020 στις 8:58 μ.μ., ο/η Jason Antic <
notifications@github.com> έγραψε:
