### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by jtn7** [jantic/DeOldify#289]
## My Problem
I'm getting this error when running `VideoColorizer.ipynb` locally. I ran everything in order just fine but this last step didn't seem to take. 

## Stacktrace
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-dd932c35ceb2> in <module>
     12     result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)
     13 else:
---> 14     result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)
     15 
     16 show_video_in_notebook(result_path)

~/DeOldify/deoldify/visualize.py in colorize_from_file_name(self, file_name, render_factor, watermarked, post_process)
    339     ) -> Path:
    340         source_path = self.source_folder / file_name
--> 341         return self._colorize_from_path(
    342             source_path, render_factor=render_factor,  post_process=post_process,watermarked=watermarked
    343         )

~/DeOldify/deoldify/visualize.py in _colorize_from_path(self, source_path, render_factor, watermarked, post_process)
    349             raise Exception(
    350                 'Video at path specfied, ' + str(source_path) + ' could not be found.'
--> 351             )
    352         self._extract_raw_frames(source_path)
    353         self._colorize_raw_frames(

~/DeOldify/deoldify/visualize.py in _extract_raw_frames(self, source_path)
    247         bwframe_path_template = str(bwframes_folder / '%5d.jpg')
    248         bwframes_folder.mkdir(parents=True, exist_ok=True)
--> 249         self._purge_images(bwframes_folder)
    250         ffmpeg-python.input(str(source_path)).output(
    251             str(bwframe_path_template), format='image2', vcodec='mjpeg', qscale=0

AttributeError: module 'ffmpeg' has no attribute 'input'
```

## What I did to fix it

I looked at #270 and saw that an attempted solution was to uninstall `ffmpeg` and `ffmpeg-python`, then reinstall `ffmpeg-python`.

This solved my issue. So I'm guessing that conda installed the dependencies wrong or python was importing the incorrect ffmpeg.

**Comment by jantic** [comment]
I just did a fresh conda install of DeOldify and couldn't reproduce what you experienced here.  This to me suggests that there's something that was done incorrectly on your end. Perhaps you forgot to do this before running Jupyter:

`conda activate deoldify`

Anyway, unless it's reproducible I'm not going to try to hunt down this issue any further. Thanks!

**Comment by 1997wzk** [comment]
@jtn7, hello，excuse me, I encountered the same problem as you, but reinstalling ffmpeg-python did not solve the problem. May I ask where ffmpeg-python should be installed, or can you tell me the details of the solution?

**Comment by jtn7** [comment]
@1997wzk I did this:

```
$ pip uninstall ffmpeg
$ pip uninstall ffmpeg-python
$ pip install ffmpeg 
``` 
Make sure to be in the `deoldify` env when you run these commands (`conda activate deoldify`).

**Comment by 1997wzk** [comment]
@jtn7 Thank you,I did it sucessfully for your help!
