### ISSUE TITLE
GOOGLE DRIVE URL DOWNLOAD CAPABILITY

### ISSUE THREAD

**Issue by isty1974** [jantic/DeOldify#291]
https://drive.google.com/file/d/__________________________________________/view only this method works currently to download mp4 from GDRIVE.
These aren't working:
https://drive.google.com/file/d/__________________________________________/edit
https://drive.google.com/file/d/__________________________________________
https://drive.google.com/open?id=__________________________________________
https://drive.google.com/uc?id=__________________________________________

**Comment by jantic** [comment]
@isty1974  Any links have to be direct to the files when it comes to images. It looks like Google Drive simply doesn't provide those.  We won't be writing special code to accommodate this special use case. It's simply not worth the effort/maintenance relative to the more straight forward options (imgur, etc).
