### ISSUE TITLE
(Video Collab) Video player doesn't appear after overall process is done

### ISSUE THREAD

**Issue by BlueSkyTrading** [jantic/DeOldify#293]
Hi,

All the steps are done with no error, once the Colorize phase is done, it just says Video created here: video/result/video.mp4 without the Video Player appearing with the video

Also I can't access/find video/result/video.mp4 

![Screenshot 2020-11-28 235114](https://user-images.githubusercontent.com/29242247/100533677-18467d80-31d5-11eb-9726-58d07bd84dfd.jpg)

**Comment by jantic** [comment]
There's instructions in the Colab notebook on how to work around this.
