### ISSUE TITLE
how to get the black-white image

### ISSUE THREAD

**Issue by Nickzhangkaiyu** [jantic/DeOldify#308]
it's a excellent work! but I can not get the details about the training dataset, and how to get the white&&black image from the color image.

**Comment by jantic** [comment]
Easy:  Just grab a lot of images- a million+ from [open images](https://storage.googleapis.com/openimages/web/index.html) or imagenet, and use PIL to change the images to black and white to get your before images:

Assuming img is a PIL image:

img = img.convert('L').convert('RGB')

That's it!
