### ISSUE TITLE
Fastai Issue with DeOldify Video Colorization.

### ISSUE THREAD

**Issue by TheVincinator** [jantic/DeOldify#309]
I got an error with fastai even though I installed it will conda at https://github.com/fastai/fastai. I was trying to run the video colorizer and I cannot seem to get it working. Please provide me with some info on this! Thanks! It looks like visualize.py is unable to load fastai.
![Screenshot 2021-01-22 224154](https://user-images.githubusercontent.com/68995370/105567851-185d8800-5d03-11eb-99bc-9ef2ca16b85c.png)

**Comment by TheVincinator** [comment]
I was also wondering if it was my GPU holding me back. I am currently using the Radeon 5700 XT. Does it require an NVIDIA GPU? I found this article on it: https://www.fast.ai/2017/11/16/what-you-need/

**Comment by TheVincinator** [comment]
Nevermind, I got it working!

**Comment by galaxyentity904** [comment]
What exactly did you do? im having the same error and cant get it working

**Comment by jantic** [comment]
@galaxyentity904 With a conda install (which is strongly recommended), this would happen if you forgot to activate the deoldify environment before launching Jupyter.  That is, you'd need to do this:

`conda activate deoldify`

or

`source activate deoldify`

One of those should work.

If you're not doing the conda install route, then it could be one of several things going wrong but you'd be on your own for that (not supported).

**Comment by galaxyentity904** [comment]
> @galaxyentity904 With a conda install (which is strongly recommended), this would happen if you forgot to activate the deoldify environment before launching Jupyter via the command line.  That is, you'd need to do this:
> 
> `conda activate deoldify`
> 
> or
> 
> `source activate deoldify`
> 
> One of those should work.
> 
> If you're not doing the conda install route, then it could be one of several things going wrong but you'd be on your own for that (not supported).

@jantic 
I did do a conda install. But also I figured out a fix I forgot to share, I switched to the version made for colab instead of whatever I was on before.
Thanks!
