### ISSUE TITLE
Remove Water Mark on Jupyter Lab

### ISSUE THREAD

**Issue by TheVincinator** [jantic/DeOldify#311]
I successfully got DeOldify working on Jupyter Lab! Is there any way to remove the watermark from your video using that program? I could not find an option to uncheck the watermark.

**Comment by jantic** [comment]
@TheVincinator Sure, just update the code under colorizer to look like this.  Only thing I've changed here is adding the "watermarked=False" parts.


`
#NOTE:  Max is 44 with 11GB video cards.  21 is a good default
render_factor=21
#NOTE:  Make source_url None to just read from file at ./video/source/[file_name] directly without modification
source_url='https://twitter.com/silentmoviegifs/status/1116751583386034176'
file_name = 'DogShy1926'
file_name_ext = file_name + '.mp4'
result_path = None

if source_url is not None:
    result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor, watermarked=False)
else:
    result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor, watermarked=False)

show_video_in_notebook(result_path)`
