### ISSUE TITLE
about the number of the images in trainging singgle generator 

### ISSUE THREAD

**Issue by Nickzhangkaiyu** [jantic/DeOldify#314]
Hi, I implement this project with tensorflow but get the bad effect. I want to know the number of the images when trainging generator only, is it the total of the imagenet traingset? thanks!

**Comment by jantic** [comment]
@Nickzhangkaiyu So yes, all of imagenet is downloaded and used to train DeOldify.  I should point out though that in the training notebooks that there's a keep_pct variable which ranges from 0.0 to 1.0 (100%) that controls the percentage of the dataset used for each step.  See [here ](https://github.com/jantic/DeOldify/blob/master/ColorizeTrainingArtistic.ipynb)for example.

I will say this:  I think there's a very high likelihood of a mismatch in implementations when attempting to do this on Tensorflow. You'd have to not only reimplement what's in the DeOldify code itself but also the FastAI code that it depends on.  It's a lot of moving parts. I would strongly recommend not trying to go down that path if you can avoid it.
