### ISSUE TITLE
Exception: [Errno 2] No such file or directory: 'models\\tmpg2yq0doa'

### ISSUE THREAD

**Issue by tenkabob** [jantic/DeOldify#316]
Hi,

After installing with Anaconda I get the following error when trying to execute step 4: 

Exception: [Errno 2] No such file or directory: 'models\\tmpg2yq0doa'
Can't write to 'models', set `learn.model_dir` attribute in Learner to a full libpath path that is writable

Another user was able to fix this by removing the read-ony flag. 
This doesn't work, It changes back to read-only immediately, even when done via admin cmd.

any guesses?

Windows 10 system

**Comment by laemmlem** [comment]
Same problem here

**Comment by srinivas68** [comment]
Deoldify not working on windows system

**Comment by laemmlem** [comment]
> Deoldify not working on windows system

You should use Ubuntu or alternative Linux dist in WSL2. 
Try to execute `!mkdir 'models'` before `colorizer = get_image_colorizer(...)`

**Comment by jantic** [comment]
Hey guys....readme says this:

> Windows is not supported and any issues brought up related to this will not be investigated.

I'm sticking to that policy. Fastai 1.x doesn't support Windows officially so I'm certainly not going to to try to work around that.

Closing this issue.
