### ISSUE TITLE
Colorizing using custom model

### ISSUE THREAD

**Issue by ruairiseosamh** [jantic/DeOldify#318]
Is it possible to use a custom model in the ImageColorizerColab.ipynb instead of the given ColorizeArtistic_gen.pth one? 

I have used the ColorizeTrainingArtistic.ipynb to train my own model. I then put it into /DeOldify/models. When I run the "colorizer = get_image_colorizer(artistic=True)" line I get a runtime error, saying that:

Missing key(s) in state_dict: "layers.4.conv1.0.weight_orig", "layers.4.conv1.0.weight", "layers.4.conv1.0.weight_u", "layers.4.conv1.0.weight_orig", "layers.4.conv1.0.weight_u", "layers.4.conv1.0.weight_v", "layers.4.conv1.2.weight", "layers.4.conv1.2.bias", "layers.4.conv1.2.running_mean", "layers.4.conv1.2.running_var", "layers.4.conv2.0.weight_orig", "layers.4.conv2.0.weight", "layers.4.conv2.0.weight_u", "layers.4.conv2.0.weight_orig", "layers.4.conv2.0.weight_u", "layers.4.conv2.0.weight_v", "layers.4.conv2.2.weight", "layers.4.conv2.2.bias", "layers.4.conv2.2.running_mean", "layers.4.conv2.2.running_var", "layers.5.conv1.0.weight_orig", "layers.5.conv1.0.weight", "layers.5.conv1.0.weight_u", "layers.5.conv1.0.weight_orig", "layers.5.conv1.0.weight_u", "layers.5.conv1.0.weight_v", "layers.5.conv1.2.weight", "layers.5.conv1.2.bias", "layers.5.conv1.2.running_mean", "layers.5.conv1.2.running_var", "layers.5.conv2.0.weight_orig", "layers.5.conv2.0.weight", "layers.5.conv2.0.weight_u", "layers.5.conv2.0.weight_orig", "layers.5.conv2.0.weight_u", "layers.5.conv2.0.weight_v", "layers.5.conv2.2.weight", "layers.5.conv2.2.bias", "layers.5.conv2.2.running_mean", "layers.5.conv2.2.running_var", "layers.5.conv2.3.gamma", "layers.5.conv2.3.query.weight_orig", "layers.5.conv2.3.query.weight", "layers.5.conv2.3.query.weight_u", "layers.5.conv2.3.query.weight_orig", "layers.5.conv2.3.query.weight_u", "layers.5.conv2.3.query.weight_v", "layers.5.conv2.3.key.weight_orig", "layers.5....
	Unexpected key(s) in state_dict: "layers.0.4.0.conv3.weight", "layers.0.4.0.bn3.weight", "layers.0.4.0.bn3.bias", "layers.0.4.0.bn3.running_mean", "layers.0.4.0.bn3.running_var", "layers.0.4.0.bn3.num_batches_tracked", "layers.0.4.0.downsample.0.weight", "layers.0.4.0.downsample.1.weight", "layers.0.4.0.downsample.1.bias", "layers.0.4.0.downsample.1.running_mean", "layers.0.4.0.downsample.1.running_var", "layers.0.4.0.downsample.1.num_batches_tracked", "layers.0.4.1.conv3.weight", "layers.0.4.1.bn3.weight", "layers.0.4.1.bn3.bias", "layers.0.4.1.bn3.running_mean", "layers.0.4.1.bn3.running_var", "layers.0.4.1.bn3.num_batches_tracked", "layers.0.4.2.conv3.weight", "layers.0.4.2.bn3.weight", "layers.0.4.2.bn3.bias", "layers.0.4.2.bn3.running_mean", "layers.0.4.2.bn3.running_var", "layers.0.4.2.bn3.num_batches_tracked", "layers.0.5.0.conv3.weight", "layers.0.5.0.bn3.weight", "layers.0.5.0.bn3.bias", "layers.0.5.0.bn3.running_mean", "layers.0.5.0.bn3.running_var", "layers.0.5.0.bn3.num_batches_tracked", "layers.0.5.1.conv3.weight", "layers.0.5.1.bn3.weight", "layers.0.5.1.bn3.bias", "layers.0.5.1.bn3.running_mean", "layers.0.5.1.bn3.running_var", "layers.0.5.1.bn3.num_batches_tracked", "layers.0.5.2.conv3.weight", "layers.0.5.2.bn3.weight", "layers.0.5.2.bn3.bias", "layers.0.5.2.bn3.running_mean", "layers.0.5.2.bn3.running_var", "layers.0.5.2.bn3.num_batches_tracked", "layers.0.5.3.conv3.weight", "layers.0.5.3.bn3.weight", "layers.0.5.3.bn3.bias", "layers.0.5.3.bn3.running_me...
	size mismatch for layers.0.4.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layers.0.4.1.conv1.weight: copying a param with shape torch.Size([64, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for layers.0.4.2.conv1.weight: copying a param with shape torch.Size([64, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).

Does anyone know how to fix this? I'm not sure whether this is from the training stage or the testing stage.

Thanks

**Comment by ruairiseosamh** [comment]
"colorizer = get_image_colorizer(artistic=True)" needed to be changed to "colorizer = get_image_colorizer(artistic=False)" because I had used ColorizeTrainingStable.ipynb not ColorizeTrainingArtistic.ipynb.

**Comment by jyotsanh** [comment]
HI, there can you tell me did you train the pre-existing model "./ColorizeArtistic_gen.pth" in your custom dataset or made a model from scratch. On How many images did you train the model , to get a nice outcome.

**Comment by jantic** [comment]
1. Used pretrained resnet34 backbone in a custom designed unet.
2. Trained dataset on Imagenet1k(black and white inputs, original color outouts) (can do much better than imagenet!)
3. Imagnet1K has 1.3 million images.

**Comment by jyotsanh** [comment]
Hi , again  my questions are:
1. If I use your ColorizeTrainingArtisitc.ipynb notebook and train a generator model on 5k custom images of temples only, will that be enough?
2. Does your ColorizeTrainingArtistic.ipynb notebook fine-tunes the pre-trained **DeOldify** model which performance can be seen in [ImageColorizerColab.ipynb](https://colab.research.google.com/github/jantic/DeOldify/blob/master/ImageColorizerColab.ipynb) notebook or it creates a new model.
3. If I have to fine-tune the DeOldify model  on my custom 5k colorful temple images, which then i can use to colorize the old black and white images of my hometown, what are things you would recommend me to consider and how would i achieve this task.?
