### ISSUE TITLE
Switching to a more precise FID (and other metrics) computation tool

### ISSUE THREAD

**Issue by toshas** [jantic/DeOldify#322]
Hi, I'm the maintainer of [torch-fidelity](https://github.com/toshas/torch-fidelity), a pip package and a CLI tool for epsilon-exact computation of the Inception Score, FID, and KID metrics (as compared to tensorflow originals). Would a PR switching current metrics computation code to torch-fidelity calls be considered?

**Comment by jantic** [comment]
@toshas That sounds fantastic! I'd love that.

**Comment by jantic** [comment]
Closing due to innactivity.
