### ISSUE TITLE
docker pull deoldify , access denied 

### ISSUE THREAD

**Issue by HelloXyp** [jantic/DeOldify#338]
hi~,here's the issue

./quick_start.sh video_api

log:
nvidia card found running on GPU
Docker started from cache
Access your video_api on port 5000 (api) or 8888 (notebook)
Unable to find image 'deoldify:latest' locally
docker: Error response from daemon: pull access denied for deoldify, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

also when i run the image deoldify_api ,and called the API for image processing for a local image，
We have the same problem with this issue：
https://github.com/jantic/DeOldify/issues/336

**Comment by jantic** [comment]
Thanks for the report. I won't be prioritizing digging into this issue anytime soon- too much on the plate elsewhere currently.

**Comment by jqueguiner** [comment]
did you login to docker as request per the error message ?

**Comment by HelloXyp** [comment]
1.We later ran the project through the following command：
 ->$:docker build -t deoldify_jupyter -f Dockerfile .
And the effect looks great！
2.But during the deployment process, we found some problems and modified the code to solve them. I don't know if this problem is usual or independent. Here is a record for you:
  We run DeOldify through step 1, but we found that the CPU utilization rate during the operation is 3000%, while the GPU utilization rate is 0%. This situation is the same in the video slicing and colorize process running.
  We made the process run on the GPU by forcibly modifying the code. We haven’t found a deeper reason yet.
  /deoldify/_device.py  line 12 ： self.set(DeviceId.CPU) -> self.set(DeviceId.GPU0)

**Comment by jqueguiner** [comment]
Happy that you were able to solve it

**Comment by jqueguiner** [comment]
@jantic  I think we can close it

**Comment by mabushey** [comment]
@jqueguiner 
`->$:docker build -t deoldify_jupyter -f Dockerfile .`

Any chance you could share your `Dockerfile`?
