### ISSUE TITLE
how to colorize all image files in specific folder?

### ISSUE THREAD

**Issue by apuokas** [jantic/DeOldify#341]
Hallo,
i dont knew if it is a isuse, but maybe i bekomme help.
My Problem: in jupiter lab on own pc, in ImageColorizer.ipynb, i tryed colorize all fotos in specific folder. I used it like this "source_path = './foto/*.jpg'" and this "source_path = './foto/'" etc. , but i becomme error like "no such file" or "you dont have permisions for this folder". But if i use like this "source_path = './foto/00001.jpg'", single specific file, its all ok. Such command working too:
"#NOTE:  Max is 45 with 11GB video cards. 35 is a good default
render_factor=35
watermarked = False #@param {type:"boolean"}
#NOTE:  Make source_url None to just read from file at ./video/source/[file_name] directly without modification
source_url= None
#source_path = './foto/00001.jpg-43799.jpg' - not working
source_path = './foto/00001.jpg'
source_path = './foto/00002.jpg'
source_path = './foto/00464.jpg'
result_path = None

if source_url is not None:
    result_path = colorizer.plot_transformed_image_from_url(url=source_url, path=source_path, render_factor=render_factor, compare=False)
else:
    result_path = colorizer.plot_transformed_image(path=source_path, render_factor=render_factor, compare=False)

#show_image_in_notebook(result_path)"
I need colorize about 50.000 jpg files at once. Is it posible? Im using jupiter lab on windows 10 with cuda, geforce gtx 1060 6GB, Ryzen 7 3700x, 32GB RAM
Edit: Now i tryed to wrote all 43799 jpg files in separate new lines and jupiter lab makes job just for last file, but show no errors

**Comment by jantic** [comment]
This would be a "batch process" and is beyond the scope of what we're willing to provide support for here.  What you're trying to do here simply isn't supported in the notebooks.

**Comment by Dominic-ZZ** [comment]
I do it like this, but it takes a lot of time.
```
import os
img_root='test_image' #your image folder
for img_path in os.listdir(img_root):
	source_path=os.path.join(img_root,img_path)
	print(source_path)
	result_path=None
	if source_url is not none:
		result_path=......
```

**Comment by Dominic-ZZ** [comment]
I do it like this: 

```
source_url=None
img_root='./test_images'
i=0
for img_path in os.listdir(img_root):
    source_path=os.path.join(img_root,img_path)
    i+=1
    print(i,source_path)
    # source_path = 'test_images/1.jpg'
    result_path = None
    if source_url is not None:
        result_path = colorizer.plot_transformed_image_from_url(url=source_url, path=source_path, render_factor=render_factor, compare=True)
    else:
        result_path = colorizer.plot_transformed_image(path=source_path, render_factor=render_factor, compare=True)
    # show_image_in_notebook(result_path)
```

and comment the code in visualize.py. (this code will cause CPU memory to increase constantly)

```
    def plot_transformed_image(
        self,
        path: str,
        results_dir:Path = None,
        figsize: (int, int) = (20, 20),
        render_factor: int = None,
        display_render_factor: bool = False,
        compare: bool = False,
        post_process: bool = True,
        watermarked: bool = True,
    ) -> Path:
        path = Path(path)
        if results_dir is None:
            results_dir = Path(self.results_dir)
        result = self.get_transformed_image(
            path, render_factor, post_process=post_process,watermarked=watermarked
        )
        orig = self._open_pil_image(path)
        # if compare:
        #     self._plot_comparison(
        #         figsize, render_factor, display_render_factor, orig, result
        #     )
        # else:
        #     self._plot_solo(figsize, render_factor, display_render_factor, result)
        orig.close()
        result_path = self._save_result_image(path, result, results_dir=results_dir)
        result.close()
        return result_path
```
