### ISSUE TITLE
Color flickering

### ISSUE THREAD

**Issue by Saartjes** [jantic/DeOldify#343]
Hi,

I have used your amazing model to colorize episodes of an old kids show in my country. It looks amazing but I am still trying to resolve an issue. The color in my videos tends to flicker a quite lot. It seems to happens mostly during busy scenes or during movement in a scene.

Do you have any tips on how to combat this issue? I have tried different render-factors but that does not seem to do the trick. 

Thanks in advance for your answer!

**Comment by jantic** [comment]
So what you're really running into here is the fundamental limitation of the approach of  the open source DeOldify's video implementation- it's based purely on colorizing frames one at a time without considering consistency between frames.  This was a sort of "20/80" solution in my mind- 20% effort to get 80% results, as this can produce good results.  It's just not the best nor ideal solution.  It's an engineering trade-off.

The -only- way I can tell you to deal with this is:
-  Generally, you simply can't expect good results with rough old videos. The higher the quality, the better.
-  Best results come out of experimentation with render_factor. Generally, the lower the quality the video, the lower the render_factor you should try using.
