### ISSUE TITLE
please, explain

### ISSUE THREAD

**Issue by apuokas** [jantic/DeOldify#344]
Hallo,
i just want to knew what does: "range(10,40,2)", "render_factor=i", "display_render_factor=True", "figsize=(8,8)" in ColorizeVideo?
And: if i have nvidia geforce gtx 1060 6GB and nvidia tesla K40 12GB, what G-Card would you use for DeOldify?
Best Regards

**Comment by jantic** [comment]
Answers are already provided in notebook and readme. I won't be reiterating what has already been said.
