### ISSUE TITLE
Completed Generator Weights

### ISSUE THREAD

**Issue by omegavegas1313** [jantic/DeOldify#345]
Not an issue, but rather a question.  Regarding the Completed Generator Weights, do these get updated and if so, how often?

**Comment by jantic** [comment]
@omegavegas1313  There's no plan to update them anytime soon, and the last time there was an update was in April 2019 with the release of DeOldify V2 (DeOldify V1 was in November 2018). We develop commercial models now separate from this open source project. There's a possibility that there will be weight updates benefiting from that work in the more distant future (we're talking years not months), but I wouldn't hold your breath.
