### ISSUE TITLE
Possibility to implement Unified Virtual Memory?

### ISSUE THREAD

**Issue by oregonpillow** [jantic/DeOldify#346]
Problem: High render values eat up VRAM quickly and limit output quality, but many people have plenty of RAM sitting idle which could be used to increase render values.

Solution: Implement UVM using Nvidia's [_cudaMallocManaged_](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html) to unify memory at the cost of speed. The nature of the project means that output quality for most use cases would be more important that render time.

**Comment by jantic** [comment]
This is actually a thing PyTorch would need to implement, and as far as I can tell, this feature certainly has been requested but they have yet to implement it (don't know if they ever will).

I can tell you though if you're really quite fine with sacrificing speed to be able to render at higher render_factors (which doesn't necessarily imply higher quality, to be clear), you can run the model on CPU by doing this at the top (before calling anything else)

```
from deoldify import device
from deoldify.device_id import DeviceId
device.set(device=DeviceId.CPU)
```

But, fair warning, that will be very slow!
