### ISSUE TITLE
add pip dependency to environment.yml

### ISSUE THREAD

**Issue by cadeon** [jantic/DeOldify#347]
Scrolling warning when building the environment:
"
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
"

Adding pip as a dependency fixes this.

**Comment by jantic** [comment]
This is resolved.  Thank you!
