### ISSUE TITLE
Comercial products?

### ISSUE THREAD

**Issue by theman8631** [jantic/DeOldify#349]
Not an issue - but I'm doing a video colorizing project I'm quite passionate about with silent films and would like the best automation software to assist.  I've used deoldify thinking its the best but have seen references to not updating the weights and much of the development going into other commercial products.  Is there a commercial product I can buy with the most current development efforts that colorizes video any better then deoldify?

**Comment by omegavegas1313** [comment]
I'm on the same boat with theman8631.  I too am colorizing old video clips for personal use.  Deoldify has been a magical tool, especially seeing my grandfather in color.  How much difference are the new generated weights compared to what has been released?   I hope you'll consider making a consumer product in the near future.

**Comment by jantic** [comment]
> Is there a commercial product I can buy with the most current development efforts that colorizes video any better then deoldify?

Not that I'm aware of, but honestly I really haven't been looking lately, so I could easily be missing something. If anybody else knows of anything, please chime in.

It's a difficult problem and apparently a very niche space to work in.

> How much difference are the new generated weights compared to what has been released?

We don't have a new video model.  We have new images models which we consider to be prerequisite work to making _good_ video, but we don't feel like we're at the point both research-wise and  bandwidth-wise in what we can do with our time to be able to do a true leap in the tech that would be something we could commercialize.  

Keep in mind, people definitely want this and we're well aware of that fact, but going from that to something that can actually work out as a business with just two of us working at DeOldify is a big difference. Seriously, it's just two of us!

To be fair we did experimentation on a "1.5" version of sorts back in summer of 2019 but it wasn't the kind of leap we were looking for.  [See here for an example.]( https://www.youtube.com/watch?v=u9Z3lCmIOlg) . But there's a number of reasons why that remained just an experiment which I won't delve into here.

**Comment by theman8631** [comment]
Start a patreon for early access my man.
