### ISSUE TITLE
_load_model_data() get IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by orrimoch** [jantic/DeOldify#35]
Hi all!

I'm getting this error:
IndexError: index 0 is out of bounds for axis 0 with size 0

For some reason the data couldn't be loaded properly in _load_model_data()
Maybe someone had similar issue?

Thanks,
Or

**Comment by jantic** [comment]
Ok man, you'll now get a message that says something like this the one below.  So basically it looks like you need to make sure you have imagenet in the right location.

ValueError: No image files were found in specified image directory. Path provided was: data/imagenet/ILSVRC/Data/CLS-LOC/trai
