### ISSUE TITLE
local variable 'url' referenced before assignment

### ISSUE THREAD

**Issue by wsloong** [jantic/DeOldify#352]
hi~,here's the issue

**platform: CentOS 7.2**
**docker: 20.10.6**

`./quick_start.sh video_api`

`
NVIDIA Release 19.04 (build 6089340)
PyTorch Version 1.1.0a0+9eb0f43

Container image Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2019 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --ipc=host ...

/opt/conda/lib/python3.6/site-packages/fastai/data_block.py:442: UserWarning: Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.
  warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
/opt/conda/lib/python3.6/site-packages/fastai/data_block.py:445: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  or pass `ignore_empty=True` when labelling to remove this warning.""")
Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /root/.torch/models/resnet101-5d3b4d8f.pth
178728960it [00:24, 7328787.34it/s]
 * Serving Flask app "app-video" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
`

1. when i do

`curl -X POST "http://127.0.0.1:5000/process" -H "accept: application/octet-stream" -H "Content-Type: application/json" -d "{\"url\":\"http://host:port/playlist.m3u8\", \"render_factor\":35}" --output colorized_video.mp4`

I Got this:
**Traceback (most recent call last):
  File "app-video.py", line 73, in process_video
    source_url=url, file_name=input_path, render_factor=render_factor
  File "/data/deoldify/visualize.py", line 340, in colorize_from_url
    source_path, render_factor=render_factor, post_process=post_process,watermarked=watermarked
  File "/data/deoldify/visualize.py", line 358, in _colorize_from_path
    self._extract_raw_frames(source_path)
  File "/data/deoldify/visualize.py", line 256, in _extract_raw_frames
    ffmpeg.input(str(source_path)).output(
AttributeError: module 'ffmpeg' has no attribute 'input'**

2. when i do
`curl -X POST "http://127.0.0.1:5000/process" -H "accept: application/octet-stream" -H "Content-Type: multipart/form-data" -F "file=@/root/origin.mp4"  -F "render_factor=35" --output colorized_video.mp4`

I Got this:
**Traceback (most recent call last):
  File "app-video.py", line 73, in process_video
    source_url=url, file_name=input_path, render_factor=render_factor
UnboundLocalError: local variable 'url' referenced before assignment**

**Comment by wsloong** [comment]
> I’ll look into it next week

👌，Thanks

**Comment by wsloong** [comment]
for **AttributeError: module 'ffmpeg' has no attribute 'input'**

I fix `Dockerfile` online 23:
`
RUN pip install --upgrade pip \
        && pip install versioneer==0.18 \
                tensorboardX==1.6 \
                Flask==1.1.1 \
                pillow==6.1 \
                numpy==1.16 \
                scikit-image==0.15.0 \
                requests==2.21.0 \
                # ffmpeg==1.4 \
                # ffmpeg-python==0.1.17 \
                ffmpeg-python \
                youtube-dl>=2019.4.17 \
                jupyterlab==1.2.4 \
                opencv-python>=3.3.0.10 \
                fastai==1.0.51
`

I try on Ubuntu and CentOS; it works！
In container `ffmpeg-python==0.2.0`

**Comment by jantic** [comment]
Closed due to inactivity
