### ISSUE TITLE
Cublas runtime error - help needed

### ISSUE THREAD

**Issue by JJR1984** [jantic/DeOldify#353]
Hi everyone,

I've encountered a problem with running DeOldify to process a local video file and appreaciate your help!

Data about my computer/installed versions:
Win10 64 bit
CPU: Intel i9
GPU: GeForce RTX 3080

Python 3.8.5
PyTorch 1.8.1

Here is the error message: 

C:\Users\User\.conda\envs\deoldify\lib\site-packages\torch\cuda\__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

What can I do?

Let me know if you need additional infos from me. 
Thank you

**Comment by jantic** [comment]
From the readme:

`Windows is not supported and any issues brought up related to this will not be investigated.`

This hasn't changed and I wouldn't bet on this stance changing anytime soon.  I'll also point out that you're using PyTorch and Python versions that won't work with DeOldify. 

There's detailed instructions on how to install, and many issues opened already about trying to run on Windows where I have to keep swatting them down and pointing them to the same thing in the readme over and over again.

Personalized assistance on the inevitable issues of ignoring all this just isn't something we're willing to do. Sorry!

</rant>
