### ISSUE TITLE
How to train with cuda11

### ISSUE THREAD

**Issue by KarolyPoka** [jantic/DeOldify#354]
Hi! I am trying to train the model but the whole repo is based on Fastai 1.0.51 and Pytorch 1.0.1. My GPU has Ampere architecture and it needs cuda11 with pytorch 1.8. **Unfortunately there is no pytorch 1.0.1 version with cuda11**. Do you have any idea how to adapt the code base to newer package versions? Or **how could it be possible to train with new RTX 30x series GPU**?

**Comment by jantic** [comment]
So you can indeed update this project to the latest PyTorch and corresponding cuda11.  We did that with our internal fork of DeOldify, which has become our commercial offerings. We're not ready yet to update the open source code with that, but I can tell you that it involves making a few changes to a fork of Fastai 1.0.51. The errors should pretty much guide you without too much ambiguity.

**Comment by KarolyPoka** [comment]
Thank you for the answer! I made some changes which helped:
1. fastai.vision.transform.py: line 243 torch.gsv replaced with torch.solve
2. fastai.vision.image.py: line 183 tensors converted to float
3. fastai/vision/image.py:
**replace**:
F.interpolate(x[None], scale_factor=1/d, mode='area') 
by
F.interpolate(x[None], scale_factor=1/d, mode='area', recompute_scale_factor=True)
**replace:**
return F.grid_sample(x[None], coords, mode=mode, padding_mode=padding_mode)[0]
by
return F.grid_sample(x[None], coords, mode=mode, padding_mode=padding_mode, align_corners=True)[0]

The ColorizeTrainingStable.ipynb is running until the second epoch, where the system is running out of CPU RAM (64Gb). I read that if num_workers>0 the memory leak problem could happen with PyTorch. I did not find any solution for that problem (even with changing the number of workers), so I wanted to ask if you have or had the same issue with the newer PyTorch version. I checked all of the issue threads but this particular problem was never solved. Could you help me with this? Thanks in advance!

**Comment by KarolyPoka** [comment]
I figured it out, it happens when the tensorboard callback is appended. If I remove it memory leak not happens.

**Comment by jantic** [comment]
@KarolyPoka oh that's a fantastic find! I'll try to see what needs to be changed in order to get things taken care of there then.  I can't believe I did that (that was definitely my bad).

**Comment by jantic** [comment]
Actually sorry @KarolyPoka I slightly misremembered and thought I needed to change existing repo.  But anyway- one thing I've actually talked about about our work beyond the open source repo here was on the fastai forums-  that I had trouble with the new GraphWriter code that was added and my solution was to make a fork of fastai and comment that graph_writer code out.   [forum post here](https://forums.fast.ai/t/tensorboard-integration/38023/21) . I honestly don't remember what all I saw at the time with that code but it was definitely problematic and kept me from moving forward.

**Comment by lkp520** [comment]
> I figured it out, it happens when the tensorboard callback is appended. If I remove it memory leak not happens.

Can you tell me the detail of removing tensorboard callback? I don not know how to do it. Thank you very much!

**Comment by jantic** [comment]
@lkp520 

That would mean commenting out lines that look like this (found in the ColorizeTrainingArtistic notebook):

learn_gen.callback_fns.append(partial(ImageGenTensorboardWriter, base_dir=TENSORBOARD_PATH, name='GenPre'))

**Comment by lkp520** [comment]
> @lkp520
> 
> That would mean commenting out lines that look like this (found in the ColorizeTrainingArtistic notebook):
> ` learn_gen.callback_fns.append(partial(ImageGenTensorboardWriter, base_dir=TENSORBOARD_PATH, name='GenPre'))`

Thank you! I try it.
