### ISSUE TITLE
Inference uses only one CPU

### ISSUE THREAD

**Issue by farazBhatti** [jantic/DeOldify#355]
When running inference for coloriszingVideo using CPU, the code only uses one CPU while other ones are not used. Is there anything I am missing? Thanks

Ram 12GB
CPU(s) = 4

**Comment by jantic** [comment]
I took a quick look at this but it appears to be more involved than I imagined.  I'll be committing a fix that seems to speed things up a bit when doing CPU inference (about 10%) . But I won't be looking into this further anytime soon. Optimizing for CPU just isn't a focus of this project.
