### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by dstef81** [jantic/DeOldify#358]
Hello,
Ive used this colab online and loved it!
now, im trying to run it locally on an Ubuntu install.

What i get after the youtube file downloaded is this:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-bdec7f38a11a> in <module>
      8 
      9 if source_url is not None:
---> 10     result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)
     11 else:
     12     result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)

~/DeOldify/DeOldify/deoldify/visualize.py in colorize_from_url(self, source_url, file_name, render_factor, post_process, watermarked)
    338         self._download_video_from_url(source_url, source_path)
    339         return self._colorize_from_path(
--> 340             source_path, render_factor=render_factor, post_process=post_process,watermarked=watermarked
    341         )
    342 

~/DeOldify/DeOldify/deoldify/visualize.py in _colorize_from_path(self, source_path, render_factor, watermarked, post_process)
    356                 'Video at path specfied, ' + str(source_path) + ' could not be found.'
    357             )
--> 358         self._extract_raw_frames(source_path)
    359         self._colorize_raw_frames(
    360             source_path, render_factor=render_factor,post_process=post_process,watermarked=watermarked

~/DeOldify/DeOldify/deoldify/visualize.py in _extract_raw_frames(self, source_path)
    254         bwframes_folder.mkdir(parents=True, exist_ok=True)
    255         self._purge_images(bwframes_folder)
--> 256         ffmpeg.input(str(source_path)).output(
    257             str(bwframe_path_template), format='image2', vcodec='mjpeg', qscale=0
    258         ).run(capture_stdout=True)

AttributeError: module 'ffmpeg' has no attribute 'input'

----

i've tried uninstall and reinstall of ffmpeg-python 

denis@denispc:~$  pip install ffmpeg-python
Collecting ffmpeg-python
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from ffmpeg-python) (0.18.2)
Installing collected packages: ffmpeg-python
Successfully installed ffmpeg-python-0.2.0

but i still get the same error.

The file i run is VideoColorizer.ipynb

can you help?

thank you!

**Comment by jantic** [comment]
@dstef81  can you provide the exact YouTube url you're attempting here?

**Comment by dstef81** [comment]
Hello!

This is the full screen, hope this one helps, thanks! :
Last Modified

#NOTE:  This must be the first call in order to work properly!

from deoldify import device

from deoldify.device_id import DeviceId

#choices:  CPU, GPU0...GPU7

device.set(device=DeviceId.GPU0)

<DeviceId.GPU0: 0>

from deoldify.visualize import *

plt.style.use('dark_background')

import warnings

warnings.filterwarnings("ignore", category=UserWarning, message=".*?Your .*? set is empty.*?")

colorizer = get_video_colorizer()

Instructions
source_url

Type in a url hosting a video from YouTube, Imgur, Twitter, Reddit, Vimeo, etc. Many sources work! GIFs also work. Full list here: https://ytdl-org.github.io/youtube-dl/supportedsites.html NOTE: If you want to use your own video, you can set source_url to None and just upload the file to video/source/ in Jupyter. Just make sure that the file_name parameter matches the file you uploaded.
file_name

Name this whatever sensible file name you want (minus extension)! It should actually exist in video/source if source_url=None
render_factor

The default value of 21 has been carefully chosen and should work -ok- for most scenarios (but probably won't be the -best-). This determines resolution at which the color portion of the video is rendered. Lower resolution will render faster, and colors also tend to look more vibrant. Older and lower quality film in particular will generally benefit by lowering the render factor. Higher render factors are often better for higher quality videos and inconsistencies (flashy render) will generally be reduced, but the colors may get slightly washed out.
file_name_ext

There's no reason to changes this.
result_path

Ditto- don't change.
How to Download a Copy

Simply shift+right click on the displayed video and click "Save video as..."!
Pro Tips

    If a video takes a long time to render and you're wondering how well the frames will actually be colorized, you can preview how well the frames will be rendered at each render_factor by using the code at the bottom. Just stop the video rendering by hitting the stop button on the cell, then run that bottom cell under "See how well render_factor values perform on a frame here". It's not perfect and you may still need to experiment a bit especially when it comes to figuring out how to reduce frame inconsistency. But it'll go a long way in narrowing down what actually works.

Troubleshooting

The video player may wind up not showing up, in which case- make sure to wait for the Jupyter cell to complete processing first (the play button will stop spinning). Then follow these alternative download instructions

    In the menu to the left, click Home icon.
    By default, rendered video will be in /video/result/

If a video you downloaded doesn't play, it's probably because the cell didn't complete processing and the video is in a half-finished state. If you get a 'CUDA out of memory' error, you probably have the render_factor too high. The max is 44 on 11GB video cards.
Colorize!!

#NOTE:  Max is 44 with 11GB video cards.  21 is a good default

render_factor=21

#NOTE:  Make source_url None to just read from file at ./video/source/[file_name] directly without modification

source_url='https://www.youtube.com/watch?v=HQXNdcNQWe4'

file_name = 'sevrwn'

file_name_ext = file_name + '.mp4'

result_path = None

​

if source_url is not None:

    result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)

else:

    result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)

​

show_video_in_notebook(result_path)

[youtube] HQXNdcNQWe4: Downloading webpage
[youtube] HQXNdcNQWe4: Downloading MPD manifest
[dashsegments] Total fragments: 22
[download] Destination: video/source/sevrwn.f137.mp4
[download] 100% of 52.26MiB in 01:214.84KiB/s ETA 00:00:21
[download] Destination: video/source/sevrwn.mp4.f140
[download] 100% of 2.05MiB in 00:03.76KiB/s ETA 00:00
[ffmpeg] Merging formats into "video/source/sevrwn.mp4"
Deleting original file video/source/sevrwn.f137.mp4 (pass -k to keep)
Deleting original file video/source/sevrwn.mp4.f140 (pass -k to keep)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-3fa061bb217c> in <module>
      8 
      9 if source_url is not None:
---> 10     result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)
     11 else:
     12     result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)

~/DeOldify/DeOldify/deoldify/visualize.py in colorize_from_url(self, source_url, file_name, render_factor, post_process, watermarked)
    338         self._download_video_from_url(source_url, source_path)
    339         return self._colorize_from_path(
--> 340             source_path, render_factor=render_factor, post_process=post_process,watermarked=watermarked
    341         )
    342 

~/DeOldify/DeOldify/deoldify/visualize.py in _colorize_from_path(self, source_path, render_factor, watermarked, post_process)
    356                 'Video at path specfied, ' + str(source_path) + ' could not be found.'
    357             )
--> 358         self._extract_raw_frames(source_path)
    359         self._colorize_raw_frames(
    360             source_path, render_factor=render_factor,post_process=post_process,watermarked=watermarked

~/DeOldify/DeOldify/deoldify/visualize.py in _extract_raw_frames(self, source_path)
    254         bwframes_folder.mkdir(parents=True, exist_ok=True)
    255         self._purge_images(bwframes_folder)
--> 256         ffmpeg.input(str(source_path)).output(
    257             str(bwframe_path_template), format='image2', vcodec='mjpeg', qscale=0
    258         ).run(capture_stdout=True)

AttributeError: module 'ffmpeg' has no attribute 'input'

**Comment by jantic** [comment]
@dstef81 Something I noticed there is that it doesn't look like you're using conda in that pip command to reinstall ffmeg-python . I'd start with that- install your environment using the provided conda install, as that'll do a great job of making sure you have your dependencies in order. I've been able to run this code fine myself so this really looks like an environment setup issue on your end.

**Comment by hahnjiang** [comment]
delete ffmpeg and use default version ffmpeg-python in requirements.txt. It's ok

**Comment by dstef81** [comment]
Hello,
finally, by installing ffmpeg-python from inside the conda env, did the trick for me! 
There was no way to figure it out as its the first time i try something on conda.
Thank you very much!

**Comment by jantic** [comment]
@dstef81 That's great to hear!
