### ISSUE TITLE
Cannot write in 'models' folder

### ISSUE THREAD

**Issue by Malibutomi** [jantic/DeOldify#360]
Trying to run VideoColorizerColab.ipynb with local connection, whatever i tried i get the same error every time:

F:\Coloring\envs\deoldify\lib\site-packages\fastai\basic_train.py in _test_writeable_path(self)
    175         try: tmp_file = get_tmp_file(path)
    176         except OSError as e:
--> 177             raise Exception(f"{e}\nCan't write to '{path}', set `learn.model_dir` attribute in Learner to a full libpath path that is writable") from None
    178         os.remove(tmp_file)
    179 

Exception: [Errno 2] No such file or directory: 'models\\tmp6inn4pmd'
Can't write to 'models', set `learn.model_dir` attribute in Learner to a full libpath path that is writable

I'm out of ideas what could be the fix. Running it under Anaconda on Win10.

**Comment by dana-kelley** [comment]
Please try your experiment in a Linux environment and the problem should resolve.
