### ISSUE TITLE
Colorizing video on DeepAI

### ISSUE THREAD

**Issue by myfta** [jantic/DeOldify#361]
I hoped to test colorizing a short video on DeepAI. I have tried uploading the video in both MP4 and MOV formats. It is just 59 seconds in length, but it returns an error:

`
error processing given inputs from request`

Am I missing something?

**Comment by dana-kelley** [comment]
Hi @myfta, 

As far as we know, DeepAI has only implemented the still-image colorization of DeOldify. Can you please share the link you are using to colorize video? 

The DeOldify video colab is provided here: https://colab.research.google.com/github/jantic/DeOldify/blob/master/VideoColorizerColab.ipynb. There is a tutorial on how to use DeOldify notebooks here: https://www.youtube.com/watch?v=VaEl0faDw38&t=4s. This information is also available in the readme, and further questions on this topic will be referred there.

Generally speaking for the video colab, if the file won't process, it still might be too long and it's recommended to try a smaller segment.

**Comment by myfta** [comment]
Thank you. The Colab set up worked perfectly on a 4 minute video.
