### ISSUE TITLE
3090 + ubuntu 18 drivers

### ISSUE THREAD

**Issue by tonybarnhill** [jantic/DeOldify#364]
Hi, after using DeOldify on Google Collab for awhile I bought a dedicated Alienware to process my videos. I have the 3090 24GB with the 460 and 465 drivers. I have Jupyter Lab installed and everythings working.
If I boot into Ubuntu, the videocolorizer script hangs at the "Colorize!" step. I donʻt get any info in terminal, just nothing works. The only thing that will make it work again is if I change the drivers from 460 to 465 or to the open source drivers. It doesnʻt seem to matter, just as long as I change it from one to the other. As soon as I do this and relaunch Jupyter, deoldify works again.
I have done a few dozen videos so far and it works great when you get going. I can do several videos in a row without messing with the drivers, but as soon as I reboot I have to toggle the drivers.

Any help is greatly appreciated.
Thank You

**Comment by dan64** [comment]
I got the same problem with my RTX 3060
The problem is that the pytorch version used by deoldify does not support the architecture Ampere. 
It is necessary to switch to CUDA 11.1.

To solve the problem I installed the last version of pytorch with the following command:

`conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.1.1 -c pytorch -c conda-forge`

I tested it on Windows 10 and the it is working properly (the encoding speed increased by about 3x respect to my old GTX 1070). 
I need to do more tests because both Windows 10 and pytorch are not supported by deoldify.

**Comment by dan64** [comment]
I tested the RTX 3060 also with Ubuntu 21.04.  In this case to use DeOldify with CUDA 11.1 it is necessary to create a new environment following these steps:

1) Create a new  environment.yml with the following text:
`name: deoldify1
channels:
- fastai
- pytorch
- conda-forge
- defaults
dependencies:
- pip
- python>=3.7.3
- fastai=1.0.51
- ffmpeg=4.1.1
- tensorboardX=1.6
- youtube-dl>=2019.4.17
- jupyterlab
- pillow=8.2.0
- pip:
  - ffmpeg-python==0.1.18
  - opencv-python>=3.3.0.10
  - wandb`

2) create the env with command:
  
  conda env create -f environment.yml

3) finally install pytorch with cuda 11.1 support with following command:

conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia


P.S. With the version 1.10 pytorch should add the support to CUDA 11.3, this should improve the stability and the performance.

**Comment by tonybarnhill** [comment]
Thank You very much. I had originally installed Ubuntu 20 but couldnʻt get anywhere with it, so attempted with 18.

I updated my Ubuntu install by using:
`conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.1.1 -c pytorch -c conda-forge`

Iʻm running the same job as yesterday and itʻs now taking 14hrs instead of 23hrs, so huge improvement there!

Thanks Again

**Comment by dan64** [comment]
The problem in upgrading the deoldify environment is mainly due to the conda version used to perform the upgrade. I used an Anaconda version of 2019 both in windows and Ubuntu to perform this upgrade. More recent versions of conda performs more consistency checks and don't allow to apply the upgrade. Moreover my RTX 3060 is supported only with the NVIDIA version 465 (cuda 11.3) which is available by default only with Ubuntu 21.04.

**Comment by jantic** [comment]
This is great feedback and information for other users, so thank you guys for that.

I'm going to keep this open for now. Upgrading to the latest Pytorch in the code, at least for training purposes, will require either going to the new FastAI 2.0 or making a custom fork- the latter I've already done before successfully. It's just a few small changes as described here:  [https://github.com/jantic/DeOldify/issues/354](https://github.com/jantic/DeOldify/issues/354) . But it'll be quite a while before I sit down and commit to putting this in the repo formally for a number of reasons.

**Comment by tonybarnhill** [comment]
@jantic thank you for your help!
 Ok, I created a new environmentnew.yml file in the DeOldify folder. But when I try to create the environment, I get an error report that says this:

>  File "/home/admin/anaconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 345, in stale_possible_simple_keys
        "could not find expected ':'", self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: while scanning a simple key
      in "<unicode string>", line 4, column 1:
        fastai
        ^ (line: 4)
    could not find expected ':'
      in "<unicode string>", line 5, column 1:
        pytorch
        ^ (line: 5)

I'm on Ubuntu 18.04.5 LTS exactly. Is it an issue with the version of python?

The rest of the report:

> environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/admin/anaconda3/bin/conda
             CONDA_PREFIX=/home/admin/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/admin/anaconda3/bin/python
               CONDA_ROOT=/home/admin/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/admin/anaconda3/bin:/home/tbadmin/anaconda3/bin:/home/tbadmin/
                          anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/
                          sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/admin/anaconda3
            shell level : 1
       user config file : /home/admin/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/admin/anaconda3  (writable)
      conda av data dir : /home/admin/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/admin/anaconda3/pkgs
                          /home/admin/.conda/pkgs
       envs directories : /home/admin/anaconda3/envs
                          /home/admin/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.21.0 CPython/3.7.3 Linux/5.4.0-77-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by jantic** [comment]
@tonybarnhill  Just based on a quick look at that error message there, it appears you may have simply introduced a typo inadvertently in the environmentnew.yml file you made there, towards the top.  I'd compare it to the original environment file and see where the difference lies.

**Comment by tonybarnhill** [comment]
> @tonybarnhill gosh sorry about that. 

I fixed it and it completed successfully. I activated the new environment, and it's working. Thank You.

**Comment by dan64** [comment]
In the case it can be useful, this is the **environment.yml** for **Linux**:

[environment_linux.yml.txt](https://github.com/jantic/DeOldify/files/6842699/environment_linux.yml.txt)

The environment for **Windows 10** (it is necessary to install Anaconda for windows)
is the following:

[deoldify_env_w10.yml.txt](https://github.com/jantic/DeOldify/files/6842696/deoldify_env_w10.yml.txt)

The encoding speed for the 2 OS is almost the same. On my hardware the encoding of a 720p movie with a render_factor=21 is 6.67fps on Linux and 6.48fps on Windows.

**Comment by tonybarnhill** [comment]
@dan64 thank you for that. I created a new deoldify2 enviornment with your file. I needed to install ipywidgets to that environment otherwise was seeing errors. 
Iʻm seeing 8fps doing 1080p at render_factor=24

Thank you again!

**Comment by tonybarnhill** [comment]
@dan64 ok WOW, I had not rebooted the machine again. But after doing so, I am getting 414fps on 1080p with a render_factor of 28. Iʻm not sure whatʻs going on, but I noticed the fans were kicking up a little higher than normal. Itʻs doing a 29,000 frame file in 1hour 10 minutes. That is crazy!!
This is a 3090 24GB liquid cooled in an Alienware i9 with 128GB ram. There is a serious amount of heat coming out of this thing lol. Thanks Again.

**Comment by tonybarnhill** [comment]
Hi, I just wanted to circle back around after a few weeks with this configuration. It's really fast at converting frames to color, now. 
I was wondering if there is a modification that could be made to allow batch processing with the still image Artistic mode? I ran a few frames through there manually and the color is a bit better than with the video processor.
Thanks for everything.

**Comment by jantic** [comment]
@tonybarnhill It wouldn't be too much code to create a batch process and in fact we have that internally here for our commercial work. But it's not going to be supported here in this project- generally the goal is to keep things as simple as possible and not create 100 more problems in the process of adding a feature that in this case is probably quite niche.

**Comment by StephanosSteer-Sparcatus** [comment]
Just got to say thank you @dan64 this (and different issue putting model folders locally and changing generators.py) allowed deoldify to work for me. Just to note my card is 3070ti
