### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by dstef81** [jantic/DeOldify#365]
Hello !

I try to run the colab version from here:
https://colab.research.google.com/github/jantic/DeOldify/blob/master/VideoColorizerColab.ipynb

but i get the error 
--> 256         ffmpeg.input(str(source_path)).output(
    257             str(bwframe_path_template), format='image2', vcodec='mjpeg', qscale=0
    258         ).run(capture_stdout=True)

AttributeError: module 'ffmpeg' has no attribute 'input'

Here is a full screenshot of the issue:

![Capture](https://user-images.githubusercontent.com/85621307/126224571-7d3c5f1b-b421-4755-a5cc-0104fa74ace7.JPG)

Can you please help?

thank you!

**Comment by PatrickHowardWBTV** [comment]
The exact same issue has been happening for me. Seems to be across multiple machines and logins, and multiple settings choices in the colourize section.

**Comment by dstef81** [comment]
> The exact same issue has been happening for me. Seems to be across multiple machines and logins, and multiple settings choices in the colourize section.

Thats correct. I've tried with different browsers and google accounts but the problem is still there! Im a bit confused as it worked perfectly since recently. maybe something changed on the code? Who knows...

**Comment by orangefunk** [comment]
Not just me then... tried to run it via new Mac mini and thought some problem was occurring there but seems it's also broken via my old computer.

I think its a problem with the ffmpeg library. I have seen mention of using ffmpeg.python instead...

**Comment by Zzip7** [comment]
Всем привет!Я вообще не программист,мучался 2 дня с такой же проблемой,но нашёл для себя решение.Даже на github зарегистрировался.Может кому поможет)))
1. Файл - Сохранить копию на диске
2. После строки   !pip install -r colab_requirements.txt   добавить ОТДЕЛЬНЫХ 3 кода.
pip uninstall ffmpeg
pip uninstall ffmpeg-python
pip install ffmpeg-python
![1](https://user-images.githubusercontent.com/87704893/126325084-2a096b0f-1bee-45b2-a3ce-81d617da5198.jpg)

3.После подключения согласиться 2 раза на удаление "pip uninstall ffmpeg" и "pip uninstall ffmpeg-python"
![2](https://user-images.githubusercontent.com/87704893/126326228-bbe1cde9-62c4-4b12-a7a8-efc5fe719667.jpg)
![3](https://user-images.githubusercontent.com/87704893/126326254-71079d7d-7a53-4511-b847-ed28c5c99054.jpg)

4.Установить  "pip install ffmpeg-python"
![4](https://user-images.githubusercontent.com/87704893/126327012-cd08f83e-104c-4a74-a231-5d0c6661a09c.jpg)

5.Дальше как обычно.

И ещё нашёл немного модифицированный код,который добавляет возможность загружать видеофайлы  прямо с компьютера,надеюсь автор тоже добавит такую функцию )))

**Comment by orangefunk** [comment]
Very good!  Yes will try this tonight!

**Comment by dstef81** [comment]
Hello, I've tried it and it worked! Although i didnt understand a word, its very easy to follow the images, just make sure to run the commands before the import.fastai step. 
Mr 7zip you are amazing. большое тебе спасибо !

**Comment by orangefunk** [comment]
Great!  Means I'm not blocked tonight :D

**Comment by Zzip7** [comment]
Очень приятно,что помог!Всем удачи!

**Comment by DavidEllisFilm** [comment]
> Очень приятно,что помог!Всем удачи!

Спасибо!
Можете ли вы разместить здесь свой код для загрузки видеофайлов прямо с компьютера?

**Comment by Zzip7** [comment]
Извините,ссылку не сохранил ((( Знаю,что,код начинается так:
from google.colab import files
uploaded = files.upload()

**Comment by orangefunk** [comment]
I tried for a few hours and the fix didn't seem to work with files I have put in Dropbox... 

![Screenshot 2021-07-21 at 00 47 51](https://user-images.githubusercontent.com/7872926/126407030-3d316f7e-3b6e-433a-bdc8-50dab90c41fd.png)

I am hoping there is a more general fix coming.  Otherwise I will have to look into hacking to get video files loaded from a directory on the host.

**Comment by Zzip7** [comment]
orangefunk  ты хочешь загрузить видео? Но, почему запускаешь  ImageColorizerColab.ipynb , вместо VideoColorizerColab.ipynb

**Comment by orangefunk** [comment]
Ahh maybe I went to the wrong project!  Thanks for being eagle eyed! I was using a new computer!

**Comment by orangefunk** [comment]
I'm still running into problems and I'm using the VideoColorizerColab.ipynb...  will try again later..

**Comment by orangefunk** [comment]
I think I found another way to get it to run.

If you find colab_requirements.txt in the Deoldify directory and remove the ffmpeg line (it will save after a few seconds) then it emulates what Zzip is doing previously.

mine says:

fastai==1.0.51
tensorboardX==1.6
ffmpeg-python==0.1.17
youtube-dl>=2019.4.17
opencv-python>=3.3.0.10
pillow
tornado~=5.1.0

**Comment by 1-0-1-0-1-0** [comment]
Hello! The Zzip7's solution works for me. I also tried the orangefunk's one, but I failed to accomplish this, I feel I need more precise step by step instructions on this. If somebody needs the English translation of the Russian lines, I can give it.
      Interesting, why the Colab version of DeOldify is so unstable. One day it works fine, the next day it gives out an error. Probably, the developers are updating the software. I have not found any official notice on the "No Attribute" issue. I am considering installing DeOldify into my machine, but it's current GPU has only two Gb of memory, whereas the recommended one is four to six Gb. Besides, I am just a PC user and I am not confident at all of whether I will be able to install this thing.

**Comment by orangefunk** [comment]
Did you look in the Deoldify folder and find the colab_requirements.txt? 

I modified that by taking away the ffmpeg line as I believe the ffmpeg-python library is a wrapper for it.
You have to make sure the file saves before running....  it seemed to autosave after 5 seconds
 I also made sure I reset the runtime before doing all this just so I knew it was all clean

<img width="416" alt="Screenshot 2021-07-21 at 23 26 00" src="https://user-images.githubusercontent.com/7872926/126562431-23a50913-5c7a-44be-874d-eb29dcdb5362.png">

**Comment by orangefunk** [comment]
Btw I too was thinking of installing the software locally on my 16GB Mac Mini M1.  The instructions I see are mostly linux based so I think it could be a good match.  I believe there is a need to install the training data though...  but I think you can run the same kind of scripts to get the data like it is in the Colab version of Deoldify.

**Comment by jantic** [comment]
Ok guys, really sorry about this bug in the colab_requirements.txt file! I just fixed it and it appears to be solved now. And thanks for doing all this hunting for me so I knew where to look!

@dstef81 I specifically tried your video in that screenshot but I get a separate error complaining that the video is private.  You'll run into the same issue unless you make it something other than private (I think unlisted should work).

**Comment by 1-0-1-0-1-0** [comment]
Thank you, thank you, thank you many, many times!!! What a great job!

**Comment by joannpav** [comment]
> Всем привет!Я вообще не программист,мучался 2 дня с такой же проблемой,но нашёл для себя решение.Даже на github зарегистрировался.Может кому поможет)))
> 
> 1. Файл - Сохранить копию на диске
> 2. После строки   !pip install -r colab_requirements.txt   добавить ОТДЕЛЬНЫХ 3 кода.
>    pip uninstall ffmpeg
>    pip uninstall ffmpeg-python
>    pip install ffmpeg-python
>    ![1](https://user-images.githubusercontent.com/87704893/126325084-2a096b0f-1bee-45b2-a3ce-81d617da5198.jpg)
> 
> 3.После подключения согласиться 2 раза на удаление "pip uninstall ffmpeg" и "pip uninstall ffmpeg-python" ![2](https://user-images.githubusercontent.com/87704893/126326228-bbe1cde9-62c4-4b12-a7a8-efc5fe719667.jpg) ![3](https://user-images.githubusercontent.com/87704893/126326254-71079d7d-7a53-4511-b847-ed28c5c99054.jpg)
> 
> 4.Установить "pip install ffmpeg-python" ![4](https://user-images.githubusercontent.com/87704893/126327012-cd08f83e-104c-4a74-a231-5d0c6661a09c.jpg)
> 
> 5.Дальше как обычно.
> 
> И ещё нашёл немного модифицированный код,который добавляет возможность загружать видеофайлы прямо с компьютера,надеюсь автор тоже добавит такую функцию )))

WOW, I do not know why this worked but it did, so thank you!
