### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by deepikagoel1** [jantic/DeOldify#366]
I tried to load the model on streamlit, please help me in doing it as it will be helpful for my research topic but facing some issues with it.

**Comment by jantic** [comment]
This request is beyond the scope of what we're supporting for this project. I've never used streamlit and this project wasn't designed with that in mind (not sure what's involved there). But more to the point- it's a personal  request for free remote debugging assistance on a specific and unique use case.  We just don't do that here.
