### ISSUE TITLE
Multi GPUs

### ISSUE THREAD

**Issue by FabianEnglbrecht** [jantic/DeOldify#367]
device_id.py allows accessing individual GPUs. Is it possible to use two GPUs in a bridged scenario, e.g. GPU0 + GPU1? Could not find a solution yet.

**Comment by jantic** [comment]
Are you talking about inference as opposed to training a model? If inference, then I have no ambitions/plans whatsoever to try make it multi-gpu.  That would add way too much complication for very little benefit- you can't really render images at much higher resolutions decently anyway that would merit throwing resources at this sort of approach.

If you're talking about training- I use multiple GPUs routinely in my day to day work, and based it on these instructions from fastai: [https://fastai1.fast.ai/distributed.html](https://fastai1.fast.ai/distributed.html) . If I do a model upgrade (not this year) for the open source project I'll most likely update the project with the scripting code I have but it's basically mostly based around what I liked to there. You have to go the additional mile of making sure that you're using synched batchnorm though, and GANs don't work out of the box with this stuff in fastai v1.

**Comment by FabianEnglbrecht** [comment]
Yes, I am just talking about the training. Thanks for the instructions and your help that should do the job. Btw, great work :)
