### ISSUE TITLE
How can I install DeOldify for local machine without online?

### ISSUE THREAD

**Issue by MartinEesmaa** [jantic/DeOldify#371]
Hey, guys! I need to know, how can I install DeOldify to my laptop for offline installation? Well, it's easy to download code ZIP, but I'm not sure what should I do now after code is downloaded and extracted files? I need encode my GPU, Google GPU is pretty slower than my 2021 GPU 6GB vRAM. Please... I'm not sure what to do.

- Martin Eesmaa

**Comment by jantic** [comment]
This is covered in the [Easy Install section](https://github.com/jantic/DeOldify#easy-install) of the readme.
