### ISSUE TITLE
I got error when I tried to test colorize image in Ubuntu 21.04.

### ISSUE THREAD

**Issue by MartinEesmaa** [jantic/DeOldify#374]
Hey! I am running Ubuntu latest version 21.04 for VMware Workstation Pro and I had NVIDIA driver. I just used to conda activate deoldify, then jupyter lab, then I chose ImageColonizer.ipynb, I ran all codes to colorize test image, but it came error like this:
---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-4-b4a391b5d01f> in <module>
      7 
      8 if source_url is not None:
----> 9     result_path = colorizer.plot_transformed_image_from_url(url=source_url, path=source_path, render_factor=render_factor, compare=True)
     10 else:
     11     result_path = colorizer.plot_transformed_image(path=source_path, render_factor=render_factor, compare=True)

~/Downloads/DeOldify/deoldify/visualize.py in plot_transformed_image_from_url(self, url, path, results_dir, figsize, render_factor, display_render_factor, compare, post_process, watermarked)
     80         watermarked: bool = True,
     81     ) -> Path:
---> 82         img = self._get_image_from_url(url)
     83         img.save(path)
     84         return self.plot_transformed_image(

~/Downloads/DeOldify/deoldify/visualize.py in _get_image_from_url(self, url)
     64     def _get_image_from_url(self, url: str) -> Image:
     65         response = requests.get(url, timeout=30, headers={'Accept': '*/*;q=0.8'})
---> 66         img = PIL.Image.open(BytesIO(response.content)).convert('RGB')
     67         return img
     68 

~/anaconda3/envs/deoldify/lib/python3.7/site-packages/PIL/Image.py in open(fp, mode, formats)
   2966         warnings.warn(message)
   2967     raise UnidentifiedImageError(
-> 2968         "cannot identify image file %r" % (filename if filename else fp)
   2969     )
   2970 

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f81c32c3110>

Here's the proof screenshot: 
![errorproblemofcolorize](https://user-images.githubusercontent.com/88035011/127756642-3a2aa2c0-3eba-4fb7-9a65-2b5e99f13582.png)

**Comment by jantic** [comment]
That's actually failing at the stage where it's trying to download the image and then read the results of the download as a PIL image. I tested the url itself and it's fine so this likely means you were having a connection issue with that url.  That could be internet access itself, or wikimedia was somehow down temporarily... or perhaps the site is some blocked for you (firewall?).  Did you check that on the vm? Perhaps try going to that URL specified in source_url in a browser.

**Comment by jantic** [comment]
Keep in mind too...even after you get past this point, I have serious doubts that this is going to actually render using GPU on the VM (there's another recent discussion on this).  CPU will be fine but slow AF. That's where you'll be on your own because that's beyond the scope of support here.

**Comment by MartinEesmaa** [comment]
Source file worked, but kernel crashed:
![kernelerror](https://user-images.githubusercontent.com/88035011/127757252-ae5b36ca-2da1-4e42-ac8e-5c5466e4b1ea.png)

**Comment by MartinEesmaa** [comment]
I guess I cannot run on Virtual machine

**Comment by jqueguiner** [comment]
you should look into passing through your nvidia card to the VMware station 

https://communities.vmware.com/t5/VMware-Workstation-Pro/Make-VMWare-Workstation-use-my-Nvidia-card/td-p/2751434
https://communities.vmware.com/t5/VMware-Workstation-Pro/GPU-not-recognized-utilized-in-Workstation-Pro-16/td-p/2819765

it's very likely that you don't have the GPU passed through to the VM.

Their are 2 ways to do it and to my knowledge only 1 is compatible with non-datacenter GPUcard:
1) either you virtualize the GPU
2) or pass it though directly to the VM

**Comment by jantic** [comment]
Thanks @jqueguiner .  Going to close this.
