### ISSUE TITLE
Notebook not working

### ISSUE THREAD

**Issue by srini8080** [jantic/DeOldify#378]
System with 8GB RAM and no GPU. I get this error

$sh quick_start.sh notebook 9876543

[W 03:52:35.090 NotebookApp] 403 POST /api (10.0.2.100): '_xsrf' argument missing from POST
[W 03:52:35.090 NotebookApp] '_xsrf' argument missing from POST
[W 03:52:35.091 NotebookApp] 403 POST /api (10.0.2.100) 1.44ms referer=None

curl -X POST "http://127.0.0.1:8888/api" -H "accept: image/png" -H "Content-Type: image/jpeg" -F "file=@123.jpeg" -F "render_factor=35" --output colorized_image.png

Anything I am doing wrong?

**Comment by jantic** [comment]
@srini8080  I'm not quite sure if you're trying to call a notebook from the docker api here- your deviating from the usage instructions in the readme. But you can't call .ipynb notebooks with the docker api like this if that's your intent.  

If you want to use the notebooks you'll want to do a normal jupyter run per instructions.
