### ISSUE TITLE
Awesome! But I have some badcase.

### ISSUE THREAD

**Issue by qinxiaoguang** [jantic/DeOldify#38]
This project is so awesome! I have tested several pictures, and the results are very good.
But There are some badcase.
First, as shown in the picture.Lei Feng -- a very famous figure in China，I use this picture to test your wonderful project, but the result turns out a little wrong. As i known ,the clothes Lei Feng dress should be green but in the result turns out blue. 
![3](https://user-images.githubusercontent.com/17332034/48389798-fdae2280-e739-11e8-8d77-1b7ed8547e03.jpg)
Second, as shown in the below picture,red scarf is a symbol of Chinese youth, but the little girl wears a blue scarf. Another point is that their hands are a bit scary（Blue,Dark）.😂
![1](https://user-images.githubusercontent.com/17332034/48389559-f2a6c280-e738-11e8-8082-cd7ddc3adf5e.jpg)
So are there any optimizition advices for these problems?
Looking forword to your reply~
Best wishes.
Thank you

**Comment by jantic** [comment]
I should add- your best bet to getting a better picture is to play around with the sz parameter. Can't go much above 500 if you have a 11GB GPU though.

**Comment by qinxiaoguang** [comment]
Thank you for your reply.I will test it with sz parameter and Im looking forword to the best version.
In addition, is there any way to set output colors if I know the colors of input picture?Just like the first picture, can I set the output colors like green、yellow except blue?If not , is it feasible to set output colors?

**Comment by jantic** [comment]
I'm sure it's feasible but I haven't figured out a way yet to specify/override colors.  The ambition is to have the user guide colors as an option but that's going to take some time to figure out.

**Comment by jantic** [comment]
This is no longer an issue with the upcoming release and it's still documented in the readme.  So going to close this.
