### ISSUE TITLE
C# implementation with GUI

### ISSUE THREAD

**Issue by GlebSBrykin** [jantic/DeOldify#381]
Hi, Jason! Apparently, there is a big request for Windows support and a graphical interface. I implemented the artistic DeOldify model in pure C# and made a simple graphical interface. The application can be run on Windows 7 and higher, and only requires .NET Framework. No Python, CUDA, etc. Only standard OS tools. The application is free and has an open source code. https://github.com/ColorfulSoft/DeOldify.NET

**Comment by jantic** [comment]
@GlebSBrykin  This is fantastic.  I gave it a spin locally and it strikes a great balance between optimization for the CPU and quality of output. It's super low barrier to entry as a result. And you've made the UI super simple which I like. You're right, people have been asking for this for ages.  I'll spread the word on Twitter and link to this on the readme.  Thank you so much!

![image](https://user-images.githubusercontent.com/179759/133360009-93e1d55b-5523-4346-b3f4-523180840452.png)

**Comment by jantic** [comment]
@GlebSBrykin I've been digging more into what you actually did here. I have to just emphasize that it's pretty impressive. This for example- 

[https://github.com/ColorfulSoft/DeOldify.NET/blob/main/Implementation/src/Functional.cs)](https://github.com/ColorfulSoft/DeOldify.NET/blob/main/Implementation/src/Functional.cs)

And this:

[https://github.com/ColorfulSoft/DeOldify.NET/blob/main/Implementation/src/HalfHelper.cs](https://github.com/ColorfulSoft/DeOldify.NET/blob/main/Implementation/src/HalfHelper.cs)

**Comment by GlebSBrykin** [comment]
Thank you for the high assessment of my work!
