### ISSUE TITLE
Change Video aspect ratio

### ISSUE THREAD

**Issue by bruntumber** [jantic/DeOldify#384]
Is there any way to change the aspect ratio of output video. The output size I get now is 640 X 360, I would like to change to 1920 X 1080. Is it possible? How would I do it? Thank you

**Comment by jantic** [comment]
That would be beyond the scope of what we're doing here. What the YouTube downloader logic does is it retrieves the best version available on the site with these options:  'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 and output a video that should reflect that quality (resolution/aspect ratio, etc)',  Similarly, if you're processing a local video, it'll do the same matching of quality as output.

I mean, you could run it through another program that specializes in video editing and artificially upscale the video to that 1920x1080 aspect ratio but it's not going to look any better if that's the intent. If you want to increase the actual video resolution, that would involve using super resolution methods such as those offered by  [Topaz Labs.](https://www.topazlabs.com/video-enhance-ai)
