### ISSUE TITLE
I made an auto installer for Ubuntu WSL!

### ISSUE THREAD

**Issue by daddyparodz** [jantic/DeOldify#385]
Hey! I don't think this is the right section, but I wanted to inform you and everyone else that I just finished making an automatic installer for DeOldify to make it run locally, working on Ubuntu. If you like go take a look, I'd love to. [Here's](https://github.com/daddyparodz/AutoDeOldifyLocal) the link.

**Comment by jantic** [comment]
Thanks! This is the sort of stuff that's highly appreciated.  I've added this to the readme as an alternative installation method.
