### ISSUE TITLE
curl local image not working

### ISSUE THREAD

**Issue by zcemycl** [jantic/DeOldify#388]
I tried curl with url and image separately. Only url returns me an image, the image method does not. 

```
curl -X POST "http://192.168.4.183:5000/process" -H "accept: image/png" -H "Content-Type: image/jpeg" -F "file=@/home/yui/DeOldify/test_images/slave-family-P.jpeg" -F "render_factor=35" --output colorized_image.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 192.168.4.183 port 5000: Connection refused
```

**Comment by jantic** [comment]
There's a lot of things that could be going on here. Not to offend but I don't have enough information to go by so I have to start with the basics that amount to "is your computer plugged in?" tech support:

1. Did you try these two commands (url and local image based) one after another on the same session?
2. Are you sure you typed the same exact IP Address both times?
3. Have you seen [this thread](https://stackoverflow.com/questions/41027340/curl-connection-refused)?

I'll have to assume this is purely a local issue as this stuff as been used for three years with this working fine so I'm going to close this and wish the best of luck to your debugging here.
