### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by jin0110** [jantic/DeOldify#391]
source_url= None
file_name = './test2'
file_name_ext = file_name + '.mp4'

File Load Error for test2.mp4
home/DeOldify-master/video/source/test2.mp4 is not UTF-8 encoded

I want to know what is the reason for the problem? How to solve it
In the coloring part of the picture, it can run normally, indicating that there is no error in the environment configuration. This problem occurs in the video coloring.  Thank you very much.

**Comment by jin0110** [comment]
#NOTE:  Max is 44 with 11GB video cards.  21 is a good default
render_factor=21
#NOTE:  Make source_url None to just read from file at ./video/source/[file_name] directly without modification
source_url= None
file_name = './test'
file_name_ext = file_name + '.mp4'
result_path = None

if source_url is not None:
    result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)
else:
    result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)

show_video_in_notebook(result_path)

**Comment by jantic** [comment]
Have you tried any other videos?  It does make me wonder if it's just that specific video that's having the issue.

**Comment by jin0110** [comment]
Thank you for your reply. There will be no problem after using Linux system. Sorry to bother you
