### ISSUE TITLE
How to also support AArch64 and ARM64 Processors (including Amazon AWS Graviton2)

### ISSUE THREAD

**Issue by Derek-2423** [jantic/DeOldify#394]
ARM processors (including AArch64, ARM64, and Amazon AWS Graviton2 as used in some Amazon EC2 instances) can also be supported via a simple tweak to the relevant Dockerfile. This is in addition to the default Intel and AMD support.

It turns out these are only supported by more recent nvidia/pytorch builds. So change the first line in Dockerfile[...]

<-- From nvcr.io/nvidia/pytorch:19.04-py3
--> From nvcr.io/nvidia/pytorch:21.10-py3

Also we were given a prompt for tzdata during the build that could not be entered, so (if you get that) in the same Dockerfile[...] change

<-- RUN apt-get -y update && apt-get install -y \\
--> RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q \\

**Comment by jantic** [comment]
This is certainly helpful to have documented in the project so this is much appreciated! Unfortunately I'm not in the position to fully test this at this time and I know others are using this Docker deployment commercially. So I'll leave the code as is for now to keep it stable until this can be tested. @jqueguiner  fyi.
