### ISSUE TITLE
To anyone who would like to see a CLI for DeOldify...

### ISSUE THREAD

**Issue by KeygenLLC** [jantic/DeOldify#395]
In reference to #389 posted by @eadmaster

I'm considering releasing some CLI scripts in the future as I've already (mostly) developed them for use in production at my company. It does not require jupyter lab to be running at all. You just call the script in the Terminal and it runs and gives you feedback while processing the files, it batches files, and batches render_factor.

Currently, I'm launching it from a socket server, but I can easily modify the code to have it also run in standalone with flags in the command line. Doing this requires modifying some of the core files though and not just the single script that fires up DeOldify, so it would require you to edit functions, add chunks of code, or overwrite the files that are in sub-directories. Sorry, but I don't have the time or desire to maintain a fork.

If anyone else thinks this would be useful to them, up-vote this post or comment below—you can also mention what models you would like to see work like this—so I can decide if it's worth the time to code and package everything up in the future once my project has been released and has had some time to gain traction.

It will also take time to properly test and debug it and a clean install of DeOldify as I think I broke the training in the process, but didn't give a shit since I didn't need it 🤭😬

Bear in mind that I only work on macOS currently, have no way to test on other platforms, and will not be providing support for the tools—though I would provide brief installation instructions and a breakdown of how to use them. I also use other dependencies you will need to install for it to function and an `.env` file, unless I strip that out of it. It should work on Linux just fine, but no idea about Windows or CUDA.

I've already discussed this with @jantic and he's cool with it, so pester me about it instead of him from now on if you really desire a command line tool. 😉 It won't be at least for several months, but during that time, I can gauge whether or not it's worth _mine_ to do this.

Feel free to close this post as anyone who wants this will probably search for it anyway.

### Sneak Peak:
<img width="682" alt="DeOldify_NewIfied" src="https://user-images.githubusercontent.com/92394639/143325113-21d23ba4-00c1-4a65-bc4a-24b3c2c5d138.png">

**Comment by jantic** [comment]
Thanks @KeygenLLC !

**Comment by eadmaster** [comment]
You may just upload your code into a branch here, a separate project if you prefer.

I will test this on Ubuntu Linux.

**Comment by mlubak** [comment]
Definitely would like this tool

**Comment by 0x41mmarVM** [comment]
Would love to have this for sure :)

**Comment by harisreedhar** [comment]
I made a single python file to run deoldify through CLI. Just copy [run_local.py](https://github.com/harisreedhar/DeOldify/blob/run-local/run_local.py) to the root directory and run:
````
python run_local.py --input ./test_images/1.jpg --output ./test_images/ --model artistic
````
N.B. only tested on linux
