### ISSUE TITLE
Possible syntax errors in some files

### ISSUE THREAD

**Issue by KeygenLLC** [jantic/DeOldify#396]
Might have found a few syntax errors and such in the code while I was modifying things after I installed Pylance. Some I could fix, some I'm not sure how to approach.

apputils.py
---
compress_image function
line26

```python
image = image.resize((width,height), PIL.Image.ANTIALIAS)
```
I believe PIL should not be there and just `Image.ANTIALIAS` would be correct. This would then match similar code on line 31. 

deoldify > filters.py
---
Getting warnings about `Learner`. No idea what to do with this.
line 24, line 73
```python
# Warning: Learner is not defined
class ColorizerFilter(BaseFilter):
    def __init__(self, learn: Learner, stats: tuple = imagenet_stats):
        super().__init__(learn=learn, stats=stats)
        self.render_base = 16

# Warning: Learner is not defined
class BaseFilter(IFilter):
    def __init__(self, learn: Learner, stats: tuple = imagenet_stats):
        super().__init__()
        self.learn = learn
        self.device = next(self.learn.model.parameters()).device
        self.norm, self.denorm = normalize_funcs(*stats)
```
_model_process function
line 53
I tracked this down in a Github issue. `DatasetType` seems to have been removed from fast.ai 2, but this is fast.ai 1. I have fast.ai 1.0.51 as it is listed in requirements.txt. Maybe you're using the new syntax instead of the old?
```python
# Warning: DatasetType is not defined
# ....
        try:
            result = self.learn.pred_batch(
                ds_type=DatasetType.Valid, batch=(x[None], y[None]), reconstruct=True
            )
```
Master_Filter
Seems to be an incorrect annotation. Removing the brackets seems to work. Let me know if this is correct.
```python
# Warning: List expression not allowed in type annotation "[IFilter]"
# Use List[T] to indicate a list type or Union[T1, T2] to indicate a union type
class MasterFilter(BaseFilter):
    def __init__(self, filters: [IFilter], render_factor: int):
        self.filters = filters
        self.render_factor = render_factor
```
deoldify > visualize.py
---
5 annotation warnings for `(int, int)`.
Changing these to `typing.Tuple[int, int]` seems to fix it.
```python
# Warning: Tuple expression not allowed in type annotation
# Use Tuple[T1, ..., Tn] to indicate a tuple type or Union[T1, T2] to indicate a union type
def plot_transformed_image_from_url(
        self,
        url: str,
        path: str = 'test_images/image.png',
        results_dir:Path = None,
        figsize: (int, int) = (20, 20), # <-------------------
        render_factor: int = None,
```
_clean_mem
line 57
fixed this by adding `import torch`. not sure if this is needed if your code somehow finds torch at runtime?? 
```python
#Warning: torch is not defined
    def _clean_mem(self):
        torch.cuda.empty_cache()
        # gc.collect()
```
_open_pil_image, _get_image_from_url
line 62, line 66
PIL is probably not needed since you're importing `Image` can just use `Image.open`. I replaced this with another module for reading files, so didn't test it.
```python
#Warning: PIL is not defined
    def _open_pil_image(self, path: Path) -> Image:
        return PIL.Image.open(path).convert('RGB')

    def _get_image_from_url(self, url: str) -> Image:
        response = requests.get(url, timeout=30, headers={'Accept': '*/*;q=0.8'})
        img = PIL.Image.open(BytesIO(response.content)).convert('RGB')
        return img

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jantic** [comment]
Hey @KeygenLLC , you were totally right.  That was some seriously sloppy and embarrassing code on my part and I'm surprised it hadn't been pointed out sooner.  I've committed fixes not only for what you pointed out but also some sloppiness  in other files as well.

**Comment by KeygenLLC** [comment]
No worries man. Just wanted to bring it to your attention. I'll look for the changes when I have a chance.
