### ISSUE TITLE
NoGan training.

### ISSUE THREAD

**Issue by HibiVixx** [jantic/DeOldify#398]
would it be possible to make a video explaining how to do a "Nogan" training on the Jupyter notebook, to improve the final result of the colorized videos?  I'm a bit of a layman with this so I didn't understand the explanation on the page at all, and besides, I'm Brazilian I have more difficulty because of the language

**Comment by jantic** [comment]
I won't be doing a video (camera shy and whatnot) but here's a blog that hopefully explains it better:  [blog](https://www.fast.ai/2019/05/03/decrappify/) .

My ultimate suggestion, however, is to simply follow the ColorizeTrainingVideo.ipynb notebook step by step.  It may be tedious to do so but it's also showing exactly what is being done.
