### ISSUE TITLE
No module named 'fastai.transforms'

### ISSUE THREAD

**Issue by levin-kelevra** [jantic/DeOldify#4]
`ModuleNotFoundError`                       Traceback (most recent call last)
<ipython-input-11-9e750ee0ffa5> in <module>
      2 import os
      3 from torch import autograd
----> 4 from fastai.transforms import TfmType
      5 from fasterai.transforms import *
      6 from fastai.conv_learner import *

ModuleNotFoundError: No module named 'fastai.transforms'
`

**Comment by jantic** [comment]
You'll need fast.ai.  Probably should just download from here for now:  https://github.com/jantic/fastai
