### ISSUE TITLE
Create install/guidance for cpu rendering

### ISSUE THREAD

**Issue by jantic** [jantic/DeOldify#40]
CPU rendering is desirable to get around the limitations of memory in GPUs when wanting to render at high quality.  Additionally, of course- not everybody has a GPU with a decent amount of memory.  This issue will track creating both an install and instructions/best practices for CPU rendering.

**Comment by Ichaelus** [comment]
Some hints for those trying to execute your (awesome :heart_eyes: ) piece of software without a Cuda-supporting GPU:

In ColorizeVisualization.ipynb
- Remove the line `torch.cuda.set_device(0)`, since you don't use cuda
- Remove the line `"IMAGENET = Path('data/imagenet/ILSVRC/Data/CLS-LOC/train')\n",`
- Modify the following to `"colorizer_path = 'colorize_gen_192.h5'\n",`

In DeFadeVisualization.ipynb
- Replace all `.cuda(gpu)` calls with `.cpu()`

Bonus, if you want to transform an entire input folder (e.g. called "input_images"):
```python
    "import os\n",
    "for subdir, dirs, files in os.walk('input_images'):\n",
    "    for file in files:\n",
    "        vis.plot_transformed_image(os.path.join(subdir, file))"
```
For this, you might also want to patch fastai, since it does keep the figures in memory which will eventually cause you to run out of memory.

In fasterai/visualize.py:37
- Add `plt.close(fig)`

Cheers, Ichaelus

**Comment by jantic** [comment]
Thanks!  This will be a good reference before I try to programmatically support this stuff.

The plt.close(fig) thing in particular- great catch. I'll look at fixing that today.

Did you use the pytorch-cpu install for this?  That was the only way I got it working at a reasonable speed (it's a PITA to have a separate install just for cpu though).  For rendering mind you (don't try to train with CPU!)  And by reasonable I mean slow as fuck but not infinitely slow (like maybe a minute or two for some renders on a 16 core threadripper lol).

`conda install -c pytorch pytorch-cpu `

**Comment by jantic** [comment]
Also- ultimately if you're just interested in rendering with pretrained weights, I strongly recommend to just use the Colab notebook.  They give you a free 11GB (!!!) gpu and it's as hassle free as you can get right now.  Though I do understand it's nice to just have it on your own machine and do whatever you want with it.

**Comment by jantic** [comment]
Update on the plt.close(fig) thing- It turns out that if you close the figure, it makes the image disappear in Juptyer (doh!). Currently at least- I'm sure there's a way around it.  I do wonder if it's worth trying to address it though.  I suppose if somebody is doing a huge batch then yeah...problem.   But then really should they be plotting to matplotlib to begin with...(and therefore the plot_transformed_image function)?  Sounds like it should just be going straight to file, because it'd also be problematic to load up Jupyter with tons of images (I've tried...it doesn't like it).

I'm going to let this go for now unless I hear of concrete problems with this that convince me it needs to be changed.  #TradeOffs and whatnot.

**Comment by Ichaelus** [comment]
Hi again!

Yes, I followed your installation guide and chose "CPU" whenever possible :wink: That said, I am launching the application with `conda activate fastai-cpu && jupyter notebook`. The render speed is not _that_ regarding the possible outcome. Yesterday, I went over to creating colorizations for 8 different render factors per image to spot the right one (which is by far not always the highest possible render factor!), and it takes me about 1-2 minutes per batch (of 8). The bottleneck of choosing higher render factors was rather my 16GB of RAM than the Coffee Lake CPU. Code see Appendinx.

Colab/Jupyter and all this was new to me, so I felt more comfortable having all set up locally at first. 

That's a good point with mathplotlib, I always went straight to the result_images directory to see the images and didn't mind the plotted figure :) 

---
Appendix: Code to create multiple versions of the input image. I needed to patch the underlying method to create different output images, though.

```python
import os
for subdir, dirs, files in os.walk('input_images'):
    for file in files:
        print(file)
        for render_factor in [6, 12, 18, 24, 30, 36, 42, 48]:
            new_path = os.path.join(subdir, file)
            vis.plot_transformed_image(new_path, render_factor=render_factor)
```

**Comment by Hyfred** [comment]
I have a problem fou you. I follow your guidance. Everything went successful until this step:
![image](https://user-images.githubusercontent.com/38806779/49910687-a0cf9480-febe-11e8-8150-85c6e4cb04e6.png)
![image](https://user-images.githubusercontent.com/38806779/49910688-a0cf9480-febe-11e8-99a1-fb58796c4437.png)
Hope get your help, thanks!!

**Comment by Hyfred** [comment]
I have a problem fou you. I follow your guidance. Everything went successful until this step:
![image](https://user-images.githubusercontent.com/38806779/49910801-0cb1fd00-febf-11e8-9791-744ef42bedcd.png)
![image](https://user-images.githubusercontent.com/38806779/49910806-120f4780-febf-11e8-988c-692e5294c79a.png)
Hope get your help, thanks!!

**Comment by jantic** [comment]
So what are you attempting to do here- gpu or cpu rendering?

**Comment by jantic** [comment]
You might have to do this 

`conda remove pytorch `

then 

`conda install -c pytorch=0.4.1 pytorch-cpu=0.4.1` 

I -think- the second command will work but haven't tried it.

I say that because it's complaining about CUDA, yet CUDA is only relevant to GPUs.  And it shouldn't even get to this point unless something's screwed up with the pytorch-cpu install.

**Comment by jantic** [comment]
I'm going to close this.  It's not actually worth it if you have a gpu (almost everybody does these days) and there's a Colab notebook that provides the hardware if you don't have it.
