### ISSUE TITLE
colorizer = get_video_colorizer()

### ISSUE THREAD

**Issue by onlymaureen** [jantic/DeOldify#400]
Getting an error message while running. Tried a few video sources, all stuck at the same spot. What did I do wrong? 
==============================
colorizer = get_video_colorizer()

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-42-81c07a854ecc> in <module>()
----> 1 colorizer = get_video_colorizer()

5 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    775             "functionality.")
    776 
--> 777     magic_number = pickle_module.load(f, **pickle_load_args)
    778     if magic_number != MAGIC_NUMBER:
    779         raise RuntimeError("Invalid magic number; corrupt file?")

EOFError: Ran out of input

**Comment by jantic** [comment]
@onlymaureen This appears to be a case of having not successfully downloaded the model weights correctly to /models/ColorizeVideo_gen.pth .  I'd delete the existing ColorizeVideo_gen.pth and reattempt the download from here:  https://data.deepai.org/deoldify/ColorizeVideo_gen.pth .  The file size should end up being 853,581 KB .
