### ISSUE TITLE
UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f84be4c1fb0>

### ISSUE THREAD

**Issue by IveMalfunctioned** [jantic/DeOldify#401]
On both the artistic and stable Google Colab pages for DeOldify single image, I get this error
---------------------------------------------------------------------------

UnidentifiedImageError                    Traceback (most recent call last)

<ipython-input-9-6f775ab8d621> in <module>()
      4 
      5 if source_url is not None and source_url !='':
----> 6     image_path = colorizer.plot_transformed_image_from_url(url=source_url, render_factor=render_factor, compare=True, watermarked=watermarked)
      7     show_image_in_notebook(image_path)
      8 else:

2 frames

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2894         warnings.warn(message)
   2895     raise UnidentifiedImageError(
-> 2896         "cannot identify image file %r" % (filename if filename else fp)
   2897     )
   2898 

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f84be4c1fb0>

**Comment by jantic** [comment]
@IveMalfunctioned  Thanks for bringing this to my attention. I've committed a fix and you should be good to go. I noticed the problem in imgur links myself- not sure where you were seeing it. Let me know if you still see an issue.
