### ISSUE TITLE
How to do batch processing? 

### ISSUE THREAD

**Issue by noonesperfect** [jantic/DeOldify#403]
Hello , I am quiet new over here and not much familiar with github, but I am trying to do batch processing  using 

https://colab.research.google.com/github/olaviinha/NeuralImageColorization/blob/master/DeOldify_ImageColorization.ipynb

As i mount "input_dir" as https://drive.google.com/drive/folders/14X5sMmC3pecXYxZIRL9vPYayCayv8IQ9?usp=sharing and
"output_dir" as https://drive.google.com/drive/folders/1Zqmj9Zx0ILl5PSR-GqVK54cL7A2T4Vi9?usp=sharing 
It shows following error 
AttributeError                            Traceback (most recent call last)

<ipython-input-19-0f3ef21ab60c> in <module>()
     12 count = len(pictures)
     13 
---> 14 op(c.title2, 'Coloring '+str(count)+' images.\n')
     15 for i, pic in enumerate(pictures):
     16   index = i+1

AttributeError: type object 'c' has no attribute 'title2'

Kindly help, how to work on this for batch processing images. Thannks

**Comment by jantic** [comment]
Looks like you found the help you needed [here in the correct project](https://github.com/olaviinha/NeuralImageColorization/issues/1) as this notebook isn't actually part of the DeOldify project.  

Closing.
