### ISSUE TITLE
GPU Issue RTX 30 Series

### ISSUE THREAD

**Issue by mlubak** [jantic/DeOldify#404]
First off, Love the software. I Use it all the time. Love old movies, not a fan of black and white. Anyways, I have a Dell computer that came with a 2060 super. I originally installed Deoldify on it with Ubuntu 20.04 LTS. Worked great. Decided I wanted to also use windows, so, changed the machine to Windows 11 with WSL2, and it also works great. I was able to purchase a 3060TI graphics card with more memory, so I upgraded the the machine. The graphic card work perfectly on the windows side. In the Jupiter notebook, print(torch.cuda.is_available()) - returns True, but running the colorizer returns CUDA error: no kernal image is available for execution on the device. I also tried the same card in my Linux machine, and same result. Nvidia-smi returns Driver Version: 51.39.01 Cuda Version 11.6. What am I doing wrong ? Is their a way to get this GPU card working ?

As another aside, I have a gaming laptop that has a 3060 super in it. Same issue. I have looked through other Issue answers, and have seen somethings tried, but wanted to see if there were any other clear steps to solving the problem before I try some things and hose up my system. I'm not exactly a newbie, but nowhere near an expert.

Thanks for any help, and thanks for this amazing software !

**Comment by LoneWarrior7** [comment]
I stumbled across Deoldify just 10 minutes ago so I have no idea about how you could solve the problem. I was wondering if a mobile 3060 super exists.

**Comment by jantic** [comment]
DeOldify uses an older version of PyTorch that only supports CUDA 10 or 9. That CUDA version result you're getting (11.,6) seems likely to be the problem. So try going with CUDA 10. I'm not sure how you're installing all this but it sounds like you may not be using the Anaconda install. I'd suggest sticking with that.

**Comment by mlubak** [comment]
I did the Anaconda install. Same issue with Version 10, so I upgraded the Cuda to 11 thinking that may help. Any other things I might try ? I just tried swapping the card in my machine that had the 2060 super, and had they same issue. For some reason, it doesn't like the 20 series. Any other thoughts on something I could try ?

**Comment by mlubak** [comment]
Sorry meant it doesn't like the RTX 30 series.

**Comment by jantic** [comment]
I honestly don't know what's going on then- there's a lot of potential ways you could be getting to this problem it appears. I think your best bet may be to reference this thread and see if you can get things working with the suggestions here.  [https://github.com/pytorch/pytorch/issues/31285](https://github.com/pytorch/pytorch/issues/31285)
