### ISSUE TITLE
Pillow error on Docker api build

### ISSUE THREAD

**Issue by dcaud** [jantic/DeOldify#405]
Reprex:

```
git clone https://github.com/jantic/DeOldify.git DeOldify
cd DeOldify && docker build -t deoldify_api -f Dockerfile-api .
```

Causes:

> Collecting pillow==9.0.0 (from -r requirements.txt (line 8))
>   Could not find a version that satisfies the requirement pillow==9.0.0 (from -r requirements.txt (line 8)) (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.8.2, 2.9.0, 3.0.0, 3.1.0rc1, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 5.4.1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.2.2, 7.0.0, 7.1.0, 7.1.1, 7.1.2, 7.2.0, 8.0.0, 8.0.1, 8.1.0, 8.1.1, 8.1.2, 8.2.0, 8.3.0, 8.3.1, 8.3.2, 8.4.0)
> No matching distribution found for pillow==9.0.0 (from -r requirements.txt (line 8))
> The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

Is a solution to change "pillow==9.0.0" to merely "pillow" in requirements.txt?

**Comment by jantic** [comment]
The available options are listed there and for some reason they don't go past 8.4.0. I'm not going to try to hunt this down as it's not critical so instead I've made a simple change to the requirements.txt file that should resolve this. Can you try again?
