### ISSUE TITLE
single command tool..

### ISSUE THREAD

**Issue by Herzbergh** [jantic/DeOldify#408]
Hey can you please make DeOldify workable as a single command tool?
I cant get enough of DeOldify but its not okay to force users to run a server to use it. I just want to colorize images.. 
best,

**Comment by jantic** [comment]
There's already an open issue about this actually:  https://github.com/jantic/DeOldify/issues/395 .

It's beyond the scope of what this project is for (sharing research- it's not a product)- but there are others on the case.
