### ISSUE TITLE
The link to download stable model is dead

### ISSUE THREAD

**Issue by mhoangvslev** [jantic/DeOldify#409]

**Comment by mbbrodie** [comment]
Same issue here -- can't download the stable model

**Comment by jantic** [comment]
Not sure what you guys ran into exactly (temporary issue?) but it's working currently.  This command definitely works (in case you were trying something else):

`wget https://www.dropbox.com/s/usf7uifrctqw9rl/ColorizeStable_gen.pth?dl=0 -O ./models/ColorizeStable_gen.pth`
