### ISSUE TITLE
python app.py not use my GPU

### ISSUE THREAD

**Issue by wonder2025** [jantic/DeOldify#410]
I curl the api ,it can return correct result , but it cost about 3s per request,
then,I found it dose not use the GPU ,how can I accelerate the  inference ?

**Comment by jantic** [comment]
@wonder2025 You'd have to be specifically using nvidia-docker with a supported Nvidia GPU installed, on Linux. There's instructions for this on the readme. Still to this day is only supported on Linux. There's Windows 11 with WSL but that's where you'd be on your own.  

Apparently it's now called Nvidia Container Toolkit.
