### ISSUE TITLE
Slow API? Is GPU working?

### ISSUE THREAD

**Issue by dcaud** [jantic/DeOldify#412]
On ubuntu 18 I can get the API to work, but it seems slow and I am not sure the GPU is configured correctly. The following API call takes ~35 seconds to process (with 1 x NVIDIA Tesla T4, and 2 CPUs and 8GB of RAM):

```curl -X POST "http://MY_SUPER_API_IP:5000/process" -H "accept: image/png" -H "Content-Type: application/json" -d "{\"url\":\"http://www.afrikanheritage.com/wp-content/uploads/2015/08/slave-family-P.jpeg\", \"render_factor\":35}" --output colorized_image.png```

After configuring the OS to recognize the GPU, I run:

`cd DeOldify && ./quick_start.sh image_api`

which returns the below that includes "nvidia card found running on GPU":

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 495.46       Driver Version: 495.46       CUDA Version: 11.5     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
> | N/A   53C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> nvidia card found running on GPU
> Docker started from cache
> Access your image_api on port 5000 (api) or 8888 (notebook)

However, the messages also contain the below which includes "WARNING: The NVIDIA Driver was not detected. ":

```
=============
== PyTorch ==
=============
NVIDIA Release 19.04 (build 6089340)
PyTorch Version 1.1.0a0+9eb0f43
....

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.
WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .
NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.
NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --ipc=host ...
/opt/conda/lib/python3.6/site-packages/fastai/data_block.py:442: UserWarning: Your training set is empty. If this is by design, pass `ignore_empty=True` to
 remove this warning.
  warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
/opt/conda/lib/python3.6/site-packages/fastai/data_block.py:445: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  or pass `ignore_empty=True` when labelling to remove this warning.""")
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

Is the GPU working as expected? Should the example file take 35 second to process on the machine specs I gave above?

**Comment by jantic** [comment]
This isn't working as expected- you should be getting much faster results. It's saying this which makes me wonder:

```
WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .
```

Do you have that installed? And this is a native instance of Ubuntu as opposed to hosted on say WSL or a virtual machine?

**Comment by dcaud** [comment]
Yes, that line contradicts the other line about GPU: "nvidia card found running on GPU."

I believe I instead the NVIDIA Driver and was able to test that it was connected and no jobs were running on it. But now I can't figure out how to test that again. Do you know of another way to test this? I wonder whether the driver I installed didn't "pass thru" to docker?

I tried this on a Google Cloud VM with Ubuntu. Is that a route know to fail?

**Comment by tonybarnhill** [comment]
@dcaud Perhaps my thread might help? I was having a similar issue.

https://github.com/jantic/DeOldify/issues/364

**Comment by jantic** [comment]
@dcaud I'm pretty sure @tonybarnhill is pointing you in the right direction there. Please let me know if that helps.
