### ISSUE TITLE
[HELP PLEASE] :  FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Lamin3** [jantic/DeOldify#413]
Hello everybody,
First of all, thank you very much for making and contributing to DeOldify. [Disclaimer] I don't have much knowelge in coding
**Long Version:**
> Okay so i wanted to run Deoldify on my PC, i've followed a tutorial in YT, downloaded "Anaconda3-2021.11" (using Python 3.7.12), i downloaded the zip from github, unzipped it, created a folder called "models" and i putted the file i downloaded "ColorizerVideo.gen.pth"  and then using Anaconda prompt i defined the right folder where i unzipped the DeOldify.zip, executed the command " conda env create -f environement.yml " ,  once finished, i used the command " conda activate deoldify " then " jupyter lab ". I ran the scripts one by one and in the order, at the end when i ran the last cell (Colorize!!) i got a bunch of errors.

**Short version:** 
In my jupyter notebook, i run the cells, everything is okay but i'm getting a bunch of errors when i run the last cell (Colorize!!)

```
`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11552\470958204.py in <module>
     10     result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)
     11 else:
---> 12     result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)
     13 
     14 show_video_in_notebook(result_path)

D:\DeOldify-master\deoldify\visualize.py in colorize_from_file_name(self, file_name, render_factor, watermarked, post_process)
    342         source_path = self.source_folder / file_name
    343         return self._colorize_from_path(
--> 344             source_path, render_factor=render_factor,  post_process=post_process,watermarked=watermarked
    345         )
    346 

D:\DeOldify-master\deoldify\visualize.py in _colorize_from_path(self, source_path, render_factor, watermarked, post_process)
    352                 'Video at path specfied, ' + str(source_path) + ' could not be found.'
    353             )
--> 354         self._extract_raw_frames(source_path)
    355         self._colorize_raw_frames(
    356             source_path, render_factor=render_factor,post_process=post_process,watermarked=watermarked

D:\DeOldify-master\deoldify\visualize.py in _extract_raw_frames(self, source_path)
    252         ffmpeg.input(str(source_path)).output(
    253             str(bwframe_path_template), format='image2', vcodec='mjpeg', qscale=0
--> 254         ).run(capture_stdout=True)
    255 
    256     def _colorize_raw_frames(

D:\PhytonAnaconda\envs\deoldify\lib\site-packages\ffmpeg\_run.py in run(stream_spec, cmd, capture_stdout, capture_stderr, input, quiet, overwrite_output)
    318         pipe_stderr=capture_stderr,
    319         quiet=quiet,
--> 320         overwrite_output=overwrite_output,
    321     )
    322     out, err = process.communicate(input)

D:\PhytonAnaconda\envs\deoldify\lib\site-packages\ffmpeg\_run.py in run_async(stream_spec, cmd, pipe_stdin, pipe_stdout, pipe_stderr, quiet, overwrite_output)
    283     stderr_stream = subprocess.PIPE if pipe_stderr or quiet else None
    284     return subprocess.Popen(
--> 285         args, stdin=stdin_stream, stdout=stdout_stream, stderr=stderr_stream
    286     )
    287 

D:\PhytonAnaconda\envs\deoldify\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

D:\PhytonAnaconda\envs\deoldify\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable`
```

Additional infos: 
I'm on Windows 10 home edition
When installing Anaconda i changed the default folder (c:), it's installed it in another disc.

Please help !

**Comment by jantic** [comment]
Unfortunately Windows is not supported for DeOldify.

**Comment by Lamin3** [comment]
But in that tutorial, that guy were running it on Windows, is it normal Jason ?

Here is the video: https://youtu.be/NA0GfR3zwb0

**Comment by jantic** [comment]
To clarify: Windows is not supported in terms of what I'm willing to help out with. Reason being is that when this project was set up a few years ago, the underlying libraries that were crucial only supported Linux. Things have changed since then but in order to properly bring up everything to speed so that Windows is properly supported I'd basically have to do a bunch of code updates and testing of what's already up- not only for running it but the training code as well. And then I'd have to support the resulting questions around it because inevitably as there would be more configurations to support, there would be more things to fail for users. 

That all being said it's possible to hack in Windows support and you can find that discussed in the issues here in the past. But I'm not going to try to help people debug that. I don't work for free and have better things to do, basically.

**Comment by Lamin3** [comment]
I understand and that's fair enough.

Just a last question; If i install Ubuntu (let's say v20.05) with Linux Kernel 5, would it work and avoid the windows instability ? (i also have RTX 3060ti)

**Comment by jantic** [comment]
Yeah you should be fine with that.

**Comment by Lamin3** [comment]
Alright. Thank you Jason and sorry if i took some of your time.
I will update this thread once i install Ubuntu, and tell you if it worked.

**Comment by Lamin3** [comment]
> Yeah you should be fine with that.

Hello again =) that was long lol but yes It worked ! i just tried it today with an online video hosted on Youtube. Thank you Jason. 
I'm totally noob on Ubuntu so it may be a stupid question but i'm really stucking on it, i would like to know if possible what's the way to put a local video/image, i don't know if i'm wrong but i just pasted the path file on the URL, like in this example: 

`source_url = ''/home/MyNickname/Downloads/Video001.mp4"
render_factor = 21  #@param {type: "slider", min: 5, max: 40}
watermarked = True #@param {type:"boolean"}

if source_url is not None and source_url !='':
    video_path = colorizer.colorize_from_url(source_url, 'video.mp4', render_factor, watermarked=watermarked)
    show_video_in_notebook(video_path)
else:
    print('Provide a video url and try again.')`

And i get an error saying that it's not a valid youtube link.
I also tried to drag & drop the video in a new tab of mozilla so i got a path like " File:///home/MyNickname/Dektop/Video001.mp4 " that i pasted on the source_url but i got the same issue.

If somebody can help it would be cool.

**Comment by Lamin3** [comment]
*** UPDATE ***

I've run it in local, it worked somehow, i got the video colorized and i also had the same error code "[WinError 2] The system cannot find the specified file " at the end of the process. 
But i think i barely know from where the issue is coming from ; **The audio encoding.**
So the issue occur when it's encoding the audio. 
Here is the lines of the processing:

```
Colorizing frame 4791 of 4791
Transferring audio
ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with clang version 14.0.6
  configuration: --prefix=/d/bld/ffmpeg_1660921618181/_h_env/Library --cc=clang.exe --cxx=clang++.exe --nm=llvm-nm --ar=llvm-ar --disable-doc --disable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libfontconfig --enable-libopenh264 --ld=lld-link --target-os=win64 --enable-cross-compile --toolchain=msvc --host-cc=clang.exe --extra-libs=ucrt.lib --extra-libs=vcruntime.lib --extra-libs=oldnames.lib --strip=llvm-strip --disable-stripping --host-extralibs= --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --pkg-config=/d/bld/ffmpeg_1660921618181/_build_env/Library/bin/pkg-config
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './test_images/02.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2022-08-19T21:08:27.000000Z
  Duration: 00:03:19.85, start: 0.000000, bitrate: 20763 kb/s
  Stream #0:0[0x1](eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1920x1036 [SAR 1:1 DAR 480:259], 20444 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      creation_time   : 2022-08-19T21:08:27.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2022-08-19T21:08:27.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
./test_images/temp_30a3f856b36441fd91fc3a5d1615add4.mp3: No such file or directory
Traceback (most recent call last):
  File "D:\DeOldify\run_local.py", line 137, in <module>
    model.colorize_video(args)
  File "D:\DeOldify\run_local.py", line 102, in colorize_video
    os.remove(tempAudio)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: './test_images/temp_30a3f856b36441fd91fc3a5d1615add4.mp3'
```

NB: it still work because in the output folder i still get the "no_audio" colorized video version.
