### ISSUE TITLE
not able to find data/imagenet/ILSVRC/Data/CLS-LOC and bandw

### ISSUE THREAD

**Issue by uchyouko** [jantic/DeOldify#414]
hello, I want to train this model on my own and I have downloaded the Imagenet 2012. But I can’t find the path “ data/imagenet/ILSVRC/Data/CLS-LOC” and “bandw”, how can I find this?
And can you tell me the formatting requirements for the dataset?
Thanks a lot！

**Comment by jantic** [comment]
The bandw folder is generated by the create_training_images function in the "ColorizeTraining" notebooks.

The expected folder format is just that there's a train and val folder in whatever your path winds up being there for "path" in the notebook. You don't have any additional requirements for the formatting of the data, as there isn't any additional information needed other than the images themselves. So just take the imagenet data as is.
