### ISSUE TITLE
UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fb589672ad0>

### ISSUE THREAD

**Issue by Sorcerer14** [jantic/DeOldify#415]
**When trying to colorize the image, I'm getting this error**
`raise UnidentifiedImageError(
         "cannot identify image file %r" % (filename if filename else fp)
  )`

**Expanding it further will provide the error in** **/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in open(fp, mode)**

**Comment by jantic** [comment]
It seems to be complaining that the file being pointed to isn't actually an image or an image type that PIL can open.  What's the image you're trying to use?

**Comment by Sorcerer14** [comment]
I'm pretty sure its regular jpeg image downloaded from picsart, I tried it out with the png format but no success.

Just asking, Does the initial resolution of image also matters?

**Comment by jantic** [comment]
Can you give the exact url of the image you used for this?

Initial resolution doesn't matter.

**Comment by Sorcerer14** [comment]
Sure here you go :
This one is in png format
![PngItem_1908805](https://user-images.githubusercontent.com/83954824/162180034-68efb045-7e4a-4c6c-ab0d-aa3afd3c4a14.png)

and this one in jpeg
![1209385](https://user-images.githubusercontent.com/83954824/162180061-0dcec091-d2c7-4bf1-bb2b-fa5c44c31bcb.jpg)
)

**Comment by jantic** [comment]
What I'm asking for though is the actual urls you're using to run these through DeOldify- assuming you're using urls.  It's either that or you're passing in a filename to a local file. In the case of urls, you will get the exact error you're getting if you're not directly linking to an image. For example, you have to get the direct image link on an Imgur image page as opposed to the link to the page it's hosted on, as the latter isn't the image itself.  

This doesn't work as a url:  [https://i.imgur.com/HGsGvPy](https://imgur.com/HGsGvPy)

This does:  [https://i.imgur.com/HGsGvPy.jpg](https://i.imgur.com/HGsGvPy.jpg)

Good way to tell if you're using the right link is to do a wget command on the image url and see if the resulting file you downloaded is actually an image.

If you're using an already downloaded file and are passing a file name in, best bet is to double check whether or not the file being pointed to is actually an image file by opening it.

These are really the only real possibilities I can think of and this seems specific to your use case, so chances are this isn't a bug in DeOldify that hasn't been discovered previously.  Anyway I wish you luck. I'll be closing this issue and not looking into it further unless I see a chorus of the same issues pop up indicating a widespread issue.
