### ISSUE TITLE
Save on your drive 

### ISSUE THREAD

**Issue by Archviz360** [jantic/DeOldify#416]
Hi! Is there a way to download & install deoldify on my Google Drive and then next time I run collab file I can just connect to my Google Drive folder with deoldify and runs it without having to download and install it everytime?? Is it possible and if so how do I do it??

**Comment by jantic** [comment]
This is really more a Google Colab question which honestly I couldn't tell you for sure if this would actually work. You can try starting (here)[https://stackoverflow.com/questions/48376580/google-colab-how-to-read-data-from-my-google-drive] and see if replacing the download steps with mounting the drive and operating on the DeOldify project there works. You'll still have to install the python dependencies for sure.

**Comment by Archviz360** [comment]
thanks for the tips will try to see if its possible to make so i just need to start with python dependencies. However do you know if this works on Vmware if I have a Linux distribution with the pre-installed python & conda ?? I plan to build a VMA server for my colorizing project that would be connected to a local network that would let me scan in photos  & import videos and then automatic colorize them

**Comment by jantic** [comment]
@Archviz360 I have limited experience with VMware but the key thing you'd have to look for is "gpu passthrough" and I know with vms that can be a hard thing to come by. Last I checked (like two years ago)that was offered only on a subset of VMware's offerings.
