### ISSUE TITLE
Jupyter doesn't run due to change in Pillow

### ISSUE THREAD

**Issue by Atheryl** [jantic/DeOldify#420]
`from deoldify.visualize import *
plt.style.use('dark_background')
import warnings
warnings.filterwarnings("ignore", category=UserWarning, message=".*?Your .*? set is empty.*?")`

Throw

`ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/home/ubuntu/miniconda3/envs/deoldify/lib/python3.7/site-packages/PIL/__init__.py)`

And from that location

```
# VERSION was removed in Pillow 6.0.0.
# PILLOW_VERSION was removed in Pillow 9.0.0.
# Use __version__ instead.
__version__ = _version.__version__
del _version
```

**Comment by Atheryl** [comment]
There are other broken dependancies, so I guess it's not workable for the moment.

**Comment by enessol** [comment]
@Atheryl Hey, could you manage to get it working? I have been having the same issue.

**Comment by prettydeep** [comment]
@enessol Someone provided a CLI script [here](https://github.com/jantic/DeOldify/issues/395#issuecomment-1026548969) that is working for me. I tried running the same script within a Jupyter notebook, seems to run fine.

**Comment by enessol** [comment]
@prettydeep Thanks a lot! I have tried your solution. However, when I run the command I get this error:

AssertionError: dummy is not a valid directory.

What is OS? I have been using Windows 10. I would really be delighted if you could tell me how exactly you are running the script.

**Comment by prettydeep** [comment]
@enessol I am running in ubuntu18 wsl, on win11, with python3.7.

You may need to create a 'video/source/' directory within the Deoldify folder before you run the script (if you are using video). When I git clone Deoldify this folder is missing. Incoming video needs to be in this 'source' directory. The CLI script and notebook file need to run from the root Deoldify folder. 

Attached is the notebook I am using. 
[deoldify.zip](https://github.com/jantic/DeOldify/files/8691717/deoldify.zip)

**Comment by enessol** [comment]
I appreciate your support. This is my first time dealing with an AI project so please pardon my questions :) I know that it might be a lot but I have to get this working somehow. 
If it is possible could you please elaborate more on how you managed to get DeOldify working on your system? I would love step-by-step instructions. And I wonder what your CLI script looks like after you modified it according to your own directory. If it is possible can you also upload your whole DeOldify folder (without the models ofc)? 

I hope I did not cause you any trouble with my overwhelming questions :))

**Comment by enessol** [comment]
@prettydeep I appreciate your support. This is my first time dealing with an AI project so please pardon my questions :) I know that it might be a lot but I have to get this working somehow.
If it is possible could you please elaborate more on how you managed to get DeOldify working on your system? I would love step-by-step instructions. And I wonder what your CLI script looks like after you modified it according to your own directory. If it is possible can you also upload your whole DeOldify folder (without the models ofc)?

I hope I did not cause you any trouble with my overwhelming questions :))

**Comment by prettydeep** [comment]
@enessol Everything you need is in the deoldify.zip file in the previous post. Extract the notebook, and try running it in google colab. If you still can't run on a local machine, then I suspect you have larger issues.

**Comment by enessol** [comment]
@prettydeep You are amazing, thank you! I can't believe it worked! I colored a short video on Colab using the zip file you provided. Now I need to make it work on my local machine :)

**Comment by enessol** [comment]
@prettydeep I had to double post but there is only one error left. I was wondering if you faced the same error. DeOldify successfully colorized the video. When I run it on Colab it produces a video with audio. However, when I run it locally the video has no audio. **And displays the following error.**

Transferring audio
Traceback (most recent call last):
  File "\DeOldify-master\run_local.py", line 137, in <module>
    model.colorize_video(args)
  File "\DeOldify-master\run_local.py", line 101, in colorize_video
    subprocess.call(" && ".join([command1, command2]), shell=platform.system() != 'Windows')
  File "\anaconda3\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System cannot find file specified

**Comment by prettydeep** [comment]
Just use ffmpeg to copy audio from one video to another.

ffmpeg -i COLOR.mp4 -i BW.mp4 -map 0:v -map 1:a -c copy videoCOLORaudioBW.mp4

**Comment by enessol** [comment]
@prettydeep Thanks a lot it works! I had almost given up on installing DeOldify before you helped me out. I do appreciate your assistance :)

**Comment by onepoint16** [comment]
I found a similar issue being discuss on the Pillow repository page. A fix seems to be installing pillow version 6.1. It worked for me and I'm using Win 10. https://github.com/python-pillow/Pillow/issues/4130#issuecomment-555434800

**Comment by jantic** [comment]
Thanks everyone for digging into this while I was gone. I'll try to build in a fix fairly soon.

**Comment by Mityugin** [comment]
Renamed copy of _version. to PILLOW_VERSION. Now stuck on this string:
```
colorizer = get_video_colorizer()
Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /home/kirill/.torch/models/resnet101-5d3b4d8f.pth
178728960it [02:25, 1227503.15it/s]
```
After downloading nothing... tried in WSL2 and from hard drive different Ubuntu versions

**Comment by Mityugin** [comment]
[https://github.com/jantic/DeOldify/issues/364#issuecomment-882712865](url)

This works with WSL2 and 30 series

**Comment by jantic** [comment]
Hey everyone-

I've got fixes in for this and a bunch of other stuff (like supporting the latest GPUs with the latest version of PyTorch). Hopefully you guys should be good to go now.
