### ISSUE TITLE
about fastai

### ISSUE THREAD

**Issue by tongchangD** [jantic/DeOldify#421]
Have you considered removing Fastai and using pyTorch code entirely？

**Comment by jantic** [comment]
I don't have any reason to do that. Why roll my own on all the things that FastAI is doing for me?

**Comment by tongchangD** [comment]
> I don't have any reason to do that. Why roll my own on all the things that FastAI is doing for me?

Thanks for your reply, I have removed FastAI

**Comment by jantic** [comment]
Granted, if you're just doing inference- you can achieve that fairly easily. But the FastAI code is there for all the training infrastructure it provides. After all, the code provided here is to share the research.
