### ISSUE TITLE
youtube-dl should be replaced ASAP by youtube-dlp, environment.yml should be modified, a last command required

### ISSUE THREAD

**Issue by PeaceForWar3** [jantic/DeOldify#426]
1) youtube-dl has been abandoned and shouldn't be used anymore (very slow YT downloads, couldn't try the Video model), instead it should be replaced by its open-source fork youtube-dlp, which not only uses the same commands (except "yt-dlp" command instead of "youtube-dl command" of course) but adds support for new file formats, new commands and allows running a subprocess within the same line (example would be using ffmpeg to extract a frame from an online video downloaded by yt-dlp, reframe it and use that as a FLAC's thumbnail).

2) I knew Windows was not supported and I installed Ubuntu when I couldn't create the deoldify environment beacuse of some errors, but I still had the same exact error as on windows: "youtube-dl resolvepackagenotfound etc " . Turns out it worked when I moved "youtube-dl" under "-pip:" and had to remove "-pip" just below "dependencies:". This is what it looks like:

**name**: deoldify

**channels**:
- fastai
- pytorch
- defaults
**dependencies**:
- fastai=1.0.60
- python>=3.7.3
- pytorch=1.11.0
- torchvision
- torchaudio
- tensorboardX
- jupyterlab
- pillow>=9.0.0
- ffmpeg
- 
**-pip:**
- youtube-dl
- ffmpeg-python
- opencv-python>=3.3.0.10
- wandb

I also had to run "conda install -c conda-forge ipywidgets" to get any notebook cell to work.
Last but not least I never got the tornado error.

I don't know why it works, I believe pip is somehow the problem. Maybe the pip that gets installed conflicts with the preinstalled one IDK.

Anyhow, this was what I did to make it work flawlessly (up until now) with python 3.9.5 preinstalled on Ubuntu 22.04 LTS.
I will try this on Windows too and see if it works given the error was the EXACT same on both OS's

Thanks for this amazing tool and I hope this can help anyone else.
Have a nice day.

**Comment by jantic** [comment]
This is great feedback. I've integrated these suggestions and can confirm that yt-dlp is much faster (have been using it for internal projects for a few months).  Thanks!
