### ISSUE TITLE
Exception: It's not possible to apply those transforms to your dataset:  module 'torch' has no attribute 'linalg'

### ISSUE THREAD

**Issue by dejanmilivojevic** [jantic/DeOldify#427]
When I try to run the ColorizeTrainingArtistic notebook from a docker container created with a quick_start.sh, I get the error from the title. I check the pytorch version it was 1.1.0a0+9eb0f43. I tried downgrading to 1.0.1 and I get the same error again. 

Here is the full stack trace.

`Exception                                 Traceback (most recent call last)
<ipython-input-7-f9cef04e4915> in <module>
----> 1 data_gen = get_data(bs=bs, sz=sz, keep_pct=keep_pct)

<ipython-input-5-a2527b763e63> in get_data(bs, sz, keep_pct)
      1 def get_data(bs:int, sz:int, keep_pct:float):
      2     return get_colorize_data(sz=sz, bs=bs, crappy_path=path_lr, good_path=path_hr, 
----> 3                              random_seed=None, keep_pct=keep_pct)
      4 
      5 def get_crit_data(classes, bs, sz):

/data/deoldify/dataset.py in get_colorize_data(sz, bs, crappy_path, good_path, random_seed, keep_pct, num_workers, stats, xtra_tfms)
     30             ),
     31             size=sz,
---> 32             tfm_y=True,
     33         )
     34         .databunch(bs=bs, num_workers=num_workers, no_check=True)

/data/fastai/data_block.py in transform(self, tfms, **kwargs)
    500         if not tfms: tfms=(None,None)
    501         assert is_listy(tfms) and len(tfms) == 2, "Please pass a list of two lists of transforms (train and valid)."
--> 502         self.train.transform(tfms[0], **kwargs)
    503         self.valid.transform(tfms[1], **kwargs)
    504         if self.test: self.test.transform(tfms[1], **kwargs)

/data/fastai/data_block.py in transform(self, tfms, tfm_y, **kwargs)
    719     def transform(self, tfms:TfmList, tfm_y:bool=None, **kwargs):
    720         "Set the `tfms` and `tfm_y` value to be applied to the inputs and targets."
--> 721         _check_kwargs(self.x, tfms, **kwargs)
    722         if tfm_y is None: tfm_y = self.tfm_y
    723         tfms_y = None if tfms is None else list(filter(lambda t: getattr(t, 'use_on_y', True), listify(tfms)))

/data/fastai/data_block.py in _check_kwargs(ds, tfms, **kwargs)
    591         try: x.apply_tfms(tfms, **kwargs)
    592         except Exception as e:
--> 593             raise Exception(f"It's not possible to apply those transforms to your dataset:\n {e}")
    594 
    595 class LabelList(Dataset):

Exception: It's not possible to apply those transforms to your dataset:
 module 'torch' has no attribute 'linalg'`

**Comment by jantic** [comment]
So first thing to point out here:  The Docker stuff was never intended for training. It was strictly made with inference and server deployment in mind. The problem you had here was indeed actually a legit problem in the Docker file (PyTorch version wasn't properly updating to latest version) but doubtless you would have other problems with this anyway after having that solved.

What you should do instead if you're interested in training is use the conda install. That's what is supported, anyway.

Now here's the thing that I'm sure is going to disappoint some people:  I've just removed the the Docker support. I've been wanting to do this for a while but this issue you had here got me to finally do it.  There's a few reasons:

1. It's a lot of extra stuff to support.
2. It strays far away from the core mission of this repo: To strictly share research.  As opposed to helping others deploy this as a service.
3. It was a lot of extra clutter in the repo and readme (and hence more potential for confusion).

**Comment by dejanmilivojevic** [comment]
>     2. It strays far away from the core mission of this repo: To strictly share research.  As opposed to helping others deploy this as a service.

I think to effectively share resarch is to have training setup as easily runnable as possible, so that people can play with the model and data and compare with "official" results. At least that is what I'm trying to do :)

I'm willing to make a docker image for training setup and I can make a pull request and potentialy mantain it. If you are not up for it that is also ok I respect your decision.

**Comment by jantic** [comment]
@dejanmilivojevic I understand what you're saying, but that argument could easily be extrapolated to suggest that we should support Jax, Tensorflow, Windows, AMD cards, etc.  I'm really advocating for simplicity and strict limits here. The more you support in software, the less likely you'll succeed in keeping everything in working order and correct, especially in the long term.

I really appreciate your offer on the pull request and the offer to maintain it, but I respectfully decline. In practice- life happens and I certainly wouldn't expect you to do free maintenance on something non-trivial like that in the long term.  I've dealt with Docker enough to know that it can become quite the pain in the butt.
