### ISSUE TITLE
How to use a local video in my HDD instead of Youtube video

### ISSUE THREAD

**Issue by Lamin3** [jantic/DeOldify#429]
Hello people ! 
Well I'm totally noob on Ubuntu/Linux & Python so it may be a stupid question but i'm really stucking on it, i would like to know what's the way to put a local video/image in the "source_url" without uploading it in a cloud, i don't know if i'm wrong but i just pasted the path file on the URL, like in this example:

> source_url = ''/home/MyNickname/Downloads/Video001.mp4"
> render_factor = 21 #@param {type: "slider", min: 5, max: 40}
> watermarked = True #@param {type:"boolean"}
> 
> if source_url is not None and source_url !='':
> video_path = colorizer.colorize_from_url(source_url, 'video.mp4', render_factor, watermarked=watermarked)
> show_video_in_notebook(video_path)
> else:
> print('Provide a video url and try again.')

And i get an error saying that it's not a valid youtube link.
I also tried to drag & drop the video in a new tab of mozilla so i got a path like " File:///home/MyNickname/Dektop/Video001.mp4 " that i pasted on the source_url but i got the same issue.

If somebody can help it would be cool.

**Comment by prettydeep** [comment]
You can try the script [here](https://github.com/jantic/DeOldify/issues/395#issuecomment-1026548969) for processing local files.

**Comment by Lamin3** [comment]
Hello Prettydeep =) 
Well, excuse my lack of knowelge  i'm totally new on that and i'm trying to undertand.
So what i understand is that i should process like this:

- Download the zip which is here [https://github.com/harisreedhar/DeOldify/tree/run-local](url) and unzip it (let's say in /Downloads folder).
- I put my old B&W footage in the folder /test_images
- In my Ubuntu terminal i run the command: cd ~/Downloads/DeOldify
- Then i run the command: python run_local.py --input ./test_images/1.jpg --output ./test_images/ --model artistic

Is that the good way or if not can you please explain or just give me a lead so i can research on my own if it  somehow bother you, thanks in advance ^^

**Comment by prettydeep** [comment]
The URL you list does not show anything.

Just download the python script [here](https://github.com/harisreedhar/DeOldify/blob/run-local/run_local.py) and place it in the root Deoldify folder. Be sure to download it in the "Raw" form. Follow the install directions in the readme in the Deoldify repository for the python requirements and the necessary weights. Put your B&W image in the test_images folder. Then from the root Deoldify folder, run...

`python run_local.py --input ./test_images/1.jpg --output ./test_images/ --model artistic`

**Comment by Lamin3** [comment]
Sorry, i just updated the link.
I just figured out how to download that script, okay i took the RAW form ^^ 
Thank you very much, i'll test it and in a while and tell you how it's going =)
Thank again PrettyDeep

**Comment by Lamin3** [comment]
Okay so at first, after running that script  i got this error: 
ModuleNotFoundError: No module named 'cv2' 
So i tried to run before that: ### conda activate deoldify  (which is logical but i'm a real newbie ^^ )  and then i run the script, it works like a charm =) 
Thank you very much PrettyDeep i appreciate it !
