### ISSUE TITLE
how do i use local source and not internet for image and video?

### ISSUE THREAD

**Issue by Archviz360** [jantic/DeOldify#432]
Hi! i plan to create a test server where i running deoldify from. i need to know how i can use local source instead of internet. is there a way to fix that? i tried with instruction but i only get this error 

NameError                                 Traceback (most recent call last)
Input In [11], in <cell line: 9>()
     10     result_path = colorizer.colorize_from_url(source_url, file_name_ext, render_factor=render_factor)
     11 else:
---> 12     result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)
     14 show_video_in_notebook(result_path)

NameError: name 'colorizer' is not defined

it works fine when using youtube but i need to see if i can use it completely offline since the server that runs deoldify will not be connected to the internet and only be used in my local intranet

**Comment by jantic** [comment]
Basically there's two options provided here:  Either you use URLs to sites like YouTube (like you have already done successfully), or you point to a file local to your -server- using the code in the ImageColorizer.ipynb and VideoColorizer.ipynb notebooks as an example. Anything else- like perhaps you'd want to upload to a separate server from a local computer file- that would be beyond the scope of what will be supported here.  That would require work and research on your end. To elaborate- This is, unapologetically, a research repository. Nothing more. Nothing less. I've made a conscious decision to keep this project simple and leave the myriad of potential applications up to others to figure out.

**Comment by weirui0430** [comment]
你好，请问如何进行测试呢 项目包里找到了ColorizeTrainingWandb.ipynb的文件，但是运行不了。
