### ISSUE TITLE
NameError: name 'noisify' is not defined

### ISSUE THREAD

**Issue by YumiGoo** [jantic/DeOldify#435]
When I run the ColorizeTrainingVideo scripts, the code from SETUP section xtra_tfms=[noisify(p=0.8)] raise an error as shown in the title, may you tell me from which package it is imported? thank you.

**Comment by bitplane** [comment]
I'd guess it's this one:

https://pypi.org/project/noisify/

so `pip install noisify` after activating the Conda environment?

**Comment by jantic** [comment]
Strange that this hasn't come up before, but it'd just be missing this import:

from deoldify.augs import noisify

I'll quickly add that fix now.
