### ISSUE TITLE
Environment requirements conflicted

### ISSUE THREAD

**Issue by seidnerj** [jantic/DeOldify#441]
I'm getting unresolvable conflicts when running "conda env create -f environment.yml", I solved this by changing pytorch's version in environment.yml from 1.11.0 to 1.12.0. My guess is one or more of the other dependencies have been updated thus causing this issue.

Hopes this helps someone.

**Comment by seidnerj** [comment]
Fixed in https://github.com/jantic/DeOldify/pull/443

**Comment by robations** [comment]
#443 didn't get merged as far as I can tell?

**Comment by seidnerj** [comment]
nope...
