### ISSUE TITLE
Updating Deoldfy

### ISSUE THREAD

**Issue by mlubak** [jantic/DeOldify#442]
Not necissarily an issue, but rather a question. I Installed deoldify over a year ago on my own machine.It has been working well.  I see that some components like Pillow, Pytorch, are now using new versions in the Environment script. So the question, is should I be updating ? Will performance or results be any better? 

If so, what is the best way to do so without reinstalling and setting up ?

Thanks for the great program !

**Comment by stphtan94117** [comment]
hi sir
may i ask you,how was your train working?
i always failure on training.
my computer is windows 10.
but it can work on colorize.

**Comment by mlubak** [comment]
I am just using the included models. So I am not training. Colorizing is
working fine.

**Comment by jantic** [comment]
Sorry for the late response. I'd say the only compelling reason to upgrade would be to run on Windows (which doesn't sound like your use case). Otherwise you won't see a difference in quality of outputs and I wouldn't expect much better performance.
