### ISSUE TITLE
Code does not use GPU

### ISSUE THREAD

**Issue by ArielReplicate** [jantic/DeOldify#444]
Hi I'm running on a google cloud machine with ubuntu 20.04.5 with Tesla T4 gpu

I'm using the script bellow (and a similar one for video) but it seems not to use the GPU at all.

I tried using different cuda versions (11.6, 11.3, 10.2) and pytorch versions (1.11, 1.12, 1.13, 1.9) like suggested here #404 but all of them run only with CPU even though **torch.cuda.is_available()** is **True**

Am I doing something wrong here?

```from deoldify.visualize import *
from deoldify import device
from deoldify.device_id import DeviceId
device.set(device=DeviceId.GPU0)

import fastai
import torch
import warnings
import pathlib

torch.backends.cudnn.benchmark=True
if not torch.cuda.is_available():
    print('GPU not available.')

warnings.filterwarnings("ignore", category=UserWarning, message=".*?Your .*? set is empty.*?")

colorizer = get_image_colorizer(artistic=True)

source_url = 'https://i.redd.it/ftd2jtea1pba1.jpg' #@param {type:"string"}
render_factor = 35  #@param {type: "slider", min: 7, max: 40}
watermarked = True #@param {type:"boolean"}


image_path = colorizer.plot_transformed_image_from_url(url=source_url, render_factor=render_factor, compare=True, watermarked=watermarked)

```

**Comment by jantic** [comment]
It's really not jumping out to me what's wrong here actually. Though I am curious, do you get a print out as expected if you change the code for detecting cuda like this?

if torch.cuda.is_available():
    print('GPU detected.')

**Comment by ArielReplicate** [comment]
This was indeed printed. Actually the first line in my script was 
`from deoldify.visualize import *
`
and moving to the last import removed the print and now the script seems to use the GPU.

However there seem to bee a slow loading into the GPU and memory usage increases slowly towards ~5G where the inference seem to happen?
Is this behaviour normal?

**Comment by jantic** [comment]
Oh yes if that was actually the first line in the script then that would indeed cause the first issue you were having. 

Now on the slow loading into GPU and memory usage you describe- yeah that sounds pretty normal for the open source version. I'm just telling you based on experience (don't have my local setup here to verify definitively currently). There are ways to speed things up that I didn't incorporate into the open source version- making pickled versions of the loaded models and using those as "cached" loaded models is a great way to get a speed up but it comes of course with the pitfalls of pickling.
