### ISSUE TITLE
Broken Link for ColorizeStable_gen.pth (Dropbox)

### ISSUE THREAD

**Issue by amitalokbera** [jantic/DeOldify#445]
Unable to download the pre-trained model from this link - https://www.dropbox.com/s/usf7uifrctqw9rl/ColorizeStable_gen.pth?dl=0 , please take a look at it.

Thank You

**Comment by S0nathan** [comment]
All dropbox links don't work in fact.

**Comment by jantic** [comment]
Sorry about the wait. I've finally been able to sit down and address this.  You should be good to go now.
