### ISSUE TITLE
i don't know where to copy the models

### ISSUE THREAD

**Issue by Postconceptlab** [jantic/DeOldify#447]
I cannot see a model folder in deoldify folder where i can copy the models , is there something i missed ?

**Comment by jantic** [comment]
Oops! I've added this back to the project. It's in the root folder as ./models . Sorry about that.

**Comment by Ssakura-go** [comment]
> Oops! I've added this back to the project. It's in the root folder as ./models . Sorry about that.

Hi, dear contributor, 

I met with the same problem and I only found the file [.gitkeep] in the root folder [./models]. Could you please tell me how to get the code?

**Comment by jantic** [comment]
@Ssakura-go  This section in the readme should help:  [https://github.com/jantic/DeOldify#pretrained-weights](https://github.com/jantic/DeOldify#pretrained-weights)

**Comment by Ssakura-go** [comment]
> @Ssakura-go This section in the readme should help: https://github.com/jantic/DeOldify#pretrained-weights

Sorry for disturbing you again. I have learned from all the sections via the link you shared.  But I found that I haven't solved the problem yet. I want to share with you my situation and wonder if there exists any solution you know: My task requires me to train the model you shared on my cartoon images (which is different from natural images in the ImageNet dataset).

**Comment by jantic** [comment]
This isn't my repo, but someone did anime using a fork of DeOldify here:  [https://github.com/Dakini/AnimeColorDeOldify](https://github.com/Dakini/AnimeColorDeOldify ).  Not sure if that'll be useful but basically what I can tell you is that I don't have good instructions for you on this other than to start with what I did and tweak from there. If it's a much smaller dataset than Imagenet you're going to probably have to increase the number of epochs accordingly. But ultimately it'll really boil down to trial and error and I'd just consider both mine and Dakini's repos a good start.

**Comment by Ssakura-go** [comment]
> This isn't my repo, but someone did anime using a fork of DeOldify here: https://github.com/Dakini/AnimeColorDeOldify. Not sure if that'll be useful but basically what I can tell you is that I don't have good instructions for you on this other than to start with what I did and tweak from there. If it's a much smaller dataset than Imagenet you're going to probably have to increase the number of epochs accordingly. But ultimately it'll really boil down to trial and error and I'd just consider both mine and Dakini's repos a good start.

Thank you for your recommendation! 
Hope you have a good day!
