### ISSUE TITLE
Jupyter Cell2 PermissionError:13

### ISSUE THREAD

**Issue by cc1311** [jantic/DeOldify#449]
Hello, I have an issue when I run cell2 in local, there are Errors: Permission Error:13
`PermissionError Traceback (most recent call last)
Cell In[2], line 1
----> 1 from deoldify.visualize import *
2 plt.style.use('dark_background')
3 import warnings

File D:\Deoldify\DeOldify-master\deoldify\visualize.py:8
6 from PIL import Image
7 import ffmpeg
----> 8 import yt_dlp as youtube_dl
9 import gc
10 import requests

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp_init_.py:19
17 from .compat import compat_shlex_quote
18 from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
---> 19 from .downloader.external import get_external_downloader
20 from .extractor import list_extractor_classes
21 from .extractor.adobepass import MSO_INFO

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\downloader_init_.py:26
24 from .common import FileDownloader
25 from .dash import DashSegmentsFD
---> 26 from .external import FFmpegFD, get_external_downloader
27 from .f4m import F4mFD
28 from .fc2 import FC2LiveFD

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\downloader\external.py:12
10 from .fragment import FragmentFD
11 from ..compat import functools
---> 12 from ..postprocessor.ffmpeg import EXT_TO_OUT_FORMATS, FFmpegPostProcessor
13 from ..utils import (
14 Popen,
15 RetryManager,
(...)
29 traverse_obj,
30 )
33 class Features(enum.Enum):

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\postprocessor_init_.py:38
35 from .xattrpp import XAttrMetadataPP
36 from ..plugins import load_plugins
---> 38 _PLUGIN_CLASSES = load_plugins('postprocessor', 'PP')
41 def get_postprocessor(key):
42 return globals()[key + 'PP']

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:135, in load_plugins(name, suffix)
132 def load_plugins(name, suffix):
133 classes = {}
--> 135 for finder, module_name, _ in iter_modules(name):
136 if any(x.startswith('_') for x in module_name.split('.')):
137 continue

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:119, in iter_modules(subpackage)
117 fullname = f'{PACKAGE_NAME}.{subpackage}'
118 with contextlib.suppress(ModuleNotFoundError):
--> 119 pkg = importlib.import_module(fullname)
120 yield from pkgutil.iter_modules(path=pkg.path, prefix=f'{fullname}.')

File C:\ProgramData\Anaconda3\envs\deoldify\lib\importlib_init_.py:127, in import_module(name, package)
125 break
126 level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File :1014, in _gcd_import(name, package, level)

File :991, in find_and_load(name, import)

File :971, in find_and_load_unlocked(name, import)

File :914, in _find_spec(name, path, target)

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:96, in PluginFinder.find_spec(self, fullname, path, target)
93 if fullname not in self.packages:
94 return None
---> 96 search_locations = self.search_locations(fullname)
97 if not search_locations:
98 return None

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:88, in PluginFinder.search_locations(self, fullname)
86 elif path.name and any(path.with_suffix(suffix).is_file() for suffix in {'.zip', '.egg', '.whl'}):
87 with contextlib.suppress(FileNotFoundError):
---> 88 if parts in dirs_in_zip(path):
89 locations.add(str(candidate))
90 return locations

File C:\ProgramData\Anaconda3\envs\deoldify\lib\site-packages\yt_dlp\plugins.py:37, in dirs_in_zip(archive)
35 @functools.cache
36 def dirs_in_zip(archive):
---> 37 with ZipFile(archive) as zip:
38 return set(itertools.chain.from_iterable(
39 Path(file).parents for file in zip.namelist()))

File C:\ProgramData\Anaconda3\envs\deoldify\lib\zipfile.py:1251, in ZipFile.init(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
1249 while True:
1250 try:
-> 1251 self.fp = io.open(file, filemode)
1252 except OSError:
1253 if filemode in modeDict:

PermissionError: [Errno 13] Permission denied: 'D:\Deoldify\DeOldify-master'`

**Comment by cc1311** [comment]
![fc708d15e09e3866174801a58284c4b](https://user-images.githubusercontent.com/125037628/218235724-166b4b5f-0f92-43b1-9c36-f8657ec87faf.png)
![d7ec50857c6d7872ad2439101403e9d](https://user-images.githubusercontent.com/125037628/218235730-8dda08e1-ca6f-4cd3-a546-676bcad2cb5b.png)
![a7987f1959f5f9e9a172564d079a992](https://user-images.githubusercontent.com/125037628/218235732-ab053aed-546d-4886-9c16-1f37ded8479b.png)

**Comment by jantic** [comment]
You should  be able to resolve this by following these directions for the D://DeOldify folder:  https://answers.microsoft.com/en-us/windows/forum/all/permissionerror-errno-13-permission-denied-how-to/1b61d264-4df4-4bfc-b1a9-1e4808f23ee5 .

**Comment by cc1311** [comment]
> You should be able to resolve this by following these directions for the D://DeOldify folder: https://answers.microsoft.com/en-us/windows/forum/all/permissionerror-errno-13-permission-denied-how-to/1b61d264-4df4-4bfc-b1a9-1e4808f23ee5 .

Still not worked, should I re-install the environment and try it again?

**Comment by cc1311** [comment]
> You should be able to resolve this by following these directions for the D://DeOldify folder: https://answers.microsoft.com/en-us/windows/forum/all/permissionerror-errno-13-permission-denied-how-to/1b61d264-4df4-4bfc-b1a9-1e4808f23ee5 .

Hey!! I think I've known the reason, which is my hard disk. I just copy the folder to another hard disk, it worked! However, I still didn't find why the old hard disk could not write. Whatever, now the program is running well, and colorizing the video. Awesome!!

**Comment by jantic** [comment]
Good to know!

**Comment by cc1311** [comment]
> Good to know!

Hey, I found there is a small watermark like a palette in the lower left corner of the colorized video. Can I remove it?
![image](https://user-images.githubusercontent.com/125037628/218321255-dfeddd63-e470-4509-bf3f-78dd58fa53c6.png)

**Comment by jantic** [comment]
Yeah just add this to the video colorization call:

watermarked=False
