### ISSUE TITLE
i am stuck at {IndexError: index 0 is out of bounds for axis 0 with size 0}

### ISSUE THREAD

**Issue by mohmam1977** [jantic/DeOldify#451]
i am stuck at {IndexError: index 0 is out of bounds for axis 0 with size 0}

any help ?

**Comment by jantic** [comment]
There's not too much information to go by here so far so it'd help to know what you're running and the larger error message you're getting (stack trace). But at first glance this looks like it could be an empty/invalid/non existent image it's trying to run on. If it's a url you're using make sure it's the direct link to the photo as opposed to just the page hosting the photo.  In Imgur, for example, you'd have to right click and "copy image address" as opposed to just using the url of the page with the image on it.  e.g. for this page,[https://imgur.com/t/old_photo/LMkLq87]( https://imgur.com/t/old_photo/LMkLq87), you'd wind up getting this direct url that you would actually use to colorize:  
[https://i.imgur.com/v5t4V6V.png](https://i.imgur.com/v5t4V6V.png)
