### ISSUE TITLE
How many epochs we should set

### ISSUE THREAD

**Issue by ZhichaoZuo** [jantic/DeOldify#453]
Excuse me, How many epochs we should set when we train the generator and the critic? just change the parameter of '.fit_one_cycle()'?

**Comment by jantic** [comment]
The training notebooks should have the correct settings built in already. Just make sure to read the instructions on the GAN training part in particular.  Is there a specific notebook/cell you're wondering about?

**Comment by ZhichaoZuo** [comment]
Thank you for your attention. And in the ColorizeTrainingStable.ipynb, if the parameters in the function of '.fit_one_cycle()' need to be adjusted, such as the epochs or max_lr, when the training dataset changes.

**Comment by jantic** [comment]
Well if you're changing the dataset then basically it's going to be a trial and error exercise for you. I can't really help you there beyond just saying that if it's a smaller dataset your probably going to have to have more epochs and the opposite if it's a bigger dataset. I doubt you'd have to change other parameters but ultimately this is all an empirically driven craft and I wouldn't take anything I've said or done as anything other than tentative!
