### ISSUE TITLE
Flat out not working with specific image

### ISSUE THREAD

**Issue by IveMalfunctioned** [jantic/DeOldify#454]
So I'm trying to colorize [this image](https://i.imgur.com/kt3E8AG.jpg) with DeOldify, but the result is just a neutralized version with no color added. I'm not sure what's going on here. Testing with other black and white images works

**Comment by jantic** [comment]
Yeah unfortunately there are some cases where DeOldify just totally falls on its face and this is one of them. The best results you can get with it are attained by lowering the render_factor all the way down to 8 or 10. Generally if you're lacking in color that's your best bet- lower the render_factor. But even then in this case it just renders the floor red.
![download](https://user-images.githubusercontent.com/179759/219963476-df5ff322-5dcb-4311-b895-b655774dd9e4.png)
