### ISSUE TITLE
Hello, does this model have any restrictions on the size of video?

### ISSUE THREAD

**Issue by mpr0xy** [jantic/DeOldify#455]
Sorry, I may not have looked at the document very carefully, but I still want to ask, does this model have any restrictions on the size and format of the video?

**Comment by jantic** [comment]
If you're using Colab, you'll basically have an effective practical limit of about a minute or less in length. Otherwise you'll tend to run into reliability issues (Colab limitations). With local installs, you can go as long as you want.

The format DeOldify is expecting for videos is mp4.
