### ISSUE TITLE
How to load from google colab content folder not from url 

### ISSUE THREAD

**Issue by FurkanGozukara** [jantic/DeOldify#456]
Hello. I have a very bad video recording

Here a frame

![image](https://user-images.githubusercontent.com/19240467/221563872-5e5e148b-0a3d-4955-b14b-ddc093408cfc.png)

I want to improve and upscale if possible

Wanted to test colab : https://colab.research.google.com/github/jantic/DeOldify/blob/master/VideoColorizerColab.ipynb#scrollTo=663IVxfrpIAb

But it only has 

```
source_url = '' #@param {type:"string"}
render_factor = 21  #@param {type: "slider", min: 5, max: 40}
watermarked = True #@param {type:"boolean"}

if source_url is not None and source_url !='':
    video_path = colorizer.colorize_from_url(source_url, 'video.mp4', render_factor, watermarked=watermarked)
    show_video_in_notebook(video_path)
else:
    print('Provide a video url and try again.')
```

How can I give drive content path? I know how to upload and give file path but it only accepts url and have no idea how to modify  `colorizer.colorize_from`

Thank you

**Comment by jantic** [comment]
Well I can save you a bit of time here:  DeOldify won't help to improve that sort of video. It'll just try to re-colorize it and the results won't look right. I'd recommend looking into something like Topaz for what you're asking for, here: [https://www.topazlabs.com](https://www.topazlabs.com)

**Comment by FurkanGozukara** [comment]
> Well I can save you a bit of time here: DeOldify won't help to improve that sort of video. It'll just try to re-colorize it and the results won't look right. I'd recommend looking into something like Topaz for what you're asking for, here: https://www.topazlabs.com

thank you. sad :/
