### ISSUE TITLE
what files are stored in this folder：./dummy/?

### ISSUE THREAD

**Issue by ZhichaoZuo** [jantic/DeOldify#457]
what files are stored in this folder：./dummy/?

def get_dummy_databunch() -> ImageDataBunch:
    path = Path('./dummy/')
    return get_colorize_data(
        sz=1, bs=1, crappy_path=path, good_path=path, keep_pct=0.001
    )

**Comment by jantic** [comment]
You actually don't need to worry about that.  It's purposefully empty to create an empty dataset. It was a quick hack on my part, admittedly.
