### ISSUE TITLE
Numexpr using 8 cores

### ISSUE THREAD

**Issue by bobba84** [jantic/DeOldify#459]
Hey guys,

I'm using a 5950X to run deoldify but I get the message "Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8."

Where / how can I set this to 16?

Thank you!

**Comment by jantic** [comment]
This thread should help:  [https://stackoverflow.com/questions/71248521/why-numexpr-defaulting-to-8-threads-warning-message-shown-in-python](https://stackoverflow.com/questions/71248521/why-numexpr-defaulting-to-8-threads-warning-message-shown-in-python)

I wouldn't necessarily worry about it but you can certainly experiment with it.
