### ISSUE TITLE
Error transforming image - possibly because outside notebook

### ISSUE THREAD

**Issue by gmerrall** [jantic/DeOldify#46]
I'm on a machine without a GUI so I'd prefer to just run everything from the command line like a boss and I can do some general tinkering on a range of images and weights.

I've basically just copied the relevant bits from the notebooks 
```
import multiprocessing
import os
from torch import autograd
from fastai.transforms import TfmType
from fasterai.transforms import *
from fastai.conv_learner import *
from fasterai.images import *
from fasterai.dataset import *
from fasterai.visualize import *
from fasterai.callbacks import *
from fasterai.loss import *
from fasterai.modules import *
from fasterai.training import *
from fasterai.generators import *
from fasterai.filters import *
from fastai.torch_imports import *
torch.backends.cudnn.benchmark=True
torch.cuda.set_device(0)

colorizer_path = 'colorize_gen_192.h5'
render_factor=42
weights_path = "/mnt/disks/400gb_ssd/DeOldify/colorize_gen_192.h5"
results_dir="/mnt/disks/400gb_ssd/DeOldify/result_images"
filters = [Colorizer34(gpu=0, weights_path=weights_path)]
vis = ModelImageVisualizer(filters, render_factor=render_factor, results_dir=results_dir)
vis.plot_transformed_image("test_images/1852GatekeepersWindsor.jpg")
```

It's unfortunately resulting in the below error. I don't doubt for a second the issue is with me
```
Traceback (most recent call last):
  File "/mnt/disks/400gb_ssd/DeOldify/fastai/dataset.py", line 234, in open_image
    im = cv2.imread(str(fn), flags).astype(np.float32)/255
AttributeError: 'NoneType' object has no attribute 'astype'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    vis.plot_transformed_image("test_images/1852GatekeepersWindsor.jpg")
  File "/mnt/disks/400gb_ssd/DeOldify/fasterai/visualize.py", line 31, in plot_transformed_image
    result = self._get_transformed_image_ndarray(path, render_factor)
  File "/mnt/disks/400gb_ssd/DeOldify/fasterai/visualize.py", line 49, in _get_transformed_image_ndarray
    orig_image = open_image(str(path))
  File "/mnt/disks/400gb_ssd/DeOldify/fastai/dataset.py", line 238, in open_image
    raise OSError('Error handling image at: {}'.format(fn)) from e
OSError: Error handling image at: test_images/1852GatekeepersWindsor.jpg
```

Which in itself is odd because you'd expect the filecheck at the top of open_image() to have dealt with that. I'm guessing this is not a DeOldify issue per se as it's all inside fastai but wonder if you've any thoughts.

**Comment by jantic** [comment]
Yeah actually I do have an initial idea here (haven't dug deep to test the theory myself yet).  If it's getting past the os.path.exists part in open_image then what you're probably dealing with is a corrupted file (says it's a jpg but isn't- it's probably a very small file).  And there's something I haven't explicitly covered in the installation process yet which is that this particular repo uses git lfs (https://git-lfs.github.com/) for the images.  Now in my case I use the GitHub desktop client for Linux, which automatically prompts you to install Git LFS if you don't have it yet.  But if your'e just using the plain old git command line client, it probably didn't say anything about it and it probably just downloaded the images incorrectly as a result.  

So that's where I'd start.

If it's not that, I'd still wager the files are corrupted and would simply need to be downloaded again.

**Comment by gmerrall** [comment]
Now why didn't I think of that. 1852GatekeepersWindsor.jpg is a glorious 131 bytes in size as are all the images in the test_images directory. 

I'm using Ubuntu xenial for this so it's an older version of git.  I fixed the issue by updating git and installing git-lfs according to https://github.com/git-lfs/git-lfs/wiki/Installation and then re-fetched the single image.  
```
git fetch
git checkout origin/master test_images/1852GatekeepersWindsor.jpg
```

and it's now 227kb and the image transform is called. Thanks for the pointer!  I'll leave this open in case you want to use it as a prompt to update the README.

**Comment by jantic** [comment]
Yeah let's keep it open exactly for that purpose- I need to either make it explicitly part of the install process described in text or something. I'll think on that.

**Comment by jantic** [comment]
I added instructions on Git LFS finally.  Closifying
