### ISSUE TITLE
 Whether cv2.COLOR_BGR2YUV should be changed to  cv2.COLOR_RGB2YUV?

### ISSUE THREAD

**Issue by winnieepooh** [jantic/DeOldify#462]
![image](https://user-images.githubusercontent.com/94221441/228416380-387fc716-1ad0-4599-8a45-9a6a53261e76.png)
PIL reads images on the RGB channel.  Why is this BGR2YUV?
Thanks!

**Comment by jantic** [comment]
Years ago I saw this and figured it wasn't a big deal and just left it be, even though it's weird. My reasoning was that it's normalizing luminance of an already b/w image (so the channel ordering shouldn't matter much), and the chroma conversion is effectively idempotent. I swear I tested it, but I just did again, and boy was I wrong!

Before/After:
![BGRC_RGBL](https://user-images.githubusercontent.com/179759/228584548-1f36aebe-dfb2-49a1-a7cf-2f50e968cf8c.jpg)
![RGBC_RGBL](https://user-images.githubusercontent.com/179759/228584568-0a4dcbe3-dc66-4f6e-ab81-807e4d88402c.jpg)

I honestly don't know how I let this go for so long but thank you for pointing this out! Fix is in.
