### ISSUE TITLE
Delete watermark

### ISSUE THREAD

**Issue by OmlineEditor** [jantic/DeOldify#467]
watermark spoils the photo and covers part of the image. the presence of a watermark can cause a negative reaction from viewers who believe that it is unsightly and interferes with the evaluation of the photo. this program is open source and anyone can remove the watermark, but this only hinders inexperienced people
I ask you to delete the watermark or replace it with the file that I attached in the message.

I'm talking about this image: resource_images/watermark.png

this watermark image falls on the photos that are processed on this site https://replicate.com/arielreplicate/deoldify_image. you can't remove the watermark there. I ask you to remove it from the code so that later the improved version is uploaded to replicate.com
[watermark.zip](https://github.com/jantic/DeOldify/files/11256434/watermark.zip)

**Comment by jantic** [comment]
This is a trick issue for sure. The reason why it's there to begin with is to convey that the colorization is made by AI and not representative of real colors. It depends on who you talk to, but this is a controversial subject. I err on the side of caution on this ethically, so it defaults to using the watermark. On the other-hand, I know full well that frankly most users don't want it showing up on their renders, so you can toggle it off.

As far as it showing up without being able to toggle it off on Ariel Replicate renders- that's the designer's choice really, and out of my hands.

So I'm going to keep the code as is on this.

**Comment by OmlineEditor** [comment]
is it possible to call the program and pass it a parameter to remove the logo?

**Comment by OmlineEditor** [comment]
where can I find instructions on how to run your program on a computer on my own? I have little experience, but I can do it if there is an instruction
