### ISSUE TITLE
can't download Completed Generator Weights of Artistic and Video

### ISSUE THREAD

**Issue by scholarboss** [jantic/DeOldify#469]
hello, as the title mentioned. I can't open the URL of 'https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth' and 'https://data.deepai.org/deoldify/ColorizeVideo_gen.pth'. is there something wrong?

**Comment by jantic** [comment]
It works for me.  Seems like it must be a temporary or local issue for you....
