### ISSUE TITLE
Can you help fix a bug in AnimeColorDeOldify?

### ISSUE THREAD

**Issue by My12123** [jantic/DeOldify#474]
https://github.com/Dakini/AnimeColorDeOldify/issues/9

**Comment by jantic** [comment]
Did you use the requirements.txt file to install the requirements (via pip)? And is the install isolated from other things with either a python environment or a conda environment?  If you do those two things you should avoid this error as what you're seeing here is that the Python version used here (3.10) is a mismatch from what should be installed (3.6). 

If that doesn't work- It's very possible that you did those two things and that there's a bug in the fastai install process that's allowing for 3.10 to be install so if that's the case, I'd just put in an explicit line in requirements.txt:

`python==3.6.15`

If that's the case I can see about doing a pull request for that project but honestly it appears they're not making updates to that project lately.
