### ISSUE TITLE
How to stablize the colors between frames of a video?

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [jantic/DeOldify#476]
When using both the local Windows .NET program, with Artistic and Stable half width model, I can see an obvious inconsistency between frames, resulting in video changing hue rapidly. Is there any solution?

**Comment by jantic** [comment]
I'm a bit confused honestly. That .NET program (assuming you're talking about [this](https://github.com/ColorfulSoft/DeOldify.NET) ) is for images only. You'd want to use the video specific model for DeOldify (there's a link to the Colab on the readme. The reason why the video specific model was developed was specifically to address inconsistency of frames, at the expense of lowering the range of colors (deliberate tradeoff).

**Comment by ZzzzzzzSkyward** [comment]
> I'm a bit confused honestly. That .NET program (assuming you're talking about [this](https://github.com/ColorfulSoft/DeOldify.NET) ) is for images only. You'd want to use the video specific model for DeOldify (there's a link to the Colab on the readme. The reason why the video specific model was developed was specifically to address inconsistency of frames, at the expense of lowering the range of colors (deliberate tradeoff).

I have also tried that but it is still not ideal.

**Comment by jantic** [comment]
Yeah I guess we're out of luck here then. There are better ways to do video that avoid the flickering and make the color more vibrant- I improved upon the tech in our closed source models for the DeOldify business. But that's not an option here.
