### ISSUE TITLE
Why there's two different color output

### ISSUE THREAD

**Issue by shahidul56** [jantic/DeOldify#48]
using render factor =42 in colab but looks like this two result is not same 

![fwefe](https://user-images.githubusercontent.com/11449967/49158330-1890b180-f34c-11e8-96f9-a9986ed4693b.JPG)

![](https://pbs.twimg.com/media/Ds4yFpEUcAAWtJN.jpg)

**Comment by jantic** [comment]
Because that output on the bottom came from a newer model that I didn't commit yet.  Sorry for the confusion!  The newer model just isn't ready to be deployed yet.
