### ISSUE TITLE
video building only works for mp4s

### ISSUE THREAD

**Issue by meksor** [jantic/DeOldify#481]
Currently, as far as i can see, rebuilding the video (from the colorized frames) only works if the original input video is a `.mp4`. (I think that is the reason for #471 as i also have a .mkv based workflow) I have a fix for this on my fork which i would be willing to split up into a PR. 
However, I am not very familiar with this project so I wanted to ask if this is a desired feature and if there is any reason to blacklist or whitelist specific video formats. 

Regards

PS: the culprit: https://github.com/jantic/DeOldify/blob/141e873e42eb5e40665d20349f4b8e9a267ba1c4/deoldify/visualize.py#L306

**Comment by jantic** [comment]
Yeah that's a deliberate decision. As the aim is to just make research freely available to the public, I made a few simplifying decisions to keep maintenance and bugs to a minimum. This is one of them.

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by meksor** [comment]
I understand. It might be good to add a check and error message otherwise the decision does not seem too deliberate. 
Anyway I will keep using my fork then, I completely understand not wanting to put effort into this.
