### ISSUE TITLE
I develop a deoldify plugin for stable-diffusion-webui，can you add to readme？

### ISSUE THREAD

**Issue by SpenserCai** [jantic/DeOldify#483]
I develop a deoldify plugin for stable-diffusion-webui，can you add to readme？

[sd-webui-deoldify](https://github.com/SpenserCai/sd-webui-deoldify)

**Comment by jantic** [comment]
Done! I have to tell you, this is really really awesome. Thank you!

**Comment by SpenserCai** [comment]
> Done! I have to tell you, this is really really awesome. Thank you!

Thank you for your recognition that Deoldify is a great project. It's my honour to contribute to it.
