### ISSUE TITLE
Everything fails 

### ISSUE THREAD

**Issue by Chelseamaniac** [jantic/DeOldify#484]
![Screenshot 2023-08-06 231345](https://github.com/jantic/DeOldify/assets/140981654/4b927e1d-d1b9-4d27-8516-90f2f361c49c)
cant get beyond that point I have paid subscription and love te program

**Comment by HippieT** [comment]
Seems that deepai link is either down or no longer being used.

**Comment by Chelseamaniac** [comment]
thank you

**Comment by jantic** [comment]
there's no paid subscription on this stuff btw.... I'm not sure who you're paying but it's not me!
