### ISSUE TITLE
How to adjust bach during inference?

### ISSUE THREAD

**Issue by UserJTZhang** [jantic/DeOldify#485]
Thank you for your long-standing maintenance and support of the DeOldify project. I'm interested in adjusting the batch size during inference. Specifically, I'd like to feed multiple images into the model for inference in one batch and retrieve the results. How can this be achieved? Are there any specific configurations or methods in the codebase that facilitate this? Thank you.

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jantic** [comment]
There wasn't anything done to facilitate this in the project, no. It could be modified for sure to do that but that's beyond the scope of what I intended to do with this project.  The core code that does inference ultimately calls a function predict_batch in fastai with a single image to predict, which is a good place to start.

https://github.com/jantic/DeOldify/blob/be725ca6c5f411c47550df951546537d7202c9bc/fastai/basic_train.py#L374
