### ISSUE TITLE
The weight link (https://www.dropbox.com/s/7r2wu0af6okv280/colorize_gen_192.h5) in dana-kelley repository is broken, would you please share again?

### ISSUE THREAD

**Issue by xiaohong23** [jantic/DeOldify#486]
The weight link (https://www.dropbox.com/s/7r2wu0af6okv280/colorize_gen_192.h5) in dana-kelley repository is broken, would you please share again? There's no issues section in dana-kelley's rep.  Thanks.

**Comment by jantic** [comment]
Huh.... I think these disappeared a while ago actually. Yikes!  I'm sorry...

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jantic** [comment]
Update:  I found it!  https://www.dropbox.com/scl/fi/kq71pa6spwj430h9nteqv/ColorizeOpenSourceV1.pth?rlkey=fpywnia7upd5z992o6gtxze8w&dl=0
