### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by Archviz360** [jantic/DeOldify#488]
![error 1](https://github.com/jantic/DeOldify/assets/82177593/63ddc57d-bb31-4f8d-bda8-7e6bcf35f631)
![error 2](https://github.com/jantic/DeOldify/assets/82177593/d68284b4-d25a-4762-a0e5-f460331e78e3)

Got TypeError: 'NoneType' object is not subscriptable

if anyone can help me please contact me as soon you see this! contact me here or on my email dacsol@gmail.com with subject TypeError: 'NoneType' object is not subscriptable help.

**Comment by Archviz360** [comment]
UPDATE: problem solved. its cool to be able to finally run deoldify on windows

**Comment by oklahuma** [comment]
I am getting the same problem, how did you solve it?
