### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by shortymc** [jantic/DeOldify#490]
Hi i cant use it.
This is the errors i got :

(new_env) root@pc-46:/home/user/colorize/DeOldify# conda env create -f environment.yml
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
done
Solving environment: - Processus arrêté
(new_env) root@pc-46:/home/user/colorize/DeOldify# source activate deoldify
bash: activate: Aucun fichier ou dossier de ce type
(new_env) root@pc-46:/home/user/colorize/DeOldify# jupyter lab
bash: jupyter : commande introuvable
(new_env) root@pc-46:/home/user/colorize/DeOldify# source activate deoldify
bash: activate: Aucun fichier ou dossier de ce type

i run on debian jessie

 Thanks for your help.
best regards

**Comment by jantic** [comment]
I see this:

Solving environment: - Processus arrêté

To me that reads as if the conda environment install was stopped prematurely with either ctrl+c or something similar....Anyway I'd try that again but also I'd say that this primarily tested on Ubuntu 18.04 and above so I'm not sure what kind of problems you may be running into on Debian.
