### ISSUE TITLE
Any known update for MyHeritage edition?

### ISSUE THREAD

**Issue by whaleyland** [jantic/DeOldify#491]
I began using DeOldify regularly back in 2020 and then switched to the MyHeritage version in late 2022. However, I've noticed that MyHeritage has not added any new builds since February 2021, suggesting that the software has not improved since that time. Do you know if they have any plans to release a new build of the software anytime soon? There are still quality consistency issues with their current build and it could really benefit from two years of machine learning from contributors and users of the MyHeritage site.

If they don't have any plans to release new builds, are you going to release a new build at some point, or are you stuck contractually because the company doesn't care about improving its feature/gimmick? I'm honestly curious because I love the software and use it every day, but I would not be opposed to an improved version.

**Comment by jantic** [comment]
Believe it or not I've moved on from the DeOldify project and startup myself.  The startup still exists but I exited earlier this year. So I can't speak to their plans but I don't plan on doing updates to this repo other than maintenance.  I've moved on to weather forecasting modeling.
