### ISSUE TITLE
The content of flickr cannot be accessed. Please check the reason.

### ISSUE THREAD

**Issue by wangchun52799** [jantic/DeOldify#495]
The content of flickr cannot be accessed. Please check the reason.

[Flickr] 53451714377: Downloading api key
[Flickr] 53451714377: Downloading video info
[Flickr] 53451714377: Downloading streams info
[info] 53451714377: Downloading 1 format(s): 1080p
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (1/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (2/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (3/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (4/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (5/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (6/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (7/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (8/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (9/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (10/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (11/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (12/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (13/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (14/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (15/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (16/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (17/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (18/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (19/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (20/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (21/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (22/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (23/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (24/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (25/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (26/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (27/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (28/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (29/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Retrying (30/30)...
[download] Got error: HTTP Error 502: Bad Gateway. Giving up after 30 retries
---------------------------------------------------------------------------
DownloadError                             Traceback (most recent call last)
[<ipython-input-8-5d4a0bf743c3>](https://localhost:8080/#) in <cell line: 5>()
      4 
      5 if source_url is not None and source_url !='':
----> 6     video_path = colorizer.colorize_from_url(source_url, 'video.mp4', render_factor, watermarked=watermarked)
      7     show_video_in_notebook(video_path)
      8 else:

**Comment by jantic** [comment]
Hmm yeah I'm having trouble with Flickr links too. Not sure what's up there. Video/gif downloads are handled through youtube-dl (https://github.com/ytdl-org/youtube-dl), so that's beyond the scope of the DeOldify project to try to address. I wish I could help more on that!
