### ISSUE TITLE
VapourSynth version of DeOldify

### ISSUE THREAD

**Issue by dan64** [jantic/DeOldify#496]
I'd like inform you that I ported DeOldify on [VapourSynth](https://www.vapoursynth.com/). You can find the VapourSynth filter project here: [vs-deoldify](https://github.com/dan64/vs-deoldify). Thanks to VapourSynth architecture, I tried to improve the output quality of colorized images, by given the possibility to merge the colored image obtained with DeOldify with the image obtained with [DDColor](https://github.com/piddnad/DDColor).
It is possible to use this filter directly in [Hybrid,](https://www.selur.de/), it represent an interesting alternative to use DeOldify on Desktop.
I hope that you can find this project of your interest.
Dan

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jantic** [comment]
Wow, I went through that readme- very interesting results you got there. Great read, and I like the project! Thanks for doing this.
