### ISSUE TITLE
Can't find libtiff

### ISSUE THREAD

**Issue by bufordk** [jantic/DeOldify#498]
Not sure if this is the place to ask for help but I am out of ideas. the lib is in multiple places but DeOldify cannot find it. Obviously (or not) a path error. Any ideas you can throw my way or direct me to a different source for help?

Thanks,

BK
![image](https://github.com/jantic/DeOldify/assets/35783603/a0dcefc0-fd55-45af-97fd-144be5fcae54)

**Comment by jantic** [comment]
I haven't run into this error myself. Have you seen this?  Seems like a good start:  https://www.reddit.com/r/linuxquestions/comments/1054cju/libtiffso5_is_broken_how_to_fix_it/
