### ISSUE TITLE
Conditionning

### ISSUE THREAD

**Issue by darkzbaron** [jantic/DeOldify#499]
Thanks for this amazing work. Anyway to influence the recoloring process with custom colors? 

I would like any yellow to come out as a specific hex yellow for instance

**Comment by jantic** [comment]
Thanks! There isn't a way to do this unfortunately. DeOldify was designed to be a purely automatic colorization process, as opposed to one allowing for manual interventions like that. It wouldn't be trivial to redesign it for that either.
