### ISSUE TITLE
Enable 16bit tensor inference 

### ISSUE THREAD

**Issue by dan64** [jantic/DeOldify#500]
Hi Jantic,

  I'd like to know if there is any plan to enable 16bit tensor inference in Deoldify. 
  This update should speed-up the coloring process significantly. 

Thanks,
Dan

P.S.
I'd like to inform you that has been released the version 2.0 of filter [vs-deoldify](https://github.com/dan64/vs-deoldify)

**Comment by jantic** [comment]
> I'd like to inform you that has been released the version 2.0 of filter [vs-deoldify](https://github.com/dan64/vs-deoldify)

Very cool!

re: 16bit inference: I don't plan on modifying the repo going forward other than maintenance things like broken dependencies. I've moved on to other things. That being said, it should be pretty easy to modify the code to do this in a fork with the code as is and it should probably just work based on what I've done elsewhere.
