### ISSUE TITLE
https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0's accident

### ISSUE THREAD

**Issue by JoaquinP41** [jantic/DeOldify#501]
Jason Antic and I Were Sorry to just delete https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0. We Didn't mean to tell, it was an accident

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jantic** [comment]
You can get the weights here:  https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth . 

What you're looking at there is an old link from years ago.
