### ISSUE TITLE
Uneven color distribution in stable and artistic model outputs

### ISSUE THREAD

**Issue by dummyuser-123** [jantic/DeOldify#503]
Hi, First of all hats off to this amazing deep learning model. It is generating fantastic results in most of the cases in various image categories. While I was trying out artistic and stable model on the different different category of images, I was saw some uneven color distribution at some part of images in both the models.

1. Artistic Model

![artistic_model_35_10143179](https://github.com/jantic/DeOldify/assets/153290092/a8fb75ba-cd19-4cf1-9060-c8df47fec5a1)
![artistic_model_35_10143226](https://github.com/jantic/DeOldify/assets/153290092/dc325397-3b54-4f47-931e-0e20ed03a7ca)
![artistic_model_35_10143582](https://github.com/jantic/DeOldify/assets/153290092/1813436a-8604-4af8-a82d-32727c9be4c4)
![artistic_model_35_10144159](https://github.com/jantic/DeOldify/assets/153290092/74baa5f3-d10f-42a9-8075-4eae8ab0ce37)
![artistic_model_35_10144580](https://github.com/jantic/DeOldify/assets/153290092/04804335-31b6-46e8-8940-140978972332)
![artistic_model_35_10144635](https://github.com/jantic/DeOldify/assets/153290092/c6741a0e-7295-4e1f-92b9-340a18d86582)
![artistic_model_35_10144798](https://github.com/jantic/DeOldify/assets/153290092/a0bd0873-0ef8-4765-b11d-dfa6fe951a68)
![artistic_model_35_10145014](https://github.com/jantic/DeOldify/assets/153290092/13590ed5-ee1b-4e7f-9204-51fb0e4b17d4)
![artistic_model_35_10145132](https://github.com/jantic/DeOldify/assets/153290092/91d2e6e7-400b-4516-b94e-86d1b4b9c26e)

2. Stable Model

![stable_model_10_10375436](https://github.com/jantic/DeOldify/assets/153290092/74680379-5ca6-4989-9b07-5231df750d16)
![stable_model_10_10375450](https://github.com/jantic/DeOldify/assets/153290092/0f816a69-5dad-40ac-919c-67b5cf0deb71)
![stable_model_10_10375566](https://github.com/jantic/DeOldify/assets/153290092/05e9e5bc-7df6-4a96-b969-24daf2ad8c2b)
![stable_model_10_10375773](https://github.com/jantic/DeOldify/assets/153290092/4b705436-2358-4a75-99a6-9cf71132603b)
![stable_model_10_10375928](https://github.com/jantic/DeOldify/assets/153290092/2a92ed18-564c-4888-ba64-9ee64d71d452)
![stable_model_10_10375948](https://github.com/jantic/DeOldify/assets/153290092/b00d370b-7468-4ba8-a450-fd435e293822)
![stable_model_10_10380013](https://github.com/jantic/DeOldify/assets/153290092/9fd94f9b-679e-4e03-ba70-ff8d6c32712b)
![stable_model_10_10380096](https://github.com/jantic/DeOldify/assets/153290092/cb490081-54b4-49dc-9fdf-10dc55fa6484)
![stable_model_10_10380144](https://github.com/jantic/DeOldify/assets/153290092/985314bd-93b8-4dae-9c4a-db697d95079d)

In this artistic vs stable model comparison, you can see artistic model is giving better results in human images compare to other category images but stable model is giving better results in other category images compare to human images. Means stable model is creating red color portion around lip and teeth part, which is the only problem in such outputs. So, is there any way I can good results in all category of images ? be it human or any other images. Means I am finding equilibrium in all category of images.

Like I have gone through the whole readme file and issue section for this problem but I haven't got any solution. So, I was thinking to train FFHQ dataset on artistic model. Would this be an good way to generate better results on human cases or I am missing any details while inferencing the images ?

@jantic it would be great if you can give some idea or solution about this problem.

**Comment by jantic** [comment]
As far as datasets that would help in terms of good results across all categories of images- I'd say Google's Open Images dataset ( https://storage.googleapis.com/openimages/web/index.html ) is probably your best bet. It's huge in comparison to what DeOldify was originally trained on, and is much more diverse.  But the problems go beyond just data. I've moved on past this particular training approach years ago, but if you were to improve upon it, my guess is increasing the batch size would go a long way. I had very limited compute resources when training this (1080 TI gpu with 11 GB VRAM!). A lot of things have changed in the past 5 years! 

Since it has been 5 years, there's definitely better approaches out there, too.  I've seen diffusion based stuff and I'd say that's probably the way to go now ( https://palette.fm ).
