### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mahaveergautamji** [jantic/DeOldify#504]
ImportError                               Traceback (most recent call last)
Cell In[1], line 5
      3 from deoldify.device_id import DeviceId
      4 #choices:  CPU, GPU0...GPU7
----> 5 device.set(device=DeviceId.GPU0)

File [~/AutoDeOldifyLocal/DeOldify/deoldify/_device.py:26](http://127.0.0.1:8888/lab/tree/AutoDeOldifyLocal/DeOldify/AutoDeOldifyLocal/DeOldify/deoldify/_device.py#line=25), in _Device.set(self, device)
     24 else:
     25     os.environ['CUDA_VISIBLE_DEVICES']=str(device.value)
---> 26     import torch
     27     torch.backends.cudnn.benchmark=False
     29 self._current_device = device    

File [~/miniconda3/envs/deoldify/lib/python3.10/site-packages/torch/__init__.py:199](http://127.0.0.1:8888/lab/tree/AutoDeOldifyLocal/DeOldify/miniconda3/envs/deoldify/lib/python3.10/site-packages/torch/__init__.py#line=198)
    197     if USE_GLOBAL_DEPS:
    198         _load_global_deps()
--> 199     from torch._C import *  # noqa: F403
    201 # Appease the type checker; ordinarily this binding is inserted by the
    202 # torch._C module initialization code in C
    203 if TYPE_CHECKING:

ImportError: /home/veeru/miniconda3/envs/deoldify/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

**Comment by jantic** [comment]
This is fixed.  Source of issue was this recent mkl update described [here](https://github.com/pytorch/pytorch/issues/123097). I put in a work around in the environment.yml (so you'll have to reinstall that).
