### ISSUE TITLE
Error on hugging faces

### ISSUE THREAD

**Issue by paulocoutinhox** [jantic/DeOldify#508]
Hi,

There an error on HF:
https://huggingface.co/spaces/PaddlePaddle/deoldify

Thanks.

**Comment by jantic** [comment]
Looks like Paddle Paddle's demos are broken across the board. I've removed the link. I won't be trying to maintain something like that on my own at this point.

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
