### ISSUE TITLE
Why using fastai rather than pure pytorch?

### ISSUE THREAD

**Issue by jinfagang** [jantic/DeOldify#51]
I think the fastai has some compatible issue as well as pytorch, in terms of complicity, less wrapper would be better

**Comment by jantic** [comment]
There's still some key components I used from Fast.AI that I really didn't want to rewrite and were really helpful.  That and I believe in the future of Fast.AI- they didn't have explicit GAN support at the time when I wrote this but...stay tuned on that :)
