### ISSUE TITLE
Runtime Resnet34 Model Downloading

### ISSUE THREAD

**Issue by ghost** [jantic/DeOldify#510]
How to avoid Resnet34 model runtime downlaoding. Basically I'm deploying this model on Lambda on AWS. Lambda doesn't allow runtime model downloading. As far as I tried to fix this runtime model downloading, the model is downloaded when virtual environment is activated and torchvision library is dowbloaded. Torchvision library then download Resnet34 model at runtime
Kindly help me to fix this issue. I'll be looking forward for your reply

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jantic** [comment]
This is beyond the scope of the project (it's just research being shared) but I'm going to guess that you just have to figure out where resnet34 gets downloaded to and then manually populate it before starting the virtual environment, if that's possible.
