### ISSUE TITLE
Web based implementation of DeOldify without any servers and frameworks...

### ISSUE THREAD

**Issue by akbartus** [jantic/DeOldify#511]
Hi! Wonderful repo! 
I recently developed a completely web-based implementation of DeOldify powered by Onnx and without any frameworks or server side code. Feel free to share it on your repository for those who are interested in serverless implementation of it. 
Here is the link:
https://github.com/akbartus/DeOldify-on-Browser

**Comment by jantic** [comment]
This is great!  I'm about to archive the repo (I need to move on) so this will be the last thing I add this to the readme. Do note though I keep running into glitches like this:

![image](https://github.com/user-attachments/assets/57edcd30-dd25-4757-9ef7-fe10f82941e5)

My guess is the quantization is making the model numerically unstable.
