### ISSUE TITLE
Thank you!  It worked!   (Where are you supposed to put the .h5?)

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [jantic/DeOldify#52]
I was shocked when I was able to colorize my own photos today.

I followed the directions in the readme and I'll be damned, it WORKED.

It's my first time using a Jupyter Notebook so there was a lot of room for error.

I wasn't able to figure out where exactly to put the .h5 file however.  I didn't see an empty set of folders to drop it into.  Perhaps more instructions on how to create that folder structure would be good. I ended up manually creating the folders user c:\user\mike\data\....

Thanks for creating and posting a working application.  SO many times I've met with dead-ends in these machine learning projects (edges for cats comes to mind).

**Comment by jantic** [comment]
My pleasure! 

Hmm..an empty slot to put the weights would be a great idea.... Keeps it unambiguous.  The folder it grabs from should be relative to where the notebook is that you're running.

**Comment by MikeTheWatchGuy** [comment]
Have you thought about putting a GUI onto the front end of this?

**Comment by MikeTheWatchGuy** [comment]
Oh, by the way, I've got a killer YOLO demo that uses my GUI!

https://github.com/MikeTheWatchGuy/PySimpleGUI/tree/master/YoloObjectDetection

You'll like it.

You can download the training file and it'll just work 👍

**Comment by shahidul56** [comment]
@jantic how about adding  [pixiedust](https://github.com/pixiedust/pixiedust) to the colab notebook

**Comment by jantic** [comment]
> @jantic how about adding [pixiedust](https://github.com/pixiedust/pixiedust) ui support to the colab notebook

Colab has it's own set of UI widgets that look quite nice that I'll want to try first.  I couldn't tell you what is better yet (this is the first I've heard of pixiedust). That'll have to come a bit later though (if I wind up doing it at all..time..)- working furiously on fast.ai v1/Pytorch v1 upgrade first!
