### ISSUE TITLE
Bad case of multiple people in a picture

### ISSUE THREAD

**Issue by howardlau1999** [jantic/DeOldify#57]
![bad](https://user-images.githubusercontent.com/5250490/49458083-0f5d8400-f827-11e8-84a6-d4f6a85239b5.png)

No one seems to be colorized correctly...

**Comment by howardlau1999** [comment]
Not much improvement after increasing render factor
![bad1](https://user-images.githubusercontent.com/5250490/49458256-6ebb9400-f827-11e8-865b-a4f6d5145491.png)

**Comment by jantic** [comment]
Yeah the smaller, more further away, and cluttered objects are in a picture, the harder time model will have generally speaking.  Much like it'd be hard for a person to manually colorize such a scene, I think.  

I'm working on improving the model, I assure you!
