### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at ..\aten\src\THC\THCGeneral.cpp:663

### ISSUE THREAD

**Issue by vamzii** [jantic/DeOldify#64]
this is my config
Collecting environment information...
PyTorch version: 0.3.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0
OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect
Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 417.35
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll
Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.6            py36h6288b17_0
[conda] mkl_random                1.0.2            py36h343c172_0
[conda] pytorch                   0.3.1           py36_cuda90_cudnn7he774522_2  [cuda90]  peterjc123
[conda] torchtext                 0.3.1                     <pip>
[conda] torchvision               0.2.1                     <pip>

this is the output of collect_env.py
this is the error i get if i try to use colorizeVisualization in jupyter notebook
RuntimeError: cuda runtime error (2) : out of memory at ..\aten\src\THC\THCGeneral.cpp:663

so does this mean my 1070 is running out of memory? any suggestions in this matter please?
what gpu did you people use to run this ?
thanks

**Comment by jantic** [comment]
So a few things:  First, Windows just isn't officially supported yet by me.  I have other higher priority items before I try to seriously knock that out.  That being said, there's a thread on this memory issue that appears to be Windows specific, here:

https://github.com/jantic/DeOldify/issues/49

Another thing that jumped out to me looking at what you posted above is that your Pytorch version is 0.3.1, which is below minimum required (0.4.1).  That's really indicating to me that the conda install wasn't used- I'd go right to the instructions on that in the readme and use that to install prereqs instead- much easier!

**But even easier than what I just said**:  Just use the Colab notebook- it comes with a free 11GB GPU and none of the install hassles!  https://colab.research.google.com/github/jantic/DeOldify/blob/master/DeOldify_colab.ipynb

**Comment by vamzii** [comment]
oh thank you for your time for replying my queries my friend,
i am making a youtube series on deep-learning, so i show people how to setup awesome apps like yours on their local machines, not the technical aspects but a how to video, with all the credits given to the app maker.
that was the reason i was trying to set it up on my windows machine .
