### ISSUE TITLE
Unpickle error with latest weights after conda env install

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [jantic/DeOldify#67]
I've just installed a clean conda environment, and on loading the pretrained weights I get the following error: 
```
UnpicklingError                           Traceback (most recent call last)
<ipython-input-4-0984d2fd4ebb> in <module>
----> 1 filters = [Colorizer34(gpu=0, weights_path=colorizer_path,nf_factor=2, map_to_orig=True)]
      2 #filters = [DeFader(gpu=3, weights_path=defader_path, nf_factor=2), Colorizer34(gpu=0, weights_path=colorizer_path,nf_factor=2, map_to_orig=True)]
      3 vis = ModelImageVisualizer(filters, render_factor=render_factor, results_dir='result_images')

~\Projects\DeOldify\fasterai\filters.py in __init__(self, gpu, weights_path, nf_factor, map_to_orig)
    119 class Colorizer34(AbstractColorizer):
    120     def __init__(self, gpu:int, weights_path:Path, nf_factor:int=2, map_to_orig:bool=True):
--> 121         super().__init__(gpu=gpu, weights_path=weights_path, nf_factor=nf_factor, map_to_orig=map_to_orig)
    122 
    123     def _get_model(self, nf_factor:int, gpu:int)->GeneratorModule:

~\Projects\DeOldify\fasterai\filters.py in __init__(self, gpu, weights_path, nf_factor, map_to_orig)
     83         self.model = self._get_model(nf_factor=nf_factor, gpu=gpu)
     84         self.gpu = gpu
---> 85         self._init_model(self.model, weights_path)
     86         self.render_base=16
     87         self.map_to_orig=map_to_orig

~\Projects\DeOldify\fasterai\filters.py in _init_model(self, model, weights_path)
     28 
     29     def _init_model(self, model:nn.Module, weights_path:Path):
---> 30         load_model(model, weights_path)
     31         model.eval()
     32         torch.no_grad()

~\Projects\DeOldify\fastai\torch_imports.py in load_model(m, p)
     27 def save_model(m, p): torch.save(m.state_dict(), p)
     28 def load_model(m, p):
---> 29     sd = torch.load(p, map_location=lambda storage, loc: storage)
     30     names = set(m.state_dict().keys())
     31     for n in list(sd.keys()): # list "detatches" the iterator

~\Anaconda3\envs\deoldify\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module)
    356         f = open(f, 'rb')
    357     try:
--> 358         return _load(f, map_location, pickle_module)
    359     finally:
    360         if new_fd:

~\Anaconda3\envs\deoldify\lib\site-packages\torch\serialization.py in _load(f, map_location, pickle_module)
    530             f.seek(0)
    531 
--> 532     magic_number = pickle_module.load(f)
    533     if magic_number != MAGIC_NUMBER:
    534         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.
```

I'm using pickle 4.0. Any Suggestions? With what pickle version were they written?

**Comment by jantic** [comment]
@Baukebrenninkmeijer Simple suggestion:  Just download the weights again.  The file appears to be corrupted.  I've seen this happen before believe it or not and that was the solution.

**Comment by jantic** [comment]
Ok so next question- did you use the conda install described in the readme?  That's your best bet to avoid issues.

Unfortunately this seems like it's specific to your environment so figuring it out from my end is tough.  So I'd focus on getting synched up with a matching environment first.

That also includes OS- I'm assuming you're using Linux?

**Comment by Baukebrenninkmeijer** [comment]
Yeah, I just used the environment.yml, not much else to it, right? I'll try with a new environment. 
I'll fiddle a bit more, but thought maybe it was a known issue. I'm using Windows 10 with this. Can't rule out that has something to do with it, but that would surprise me.

**Comment by jantic** [comment]
Yeah Windows 10 isn't officially supported here yet in my effort so I haven't tested/verified that anything works there.  I know others have gotten it to run but have run into issues.

**Comment by Baukebrenninkmeijer** [comment]
I understand, but conda (and pickle for that matter) has essentially no difference between OSs, so even though it's a different OS, the issue is still relevant.

**Comment by jantic** [comment]
I'm not dismissing the likelihood that it's a legit issue.  It's more of a practical consideration at this point: I don't have a reliable way to reproduce this yet, and this is the first time I've heard of this (there's a lot of users!).  So...I have to keep myself sane, basically, and wait for that, as opposed to try to reproduce the environment your working on based on what you're telling me, hunting down an issue that hasn't been reported by anybody else.  That's basically it- prioritization.

**Comment by jantic** [comment]
Keeping open in case anybody else reports it.

**Comment by Baukebrenninkmeijer** [comment]
Ah alright, understandable. 
To add some more info; I tried recreating the environment and this did not fix the issue.

**Comment by jantic** [comment]
@Baukebrenninkmeijer Just thought of something: The '<' character it's complaining about there happens to be the opening tag of an html tag.  Here's my guess:  Perhaps the ".h5" file you downloaded isn't in fact .h5, but the html page it's hosted on instead?  This has happened to me before in using curl.  Easy way to verify:  Try opening the .h5 file using a text editor.  Also- the file should be very big (hundreds of MB if I remember correctly).

**Comment by Baukebrenninkmeijer** [comment]
:') Yup, that's it. Thanks for the help, lad.

**Comment by jantic** [comment]
@Baukebrenninkmeijer Great to hear.
