### ISSUE TITLE
Red hand in example

### ISSUE THREAD

**Issue by danvk** [jantic/DeOldify#7]
These colorizations look amazing! Not sure if you noticed, but the hand in this image on the main page stuck out like a … sore thumb?
![image](https://user-images.githubusercontent.com/98301/48010811-53584e80-e0ec-11e8-8a9d-2665deb15130.png)

Keep up the great work!

**Comment by noahc** [comment]
Yes, https://news.ycombinator.com/item?id=18363870

**Comment by danvk** [comment]
Doh!

**Comment by jantic** [comment]
LOL don't feel bad.  It's a giant ass README.  And it does stick out like a sore...hand.  Not entirely sure if she really did just have a cartoonishly large/red hand there now that I look at the source image....

**Comment by danvk** [comment]
Perhaps the model thought it was some kind of mushroom growing on the tree?
