### ISSUE TITLE
scope problem - pytorch and JIT

### ISSUE THREAD

**Issue by miaoqiz** [jantic/DeOldify#73]
Hi,

Looks like it is the scope related issue. The message pops up when the training starts.

"Failed to generate graph for model: index 0 is out of bounds for axis 0 with size 0. Note that there's an outstanding issue with scopes being addressed here:  https://github.com/pytorch/pytorch/pull/12400"

Any suggestions on whether it will affect training? and how to get rid of it?

Thanks!

**Comment by jantic** [comment]
This won't affect training.  This is strictly tensorboard functionality I built in to generate a graph of the model.  I found the graph of the model to be pretty useless so I'm just getting rid of it all together with the FastAI v1 upgrade.
