### ISSUE TITLE
results don't look as expected 

### ISSUE THREAD

**Issue by nimamoradi** [jantic/DeOldify#77]
i newbie in image processing  so my question might look silly<br>
i want to colorized and video i used `cv2.VideoCapture` to iterate video frame by frame<br>
i don't want to save each frame to file both for original video and colorized one
<br> so in loop i transformed images   
<pre><code>          for filt in vis.filters:
             filtered_image = filt.filter(image, image_fir, render_factor=38)
           
</pre></code>

here is a sample original picture 

![image](https://user-images.githubusercontent.com/18138551/54449189-c6409880-4762-11e9-8f56-dcda175724f6.png)
i save `filtered_image ` in `VideoWriter` 
<br>
output is like this
![image](https://user-images.githubusercontent.com/18138551/54449473-6bf40780-4763-11e9-9fd9-aeeb70225e2e.png)

while i can produce good looking images if i use file
<pre><code>

for img in os.listdir("/path/"):
  img_path = "/path/" + str(img)
  if os.path.isfile(img_path):
       vis.plot_transformed_image(img_path) 
</code></pre>

![image](https://user-images.githubusercontent.com/18138551/54449616-c8efbd80-4763-11e9-93ce-5b6fd6429bd0.png)
@jantic

**Comment by jantic** [comment]
I don't have full context to be sure if I'm correct, but it looks most likely that you're not preprocessing the images in the same way as the open_image function does, which is used in visualize.py.  I'll paste that here for convenience.  So tl;dr- I'd use the open_image function if you aren't already to get the images.

```
def open_image(fn):
    """ Opens an image using OpenCV given the file path.
    Arguments:
        fn: the file path of the image
    Returns:
        The image in RGB format as numpy array of floats normalized to range between 0.0 - 1.0
    """
    flags = cv2.IMREAD_UNCHANGED+cv2.IMREAD_ANYDEPTH+cv2.IMREAD_ANYCOLOR
    if not os.path.exists(fn) and not str(fn).startswith("http"):
        raise OSError('No such file or directory: {}'.format(fn))
    elif os.path.isdir(fn) and not str(fn).startswith("http"):
        raise OSError('Is a directory: {}'.format(fn))
    else:
        #res = np.array(Image.open(fn), dtype=np.float32)/255
        #if len(res.shape)==2: res = np.repeat(res[...,None],3,2)
        #return res
        try:
            if str(fn).startswith("http"):
                req = urllib.urlopen(str(fn))
                image = np.asarray(bytearray(req.read()), dtype="uint8")
                im = cv2.imdecode(image, flags).astype(np.float32)/255
            else:
                im = cv2.imread(str(fn), flags).astype(np.float32)/255
            if im is None: raise OSError(f'File not recognized by opencv: {fn}')
            return cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
        except Exception as e:
            raise OSError('Error handling image at: {}'.format(fn)) from e
```

**Comment by jantic** [comment]
Closing
