### ISSUE TITLE
Add noise removal

### ISSUE THREAD

**Issue by Spenhouet** [jantic/DeOldify#80]
NVIDIA released a paper on a model that removes noise. It looks really promising and could also be used for this project in a pre-processing pipeline.

Video: https://www.youtube.com/watch?v=pp7HdI0-MIo
Paper: https://arxiv.org/abs/1803.04189

**Comment by jantic** [comment]
This is actually already on a TODO list of things to explore that we're maintaining separately.  It's indeed a really promising idea.  I'll keep this open for now- thanks!

**Comment by jqueguiner** [comment]
What do you think about this new implementation? https://github.com/Ding-Liu/NLRN

**Comment by jantic** [comment]
I'm adding this to bookmarks for options in denoising when I get to that point.  Hopefully soon.  Thanks for bringing that to my attention!

**Comment by kirkgutierrdd** [comment]
you can use"topaz denoise" if really wanted

**Comment by jantic** [comment]
@kirkgutierrdd Yeah that's a great point.  The landscape, and the direction I want to take this project, has evolved since this issue was opened.  I'm going to close it for now as I don't see the sense in trying to do something that's already being done well elsewhere.
