### ISSUE TITLE
Not able to save trained weights on custom training

### ISSUE THREAD

**Issue by prnvjb** [jantic/DeOldify#81]
Hi,
Thank you so much for this implementation.
I ran ColorizeTraining.ipynb in GCP VM with a Tesla P100 on my own image data of about 2500images. I guess the training went well but didn't save any weights?
Please help.

**Comment by jantic** [comment]
So two things to look at here:

First, that's a really small number of images.  The save_iters parameter of the GANTrainer constructor is set to 1000.  Meaning- every 1000 batch iterations it's going to save the model (counted per GANTrainer instance).  Be careful about that number there- it's not images, it's batches of images, so chances are you're not even hitting that number of batches in this case unless you're running many training epochs.  So you can lower this parameter easily but do keep in mind that saves are expensive in this version of DeOldify (new one is coming out soon).

If that's not the issue the only other thing I can think of is that you may just not be looking in the right place for the weights.  The place to look is wherever they're set to in this line in the notebook:

gpath = IMAGENET.parent/(proj_id + '_gen_128.h5')
dpath = IMAGENET.parent/(proj_id + '_critic_128.h5')
