### ISSUE TITLE
Could someone update the Colab File?

### ISSUE THREAD

**Issue by nixxon94** [jantic/DeOldify#83]
Hi there! I used the Colab file without any issues a month ago and wanted to try it again today but there seem to be issues with pytorch now. I am not very versed in all this yet but would appreciate it if someone could get the file back up and running :) 

https://colab.research.google.com/github/jantic/DeOldify/blob/master/DeOldify_colab.ipynb

**Comment by jantic** [comment]
We're going to be doing a new release in a little over a week, and there's going to be a brand new Colab there that definitely works.  I'll keep this open for now but the gist is I have too much going on right now to address this on the soon to be outdated version of DeOldify.

**Comment by nixxon94** [comment]
> We're going to be doing a new release in a little over a week, and there's going to be a brand new Colab there that definitely works. I'll keep this open for now but the gist is I have too much going on right now to address this on the soon to be outdated version of DeOldify.

Thanks so much for the quick reply @jantic ! Glad to hear that. I managed to get it running again with the torch version 1.0.0 from
 `http://download.pytorch.org/whl/{accelerator}/torch-1.0.0-{platform}-linux_x86_64.whl`
and setting the accelerator to cu100

**Comment by jantic** [comment]
New version of DeOldify is up with the updated Colabs.  Closifying.
