### ISSUE TITLE
Error when switching to artistic=False

### ISSUE THREAD

**Issue by gaiar** [jantic/DeOldify#86]
Running code

```
!wget https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeStable_gen.pth?dl=0 -O ./models/ColorizeStable_gen.pth

colorizer = get_image_colorizer(artistic=False)

```

Produces an error

```
/usr/local/lib/python3.6/dist-packages/fastai/data_block.py:442: UserWarning: Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.
  warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
/usr/local/lib/python3.6/dist-packages/fastai/data_block.py:445: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  or pass `ignore_empty=True` when labelling to remove this warning.""")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-27-366a8bd889a1> in <module>()
----> 1 colorizer = get_image_colorizer(artistic=False)

11 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/utils/spectral_norm.py in __call__(self, state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
    163         if version is None or version < 1:
    164             with torch.no_grad():
--> 165                 weight_orig = state_dict[prefix + fn.name + '_orig']
    166                 weight = state_dict.pop(prefix + fn.name)
    167                 sigma = (weight_orig / weight).mean()

KeyError: 'layers.4.conv.0.weight_orig'
```

Changes applied to Notebook https://colab.research.google.com/github/jantic/DeOldify/blob/master/ImageColorizerColab.ipynb

**Comment by gaiar** [comment]
I've used the wrong link. Correct link is `https://www.dropbox.com/s/mwjep3vyqk5mkjc/ColorizeStable_gen.pth?dl=0`

**Comment by zarifaziz** [comment]
@gaiar how did you fix this issue? I'm getting an error that says:

FileNotFoundError: [Errno 2] No such file or directory: 'models/ColorizeStable_gen.pth'

after I set 'artistic=False'

**Comment by jantic** [comment]
This isn't supported guys.  I'm keeping the notebooks as simple as possible to make it so that there's only one way of doing things.  If you want to do rendering with the stable model I'd just suggest installing locally (there's a notebook specifically setup already for stable model colorization).

**Comment by alexandrevicenzi** [comment]
@jantic I got both models on Colab, are you interested in a patch? It's still simple but download extra data.

**Comment by jantic** [comment]
@alexandrevicenzi Thanks for the offer!  So believe it or not, the way it is now was a deliberate choice.  It might seem broken to do it this way but the motivation was two-fold:  Avoid having any conditional workflow possibilities in the Colab notebook (to avoid confusion and false reports of bugs), and to not have to download any more data than what was already needed.   If we were to offer the stable model in the Colabs, we'd probably opt to make it a separate notebook.  But then that'd probably also add confusion.

**Comment by alexandrevicenzi** [comment]
@jantic I understand your point of view. I'll keep my custom Colab just for me in this case, as I want to try both models to see which one gives me better results.
