### ISSUE TITLE
How to load all images from folder?

### ISSUE THREAD

**Issue by djavo22** [jantic/DeOldify#87]
Have issue to load multiple images one by one(from one folder) .Do not know which code to write in jupyter lab

My graphic card is 1050ti 4GB, 

with this code I am able to colorize single photo but I want to speed up time cause have lot of grayscale photos to color....

> #NOTE:  Max is 45 with 11GB video cards. 35 is a good default
render_factor=23
#NOTE:  Make source_url None to just read from file at ./video/source/[file_name] directly without modification
source_url=None
source_path = 'C:/KOLOR/test_images/proba.jpg'
result_path = 'C:/KOLOR/results/proba.jpg'

if source_url is not None:
    result_path = colorizer.plot_transformed_image_from_url(url=source_url, path=source_path, render_factor=render_factor, compare=True)
else:
    result_path = colorizer.plot_transformed_image(path=source_path, render_factor=render_factor, compare=True)
show_image_in_notebook(result_path)

> 

Have tried with:

> for img in os.listdir("C:/KOLOR/test_images"):
  img_path = "C:/KOLOR/test_images" + str(img)
  if os.path.isfile(img_path):
       vis.plot_transformed_image(img_path) 

> 

not success

 

Please help...

**Comment by jantic** [comment]
This is one of those things I'll have to draw a line on with my time and decline to address this or similar questions.  This isn't something you need specifically me or @dana-kelley to answer as this isn't really specific to DeOldify, and it's not something I'm looking to support in the code anymore.  This is a general programming question.  We'd love to help but it really boils down to time management for us.

**Comment by gravitydeep** [comment]
instead of replying that you don't have time to answer a simple question that I suppose all beginners in development ask themselves you could give the solution !!!!

**Comment by snynisada** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
