### ISSUE TITLE
Add back audio from source when available to video renders.

### ISSUE THREAD

**Issue by jantic** [jantic/DeOldify#88]
Title says it all.  Having audio dropping from videos sucks.

**Comment by lf-openthos** [comment]
It's easy for ffmpeg to remux the audio track back from the original one.
Such as
> ffmpeg -i original.video -vn -acodec copy temp.aac
> ffmpeg -i results.video -i temp.aac -codec copy final.video

**Comment by jantic** [comment]
Thanks!  I'll try this soon.

**Comment by btahir** [comment]
This is what you need:

```
from moviepy.editor import *

# get the original video
videoclip = VideoFileClip('original.mp4')

# extract the audio from video
audioclip = videoclip.audio

# DeOldify video as usual and get the colorized output
video = VideoFileClip('colorized_output.mp4')

# set audio
final = video.set_audio(audioclip)

# save with required settings (mostly to make Quicktime happy and recognize the audio): https://github.com/Zulko/moviepy/issues/820
final.write_videofile("final_output.mp4", codec='mpeg4', audio_codec='aac', temp_audiofile='temp-audio.m4a', remove_temp=True)
```
You can look at the options for saving here: https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html

Quicktime is really annoying and won't recognize the audio so you have to set those codecs for it.

Love the project. Great job! :)

**Comment by btahir** [comment]
Working pretty well :)

https://www.youtube.com/watch?v=JACcWJRUkYc&feature=youtu.be

**Comment by jqueguiner** [comment]
https://github.com/jantic/DeOldify/pull/108

**Comment by btahir** [comment]
Sweet! One more thing I should mention. I realized that writing the Video to mpeg4 leads to bad quality video (for some reason). If you change the codec to libx264, the quality is much better!

`final.write_videofile(out, codec='libx264', audio_codec='aac', temp_audiofile='temp-audio.m4a', remove_temp=True)`

**Comment by btahir** [comment]
Bonus: You can add a thread parameter to leverage multithreading which leads to a much faster operation. Example:

`final.write_videofile(out, codec='libx264', threads=64, audio_codec='aac', temp_audiofile='temp-audio.m4a', remove_temp=True)`

**Comment by jqueguiner** [comment]
Yep also saw the bad quality, fixing it

**Comment by jqueguiner** [comment]
https://github.com/jantic/DeOldify/pull/108/commits/3df2647500a4f82571beac0fc5101395390c9bc0
Fixed and tested

**Comment by jantic** [comment]
Ok guys, this functionality is merged in now. Thanks!
