### ISSUE TITLE
Add Exemplar-based Option

### ISSUE THREAD

**Issue by dorpxam** [jantic/DeOldify#93]
What about an exemplar-based option to this wonderful project? 

For example, I have some 60's B&W music video with some additional color pictures (from photographer) of the corresponding video. 

That can be a great benefice to add something like the Microsoft-Asia project: https://github.com/msracver/Deep-Exemplar-based-Colorization

In any case, DeOldify has already a great potential. Thank you so much !

**Comment by jantic** [comment]
This is something I have no idea how to gracefully integrate into the existing functionality yet. It certainly would be great but the "how" is the hard part.

**Comment by jantic** [comment]
I've thought about this further.  This is definitely way beyond the scope of what I think is reasonable for this project. It may be done as a commercial effort but anybody that wants to tackle this in their own fork is more than welcome to!
