### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by GraphicVisuals** [jantic/DeOldify#95]
I've tried working this thing several times - to none of which makes any sense!? Which becomes increasingly fucking annoying after the second hour of attempting it to no results, unclear and poorly written instructions - and all on top of even knowing the thing work!

**Comment by zarifaziz** [comment]
No results? the ImageColorizerColab notebook runs very smoothly

**Comment by GraphicVisuals** [comment]
I'm trying to get a video to colourize.

**Comment by GraphicVisuals** [comment]
And non of the listed instructions make sense to me - not sure if that's because I have no coding experience... and clearly, the damb thing works - because I've seen the results and I wouldn't be asking.

**Comment by jantic** [comment]
Colabs aren't really for people who aren't comfortable with code.  Sorry but it's not made for you. 

Also..... I'm not exactly the type to respond favorably to being talked to like this. Not sure if you needed that reminder but it appears that's the case.

**Comment by GraphicVisuals** [comment]
Honestly, really disappointed by the put down on this - I don't want in any way to learn how to code just so I can colourise a video 'quickly.' Also, no offence - but I'm stressed after hours of attempting this, so I'm not exactly gonna pleased...

**Comment by jantic** [comment]
It's not a product dude.  And you're not a customer.  End of story.

**Comment by GraphicVisuals** [comment]
Product? - I want to use it as a tool for a start and second, I dunno what you mean by customer, but I wouldve actually paid for this - if that's the irony?
