### ISSUE TITLE
Error when switching to artistic=False

### ISSUE THREAD

**Issue by zarifaziz** [jantic/DeOldify#96]
Hi, I'm getting the following error when switching to artistic=False on the Image Colab notebook:
`KeyError: 'layers.4.conv.0.weight_orig`

I even made sure I downloaded the ColorizeStable_gen.pth using:
`!wget wget https://www.dropbox.com/s/zkehq1uwahhbc2o/ColorizeArtistic_gen.pth?dl=0 -O ./models/ColorizeStable_gen.pth`

**Comment by jantic** [comment]
There's an error in the line above.  Here's the fixed version:

!wget wget https://www.dropbox.com/s/mwjep3vyqk5mkjc/ColorizeStable_gen.pth?dl=0 -O ./models/ColorizeStable_gen.pth

**Comment by monteforest** [comment]
This link doesn't seem to be working for me. Is this still the location of the stable model?

**Comment by monteforest** [comment]
nevermind. Got it.
